import { makeGuide, sources } from './shared';

export const bookingGuides = [
  makeGuide({
    slug: 'can-ai-receptionist-book-jobs-for-tradies', number: 71, category: 'Bookings & calendars',
    title: 'Can an AI Receptionist Book Jobs for Tradies?',
    description: 'When direct booking is useful, when a booking request is safer and what must be connected before a time is promised.',
    directAnswer: 'Yes, but only when the business has connected current availability, defined duration, travel, skill and approval rules, and tested clashes and failures. TradieRelay’s cautious standard flow captures preferred times and creates a booking request for the tradie to confirm. Direct calendar booking is enabled only for a configured and tested customer setup.',
    heroImage: '/blog/71-ai-booking-tradie-jobs.webp', heroAlt: 'Australian plumber checking a booking request on a tablet beside a service van',
    keyPoints: ['A preferred time is not a confirmed booking.', 'Direct booking needs live availability plus travel and skill rules.', 'Start with human confirmation before enabling automatic placement.'],
    sections: [
      { heading: 'Choose booking request or direct booking', paragraphs: ['A booking request records what the customer wants and lets a person confirm. Direct booking writes a time into a connected calendar. The second option removes work only when the calendar and rules are dependable.'] },
      { heading: 'Define what makes a slot valid', bullets: ['Correct technician or trade skill', 'Enough duration for the job type', 'Service-area and travel allowance', 'Working hours and protected time', 'Parts or access prerequisites', 'No unresolved urgent work'] },
      { heading: 'Keep the promise precise', paragraphs: ['If the slot is not confirmed, say the business will review the requested time. If it is confirmed through a tested integration, send a clear confirmation with the date, window and change process. Never blur the two.'], callout: { label: 'WORDING RULE', text: '“Requested” and “booked” are different customer promises.' } },
      { heading: 'Test the awkward cases', paragraphs: ['Try a clash, an unavailable technician, an out-of-area job, a long job in a short slot, a cancellation and a calendar outage. The customer must always receive a sensible fallback rather than a false booking.'] },
      { heading: 'Let the owner control expansion', paragraphs: ['Begin with one repeatable job type and a narrow window. Review whether staff still move or correct the bookings. Expand only when the direct route reliably deletes admin work.'] },
    ],
    example: { title: 'A service request, not a false booking', text: 'Sarah asks for Thursday afternoon. TradieRelay records that preference and places the job in “Needs you”. The plumber confirms 2–4 pm, and Sarah receives the confirmed time. This matches the current standard workflow; direct calendar placement requires additional connected setup.' },
    productVisual: 'pipeline', productCaption: 'The working pipeline clearly separates a time request that needs approval from a genuinely booked job.',
    table: { headers: ['Mode', 'Customer hears', 'Business action'], rows: [['Request', 'We will review this time', 'Confirm or offer another window'], ['Direct booking', 'Your time is booked', 'Calendar integration owns the slot'], ['Fallback', 'We will call to arrange it', 'Human resolves missing availability']] },
    faqs: [{ question: 'Does TradieRelay book directly by default?', answer: 'No. The standard cautious flow captures preferred times for human confirmation.' }, { question: 'Can it book different technicians?', answer: 'Only when skills, calendars, territories and fallbacks are connected and tested.' }, { question: 'What if the calendar is offline?', answer: 'The caller should receive a booking-request or callback fallback, not an invented slot.' }],
    sources: [sources.aiStandard], related: ['ai-receptionist-setup-checklist-australian-tradies', 'how-tradie-set-call-answering-rules', 'test-ai-receptionist-before-going-live'],
  }),
  makeGuide({
    slug: 'appointment-windows-for-trade-business', number: 72, category: 'Bookings & calendars',
    title: 'Should Tradies Offer Exact Times or Appointment Windows?',
    description: 'How to set realistic arrival windows that respect travel, job uncertainty and the customer’s day.',
    directAnswer: 'Most mobile trade businesses are safer offering a realistic arrival window than an exact minute because the previous job, travel and site conditions can change. Use exact times only for work that is genuinely predictable. Whatever you offer, explain whether it is an arrival window, appointment start or callback time.',
    heroImage: '/blog/72-tradie-appointment-windows.webp', heroAlt: 'Australian electrician planning service appointment windows on a wall calendar',
    keyPoints: ['Name exactly what the time means.', 'Allow for travel and earlier-job variability.', 'Send changes early instead of quietly missing the window.'],
    sections: [
      { heading: 'Pick a promise the operation can keep', paragraphs: ['A two-hour arrival window may be more useful than an exact time that regularly slips. The right width depends on job type, territory and how much uncertainty the day carries.'] },
      { heading: 'Separate arrival, start and callback times', paragraphs: ['“We will call between 9 and 10” is not “the electrician arrives at 9”. Put the promise in the confirmation so the customer does not fill in the gap themselves.'] },
      { heading: 'Build windows from real constraints', bullets: ['Expected job duration', 'Travel between service areas', 'Parking and access', 'Urgent-work allowance', 'Parts collection', 'Crew and licence requirements'] },
      { heading: 'Give the customer a change path', paragraphs: ['A confirmation should say how to reply or call if the window no longer works. When the schedule changes, one named person or workflow should own the update.'] },
      { heading: 'Do not let the AI tighten the promise', paragraphs: ['The assistant repeats approved windows. It should not turn “morning” into 9 am or offer an exact time because the caller presses for certainty.'], callout: { label: 'PROMISE CONTROL', text: 'The system can offer only the windows the business has approved and made available.' } },
    ],
    example: { title: 'A realistic plumbing window', text: 'The business offers 8–10 am and 12–2 pm arrival windows for routine service. The customer chooses 8–10 am, the plumber confirms it and the SMS repeats “arrival window”. No exact 8 am promise is created.' },
    productVisual: 'customer-quote', productCaption: 'Customer-facing messages should show a clear agreed window and next action, using the same plain wording as the team.',
    faqs: [{ question: 'How wide should a window be?', answer: 'Use operational evidence. It should be narrow enough to help the customer and wide enough to be dependable.' }, { question: 'Can urgent jobs use windows?', answer: 'They can, but do not present an estimate as a guaranteed arrival.' }, { question: 'Can the AI change a window?', answer: 'Only through an approved rescheduling flow tied to current availability or human review.' }],
    sources: [sources.aiStandard], related: ['can-ai-receptionist-book-jobs-for-tradies', 'ai-receptionist-setup-checklist-australian-tradies', 'what-happens-after-tradie-misses-call'],
  }),
  makeGuide({
    slug: 'prevent-double-bookings-with-ai-receptionist', number: 73, category: 'Bookings & calendars',
    title: 'How Do You Prevent Double Bookings with an AI Receptionist?',
    description: 'The calendar, locking, fallback and human rules needed before automated booking can be trusted.',
    directAnswer: 'Prevent double bookings by using one current source of availability, reserving a slot atomically, checking skill and duration before confirmation, handling calendar errors as booking requests, and testing simultaneous callers. If the system cannot prove the slot is held, it must not tell the customer it is booked.',
    heroImage: '/blog/73-prevent-double-bookings.webp', heroAlt: 'Australian trade office coordinator comparing two overlapping bookings on a scheduling screen',
    keyPoints: ['One calendar must be the source of truth.', 'A slot is confirmed only after the write succeeds.', 'Failures fall back to a request, not a promise.'],
    sections: [
      { heading: 'Choose the source of truth', paragraphs: ['If the office calendar, a job-management system and a personal phone all show different availability, automation will expose the conflict. Decide which system owns the final booking before connecting anything.'] },
      { heading: 'Check more than an empty gap', bullets: ['Required technician or crew', 'Job duration and buffer', 'Territory and travel', 'Working hours and leave', 'Equipment or vehicle', 'Existing tentative holds'] },
      { heading: 'Confirm only after the slot is held', paragraphs: ['The customer-facing confirmation should follow a successful calendar write. If two calls request the same slot, only the first completed reservation can receive the booking promise.'] },
      { heading: 'Design the failure path', paragraphs: ['An unavailable calendar, timeout or ambiguous result should create a review task. The caller hears that the time has been requested and a person will confirm.'], callout: { label: 'SAFE FALLBACK', text: 'No confirmed write means no confirmed booking.' } },
      { heading: 'Test simultaneous and edited bookings', paragraphs: ['Use two phones to request the same slot. Then move, cancel and reopen it. Confirm every system and message agrees before real customers can book directly.'] },
    ],
    example: { title: 'Two callers want Friday morning', text: 'The first booking successfully reserves the qualified technician. The second request finds the slot unavailable and offers another approved option or human callback. Neither caller receives a duplicate confirmation.' },
    productVisual: 'pipeline', productCaption: 'The pipeline keeps unresolved time requests visible when a direct booking cannot be safely confirmed.',
    faqs: [{ question: 'Can two calendars be connected?', answer: 'They can, but one system still needs to own availability and conflict rules.' }, { question: 'What is a tentative hold?', answer: 'A temporary reservation while the booking is completed. Its expiry and customer wording must be defined.' }, { question: 'Does the current standard product directly lock calendars?', answer: 'Not by default. TradieRelay captures preferred times unless a customer-specific calendar integration has been configured and tested.' }],
    sources: [sources.aiStandard, sources.aiGuardrails], related: ['can-ai-receptionist-book-jobs-for-tradies', 'test-ai-receptionist-before-going-live', 'what-if-ai-receptionist-service-goes-down'],
  }),
  makeGuide({
    slug: 'ai-receptionist-handle-rescheduling', number: 74, category: 'Bookings & calendars',
    title: 'How Should an AI Receptionist Handle Rescheduling?',
    description: 'A safe rescheduling flow that verifies the job, captures the change and avoids deleting the original booking too early.',
    directAnswer: 'A rescheduling flow should identify the customer and existing job, capture why and when they need to change, check who may approve the move, and preserve the original booking until a replacement is confirmed. The assistant should never guess which job the caller means or silently move a time in an unconnected diary.',
    heroImage: '/blog/74-ai-rescheduling-tradie.webp', heroAlt: 'Australian homeowner and trade office coordinator discussing a changed appointment time by phone',
    keyPoints: ['Verify the existing job before changing anything.', 'Keep the original slot until the new one is confirmed.', 'Send a written confirmation of the final change.'],
    sections: [
      { heading: 'Find the right booking', paragraphs: ['Use the caller number, name, address, job reference and scheduled date. If two jobs match or the details conflict, send the case to a person instead of guessing.'] },
      { heading: 'Capture the requested change', paragraphs: ['Ask whether the customer needs a later time, another day, different site contact or full cancellation. Record constraints such as tenant access or another trade on site.'] },
      { heading: 'Protect the original slot', paragraphs: ['Do not release it until a valid replacement is held or a person confirms the cancellation. Otherwise a failed change can leave the customer with no booking.'] },
      { heading: 'Coordinate the human impact', bullets: ['Notify the diary owner', 'Check technician and territory', 'Check access and parts', 'Record the customer’s reason', 'Update every connected calendar', 'Send the final confirmation'] },
      { heading: 'Use a clear unresolved status', paragraphs: ['When the change is only requested, say so. The dashboard should show “reschedule requested” rather than pretending the new time is final.'], callout: { label: 'STATUS MATTERS', text: 'A requested change is not a completed change.' } },
    ],
    example: { title: 'A tenant loses access on Tuesday', text: 'The tenant asks to move the booking to Thursday. TradieRelay verifies the address and existing Tuesday booking, records Thursday preferences and alerts the office. Tuesday remains protected until the office confirms the replacement and texts the final time.' },
    productVisual: 'pipeline', productCaption: 'A needs-you status keeps a requested change visible until the diary owner completes it.',
    faqs: [{ question: 'Can the AI move a job automatically?', answer: 'Only when the booking system, authority and clash rules are connected and tested.' }, { question: 'What if the caller number has changed?', answer: 'Use other identifiers and send uncertain matches to human review.' }, { question: 'Should the old booking be deleted first?', answer: 'No. Preserve it until the replacement or cancellation is confirmed.' }],
    sources: [sources.aiStandard], related: ['can-ai-receptionist-book-jobs-for-tradies', 'appointment-windows-for-trade-business', 'how-ai-receptionist-handles-existing-customer'],
  }),
  makeGuide({
    slug: 'handle-cancellations-and-no-shows-tradie', number: 75, category: 'Bookings & calendars',
    title: 'How Should Tradies Handle Cancellations and No-Shows?',
    description: 'A practical phone and message process for cancellations, access failures and missed appointments without creating a customer argument.',
    directAnswer: 'Give customers an easy way to cancel or change, record the reason and notice period, notify the diary owner promptly and apply any fee only under a clear pre-agreed policy. Treat a no-show as a human review event: confirm the facts and customer history before charging, rebooking or declining future work.',
    heroImage: '/blog/75-tradie-cancellations-no-shows.webp', heroAlt: 'Australian air-conditioning technician waiting outside a locked property and checking the appointment record',
    keyPoints: ['Easy cancellation protects the day better than silence.', 'Fees require clear prior disclosure and human review.', 'Access failures should be recorded with the original job.'],
    sections: [
      { heading: 'Make changing the booking easy', paragraphs: ['Put the reply or call method in the confirmation. Customers are more likely to tell you early when they can use a simple, recognised channel.'] },
      { heading: 'Record the operational facts', bullets: ['Scheduled window', 'Time the customer contacted the business', 'Reason supplied', 'Whether a technician had departed or arrived', 'Access attempts', 'Requested replacement time'] },
      { heading: 'Keep fee decisions human', paragraphs: ['The assistant can repeat an approved policy but should not argue, waive or apply a fee. A person considers the agreement, evidence and customer relationship.'], callout: { label: 'NO AUTOMATED DISPUTE', text: 'Policy information can be repeated; a contested fee belongs with a person.' } },
      { heading: 'Use no-show data to improve the process', paragraphs: ['Look for weak confirmations, unclear arrival windows, property-manager hand-offs or long lead times. The aim is not only to charge; it is to prevent wasted travel.'] },
      { heading: 'Close the loop', paragraphs: ['Update the job status, free the slot when appropriate, send the final outcome and make the next owner visible. Do not leave cancelled work in the active diary.'] },
    ],
    example: { title: 'A locked rental property', text: 'The technician arrives but the tenant cannot be reached. The event, call attempt and property-manager contact stay on the job. The office decides whether to rebook or apply the disclosed access policy; the AI does not make the dispute decision.' },
    productVisual: 'dashboard', productCaption: 'The job record keeps appointment, access and customer communication evidence together for a fair human decision.',
    faqs: [{ question: 'Can an AI charge a cancellation fee?', answer: 'It should not make that decision. It may repeat the business’s disclosed policy and route the case.' }, { question: 'Can customers cancel by SMS?', answer: 'Yes, when the number and workflow are configured to receive and attach the reply.' }, { question: 'Should every no-show block the customer?', answer: 'No. Review the facts and history rather than automating a permanent decision.' }],
    sources: [sources.acccClaims], related: ['ai-receptionist-handle-rescheduling', 'appointment-windows-for-trade-business', 'how-ai-receptionist-handles-existing-customer'],
  }),
  makeGuide({
    slug: 'allow-travel-time-in-tradie-bookings', number: 76, category: 'Bookings & calendars',
    title: 'How Do Tradies Allow for Travel Time When Booking Jobs?',
    description: 'A simple territory, buffer and job-duration method that stops a full calendar becoming an impossible run sheet.',
    directAnswer: 'Group work into service areas, estimate duration by job type, add realistic travel and parking buffers, and protect time for urgent work and overruns. A calendar gap is not automatically a usable appointment if the technician, territory, skill or travel path does not fit.',
    heroImage: '/blog/76-tradie-travel-time-bookings.webp', heroAlt: 'Australian plumber planning a Gold Coast service route beside a work ute and map',
    keyPoints: ['An empty calendar gap may still be unusable.', 'Territory and job duration belong in the booking rule.', 'Review actual travel instead of relying on optimistic guesses.'],
    sections: [
      { heading: 'Create practical service zones', paragraphs: ['Use the areas the team already understands: northern run, central run, southern run or another stable territory. Do not build dozens of tiny rules before the actual call volume requires them.'] },
      { heading: 'Assign a starting duration by job type', paragraphs: ['A quote visit, maintenance service and uncertain breakdown need different starting allowances. The office can correct them after reviewing real completed work.'] },
      { heading: 'Add the invisible time', bullets: ['Traffic and parking', 'Site sign-in', 'Material collection', 'Customer explanation', 'Job notes and payment', 'Buffer for the earlier job'] },
      { heading: 'Protect the day from false density', paragraphs: ['Six one-hour gaps do not necessarily hold six jobs. A booking rule should consider who is travelling from where and whether the next work belongs in that run.'] },
      { heading: 'Measure and adjust fortnightly', paragraphs: ['Compare planned and actual arrival, completion and travel times. Change one job type or zone at a time so the team can see whether the schedule improves.'], callout: { label: 'REAL CAPACITY', text: 'Book the route the technician can drive, not the empty squares a calendar can display.' } },
    ],
    example: { title: 'A Gold Coast north–south clash', text: 'A two-hour slot is open, but the technician would need to cross the city between jobs. The system treats it as unavailable for that territory and captures a booking request instead of offering a time the run cannot keep.' },
    productVisual: 'rules', productCaption: 'Territory and ownership rules should be explicit before they influence any customer-facing availability.',
    faqs: [{ question: 'Can routing use suburbs?', answer: 'Yes, when the business has supplied a stable suburb-to-zone rule and a boundary fallback.' }, { question: 'How much buffer should we add?', answer: 'Start from recent real jobs and adjust by job type and area.' }, { question: 'Can the AI see live traffic?', answer: 'Do not assume that. A live travel-data feature would need to be explicitly connected and tested.' }],
    related: ['appointment-windows-for-trade-business', 'prevent-double-bookings-with-ai-receptionist', 'route-different-calls-to-different-staff'],
  }),
  makeGuide({
    slug: 'ai-receptionist-recurring-maintenance-bookings', number: 77, category: 'Bookings & calendars',
    title: 'Can an AI Receptionist Help with Recurring Maintenance?',
    description: 'How to capture, remind and route repeat service work without pretending a future maintenance engine is already live.',
    directAnswer: 'Yes. It can capture recurring-maintenance enquiries, identify the asset or property, record the preferred interval and route the job to the maintenance owner. Automated future reminders and recurring bookings require a connected, tested workflow. TradieRelay’s founding scope should first prove missed-call recovery and quote follow-up before adding that automation.',
    heroImage: '/blog/77-recurring-maintenance-bookings.webp', heroAlt: 'Australian HVAC technician reviewing a recurring maintenance schedule beside commercial equipment',
    keyPoints: ['Recurring intent can be captured today.', 'Future reminders need a source date, owner and opt-out process.', 'Add recurring automation only after the core call flow works.'],
    sections: [
      { heading: 'Capture the maintenance unit', paragraphs: ['Record the site, asset or service, responsible contact, last service if known, preferred interval and any contract or access details. The record needs enough identity to avoid reminding the wrong person about the wrong equipment.'] },
      { heading: 'Choose who owns the future action', paragraphs: ['A reminder without a maintenance owner creates another queue. Decide whether the office, technician, account manager or automated workflow prepares and approves the next contact.'] },
      { heading: 'Separate operational and marketing messages', paragraphs: ['A reminder connected to an existing service relationship may be operational or commercial depending on its content and context. Review consent, identification and unsubscribe requirements before automating a campaign.'], callout: { label: 'MESSAGE CONTROL', text: 'A useful service reminder still needs the right recipient, sender identity and stop process.' } },
      { heading: 'Start with a review list', bullets: ['Due date or interval', 'Customer and asset', 'Responsible staff member', 'Contact permission and channel', 'Current product or price', 'Outcome and next due date'] },
      { heading: 'Do not overstate the current feature', paragraphs: ['TradieRelay can capture and route the enquiry now. A fully automated recurring maintenance sequence is a later customer-specific workflow until it is connected, tested and visible in the operator console.'] },
    ],
    example: { title: 'Annual split-system service', text: 'A customer asks to be contacted next winter. The assistant records the unit, contact details and preferred month for the maintenance owner. No automatic reminder is promised until the workflow and consent handling are configured.' },
    productVisual: 'lead', productCaption: 'The current working product captures the maintenance lead and owner; future reminder automation is configured separately.',
    faqs: [{ question: 'Does TradieRelay automatically send annual reminders today?', answer: 'Not as a universal default. It requires a configured customer workflow.' }, { question: 'Can the service date be captured?', answer: 'Yes, as a field on the enquiry or job.' }, { question: 'Do reminder texts need an unsubscribe?', answer: 'Commercial messages generally need compliant consent, sender identification and unsubscribe handling. Obtain advice for the message and relationship.' }],
    sources: [sources.acmaSpam], related: ['best-missed-call-text-back-message-tradies', 'how-ai-receptionist-handles-existing-customer', 'what-ai-receptionist-pricing-should-include'],
  }),
  makeGuide({
    slug: 'after-hours-booking-requests-for-tradies', number: 78, category: 'Bookings & calendars',
    title: 'Should an AI Receptionist Book Jobs After Hours?',
    description: 'When to capture a request, when direct booking is safe and how to set expectations when nobody is watching the diary.',
    directAnswer: 'After hours, capturing a preferred time and promising review is usually safer than direct booking. Direct booking can work for tightly defined routine jobs with live availability and tested rules, but urgent, uncertain or complex work should create an alert or morning-review task rather than an unattended promise.',
    heroImage: '/blog/78-after-hours-booking-request.webp', heroAlt: 'Australian homeowner making an evening trade booking request from a kitchen table',
    keyPoints: ['After-hours customers need a clear review expectation.', 'Routine work and urgent work should not share one booking rule.', 'Direct booking needs the same controls at night as during the day.'],
    sections: [
      { heading: 'Tell the caller what “after hours” changes', paragraphs: ['State when routine requests will be reviewed and how approved urgent indicators are handled. Do not imply that a person is currently monitoring every call unless that is true.'] },
      { heading: 'Use booking requests as the default', paragraphs: ['Capture the desired day or window and place it in the morning queue. The customer gains progress without the business giving up control of tomorrow’s run.'] },
      { heading: 'Limit any direct-booking lane', bullets: ['One repeatable job type', 'Known duration', 'Current connected calendar', 'No diagnosis or site uncertainty', 'Clear territory', 'Working cancellation and fallback path'] },
      { heading: 'Handle urgent indicators separately', paragraphs: ['An urgent rule may alert the on-call person. It should not quietly insert a job into tomorrow’s diary or promise immediate attendance.'] },
      { heading: 'Review the morning hand-off', paragraphs: ['The first person starting work should see every after-hours request, urgent alert and failed or incomplete call. A hidden overnight queue defeats the service.'], callout: { label: 'MORNING OWNER', text: 'Name the person who clears the after-hours queue before the day gets busy.' } },
    ],
    example: { title: 'A 9 pm hot-water enquiry', text: 'The assistant captures the customer, unit details, suburb and preferred time, explains that the request will be reviewed in the morning and creates a visible job. No attendance or calendar time is promised.' },
    productVisual: 'dashboard', productCaption: 'The dashboard gives the morning owner one place to clear overnight requests and urgent review items.',
    faqs: [{ question: 'Can the caller choose tomorrow morning?', answer: 'They can request it. It is confirmed only under the business’s booking rule.' }, { question: 'Will someone be alerted overnight?', answer: 'Only for the approved urgent route and nominated on-call recipient.' }, { question: 'Should every after-hours call be urgent?', answer: 'No. Caller timing and job urgency are different things.' }],
    sources: [sources.aiStandard], related: ['how-tradies-handle-after-hours-calls', 'busy-no-answer-after-hours-which-call-rule', 'can-ai-receptionist-book-jobs-for-tradies'],
  }),
  makeGuide({
    slug: 'urgent-versus-routine-trade-booking', number: 79, category: 'Bookings & calendars',
    title: 'How Should Tradies Separate Urgent and Routine Bookings?',
    description: 'A routing and diary method that keeps urgent reports visible without letting every caller jump the queue.',
    directAnswer: 'Define observable urgency indicators for each trade, capture the caller’s words, alert a qualified person and let that person decide whether to interrupt the schedule. Routine work follows the normal request or booking path. The assistant should not diagnose urgency or move existing customers automatically.',
    heroImage: '/blog/79-urgent-routine-bookings.webp', heroAlt: 'Australian plumbing coordinator comparing an urgent leak alert with routine service bookings',
    keyPoints: ['Urgency is defined before the call, not improvised during it.', 'An urgent alert triggers judgment; it does not guarantee attendance.', 'Routine customers should not be displaced automatically.'],
    sections: [
      { heading: 'Write observable indicators', paragraphs: ['Use conditions callers can report and the business can test. Avoid broad labels such as “sounds serious”. Each trade needs its own wording and emergency boundary.'] },
      { heading: 'Capture the caller’s requested outcome', paragraphs: ['Record whether they want immediate help, a callback, advice about the business process or the next available routine time. Their preference informs the decision but does not control the schedule.'] },
      { heading: 'Alert a person with enough context', bullets: ['Caller and address', 'What was reported', 'Approved indicator matched', 'Photos or evidence', 'Current callback details', 'Existing booking if any'] },
      { heading: 'Let the qualified person decide the disruption', paragraphs: ['The on-call or service owner decides whether to call, attend, refer or keep the routine schedule. The system must not bump another customer on its own.'] },
      { heading: 'Audit false positives and misses', paragraphs: ['Review urgent labels against the final human outcome. Adjust the wording carefully so the route stays sensitive without making the whole day urgent.'], callout: { label: 'ROUTING, NOT DIAGNOSIS', text: 'The urgent lane gets faster human attention; it does not certify the fault.' } },
    ],
    example: { title: 'An active leak versus a dripping tap', text: 'Both callers want today. The active-leak report matches the plumber’s approved urgent indicators and alerts the on-call person. The dripping tap becomes a routine booking request. A plumber decides both outcomes.' },
    productVisual: 'alert', productCaption: 'The alert explains why the reported call entered the urgent review lane without creating an attendance promise.',
    faqs: [{ question: 'Can a caller demand the urgent lane?', answer: 'The system records their concern and applies the approved indicators; a qualified person decides the response.' }, { question: 'Should urgent work be booked directly?', answer: 'Usually it should alert a person first because diagnosis, travel and current workload matter.' }, { question: 'What happens to routine bookings?', answer: 'They remain intact unless a person deliberately changes the schedule and communicates with the customer.' }],
    sources: [sources.aiStandard], related: ['urgent-jobs-vs-emergency-jobs', 'ai-receptionist-transfer-urgent-calls', 'appointment-windows-for-trade-business'],
  }),
  makeGuide({
    slug: 'connect-calendar-to-ai-receptionist-safely', number: 80, category: 'Bookings & calendars',
    title: 'How Do You Connect a Calendar to an AI Receptionist Safely?',
    description: 'A staged checklist for permissions, availability, write controls, audit records, fallbacks and go-live testing.',
    directAnswer: 'Use a dedicated least-privilege connection, decide which calendar is authoritative, limit the assistant to the minimum read or write actions, define valid slots, log changes, and fall back to a booking request on any error. Test creation, clash, reschedule, cancellation, expiry and disconnection before allowing customer-facing confirmation.',
    heroImage: '/blog/80-connect-calendar-ai-safely.webp', heroAlt: 'Australian trade business owner and office coordinator reviewing calendar connection permissions',
    keyPoints: ['Give the integration only the access it needs.', 'A booking must be traceable to the call and customer.', 'Disconnect and failure paths are part of the launch test.'],
    sections: [
      { heading: 'Choose the calendar owner', paragraphs: ['Decide which system staff must update and who resolves conflicts. A connection cannot repair a team that treats three diaries as equally current.'] },
      { heading: 'Limit access and scope', paragraphs: ['Use a dedicated connection where possible. Restrict it to the relevant calendar, event fields and actions. Do not grant broad mailbox or file access merely because it is convenient.'] },
      { heading: 'Define valid booking behaviour', bullets: ['Allowed job types', 'Working hours and blackout periods', 'Duration and buffer', 'Technician skill and territory', 'Required customer fields', 'Confirmation and cancellation wording'] },
      { heading: 'Keep an audit trail', paragraphs: ['Record which call or user created, moved or cancelled the event, the old and new values and whether the customer was notified. That makes correction possible when a sync behaves unexpectedly.'] },
      { heading: 'Test failure before launch', paragraphs: ['Revoke the connection, create a clash and simulate a timeout. The caller should hear that the time is requested and a person will confirm.'], callout: { label: 'GO-LIVE GATE', text: 'Calendar unavailable must produce a reviewable request—not a booking claim.' } },
    ],
    example: { title: 'A limited service calendar', text: 'The business connects only its service calendar and permits the booking workflow to view free/busy and create approved service events. Project quotes remain human-scheduled. A revoked connection switches the caller to a booking request.' },
    productVisual: 'rules', productCaption: 'TradieRelay’s visible account rules define when a connected feature may act and what happens when it cannot.',
    faqs: [{ question: 'Does TradieRelay need access to my email?', answer: 'A calendar integration should request only the permissions needed for the selected calendar function. Confirm the exact provider permissions before connecting.' }, { question: 'Can staff still edit bookings?', answer: 'Yes, but the source of truth and notification process must keep changes consistent.' }, { question: 'Is calendar integration included in every plan?', answer: 'Do not assume it. Confirm the current plan scope, provider and setup requirements in writing.' }],
    sources: [sources.oaicApp11, sources.aiGuardrails], related: ['can-ai-receptionist-book-jobs-for-tradies', 'prevent-double-bookings-with-ai-receptionist', 'test-ai-receptionist-before-going-live'],
  }),
];
