import { makeGuide, sources } from './shared';

export const customerCommunicationGuides = [
  makeGuide({
    slug: 'customer-confirmation-after-missed-trade-call', number: 81, category: 'Customer communication',
    title: 'What Confirmation Should a Customer Receive After a Missed Trade Call?',
    description: 'A plain-English confirmation that reassures the customer, repeats the next step and avoids creating a false booking.',
    directAnswer: 'The customer should receive the business name, a short reference to their enquiry, the actual next step, the expected review or callback window, and a way to correct details or opt out where required. The message must say “requested” when a person still needs to approve the job and “booked” only when a time is confirmed.',
    heroImage: '/blog/81-customer-missed-call-confirmation.webp', heroAlt: 'Australian homeowner reading a clear trade enquiry confirmation message on a phone',
    keyPoints: ['Name the business so the message is trusted.', 'Repeat the real next step, not a vague thank-you.', 'Never turn a captured enquiry into a booking claim.'],
    sections: [
      { heading: 'Reassure the customer that the call went somewhere', paragraphs: ['A short confirmation closes the anxiety created by a missed call. It should make the business recognisable and show that the enquiry has been captured under the correct customer and property.'] },
      { heading: 'State the exact status', bullets: ['Details received', 'Photo requested', 'Callback requested', 'Quote ready to review', 'Time requested', 'Time confirmed'] },
      { heading: 'Set a realistic expectation', paragraphs: ['Use a review window the business can keep. “We will review this tomorrow morning” is better than “ASAP” when nobody knows what that means.'] },
      { heading: 'Give a correction path', paragraphs: ['Tell the customer how to reply if the address, number, photo or timing is wrong. Corrections should attach to the original enquiry instead of creating another loose message.'] },
      { heading: 'Keep commercial messaging separate', paragraphs: ['An operational confirmation should not be padded with promotions. If the business sends commercial content, consent, sender identification and unsubscribe rules may apply.'], callout: { label: 'USEFUL MESSAGE', text: 'Business + enquiry + true status + next step + correction path.' } },
    ],
    example: { title: 'A useful missed-call text', text: '“GC Plumbing: We’ve received your enquiry about the leak in Robina. Noah will review it this morning and call the number ending 412. Reply here if the address or details are wrong.” The wording confirms capture, not attendance.' },
    productVisual: 'lead', productCaption: 'The customer message and the job record should carry the same status so the tradie sees exactly what was promised.',
    faqs: [{ question: 'Should the message say the job is booked?', answer: 'Only after a valid confirmation. Otherwise use received, requested or awaiting review.' }, { question: 'Should it include the full address?', answer: 'Use only the information needed and consider privacy if a phone may be shared.' }, { question: 'Can customers reply?', answer: 'Yes, when two-way messaging is enabled and replies are attached to the enquiry.' }],
    sources: [sources.acmaSpam, sources.oaicApp5], related: ['what-happens-after-tradie-misses-call', 'best-missed-call-text-back-message-tradies', 'how-does-an-ai-receptionist-handle-a-tradie-call'],
  }),
  makeGuide({
    slug: 'how-ai-receptionist-asks-customer-for-photos', number: 82, category: 'Customer communication',
    title: 'How Does an AI Receptionist Ask a Customer for Photos?',
    description: 'What the caller hears, what arrives by text and how the photo lands on the correct TradieRelay job.',
    directAnswer: 'During the call, the assistant explains that photos may help the tradie review the job and asks permission to send a secure upload link. The text names the business and describes the useful, safe views. The customer uploads from their phone, and the images attach to the same job tile in the TradieRelay dashboard.',
    heroImage: '/blog/82-ai-asks-customer-for-photos.webp', heroAlt: 'Australian homeowner receiving a secure trade job photo request on a smartphone',
    keyPoints: ['The caller is told why the photos help.', 'The request never asks the customer to take a safety risk.', 'Uploaded images appear on the same dashboard job.'],
    sections: [
      { heading: 'Explain the purpose on the call', paragraphs: ['Use a simple line: the business can send a secure link so the tradie can see the area before calling back. Do not imply that a photo guarantees a quote or replaces an inspection.'] },
      { heading: 'Send a recognisable request', paragraphs: ['The text should name the trade business, reference the enquiry and provide the secure link. Customers are less likely to trust a bare link from an unknown number.'] },
      { heading: 'Ask for only useful and safe views', bullets: ['One wide photo for context', 'One close photo of the visible issue', 'Model label when safely reachable', 'Ground-level access view', 'No ladders, covers, live equipment or unsafe areas'] },
      { heading: 'Attach, do not scatter', paragraphs: ['The upload token links the images to the correct job. The tradie sees them in the job detail rather than searching the phone gallery or a personal message thread.'] },
      { heading: 'Let the tradie interpret the evidence', paragraphs: ['The system stores and displays the images. A qualified person decides what they mean and whether more information or an inspection is required.'], callout: { label: 'CURRENT WORKING FLOW', text: 'Call explains the request → SMS link → customer upload → photos appear on the dashboard job.' } },
    ],
    example: { title: 'Sarah’s fence photos', text: 'Sarah says two fence panels blew down. The assistant explains that photos will help and sends a secure link. Sarah uploads the damaged panels—not a photo of herself taking them. The images appear on Sarah’s job tile for the tradie to review.' },
    productVisual: 'photo-request', productCaption: 'This is the working customer upload screen. Up to six selected images can attach to the same fictional demo job.',
    faqs: [{ question: 'Where do the photos appear?', answer: 'On the matching job detail in the tradie dashboard.' }, { question: 'Does the customer need an account?', answer: 'No. The secure job-specific link is designed for direct mobile upload.' }, { question: 'Can a photo produce an automatic diagnosis?', answer: 'No. The tradie reviews the evidence.' }],
    sources: [sources.oaicApp11], related: ['customer-photos-help-qualify-trade-job', 'what-is-an-ai-receptionist-for-tradies', 'customer-confirmation-after-missed-trade-call'],
  }),
  makeGuide({
    slug: 'what-job-photos-should-tradies-request', number: 83, category: 'Customer communication',
    title: 'What Job Photos Should Tradies Ask Customers to Send?',
    description: 'A trade-by-trade photo brief that gets useful evidence without asking customers to climb, open equipment or take risks.',
    directAnswer: 'Ask for one wide context photo, one close photo of the visible issue and an identifying label only when safely accessible. Tailor the request to the trade. Never ask a customer to climb, remove a cover, touch live or damaged equipment, enter a roof space or expose themselves to water, traffic or unstable structures.',
    heroImage: '/blog/83-useful-safe-job-photos.webp', heroAlt: 'Australian homeowner safely photographing a visible plumbing issue from ground level',
    keyPoints: ['Wide plus close usually beats six near-identical photos.', 'The photo brief should match the trade and decision.', 'Safety overrides evidence collection every time.'],
    sections: [
      { heading: 'Start with the decision the photo will support', paragraphs: ['A photo may help confirm the trade, prepare the callback or identify a model. If nobody will use it to make a decision, do not create extra customer work or store unnecessary personal information.'] },
      { heading: 'Use a simple two-view pattern', paragraphs: ['A wide photo explains location and context. A close photo shows the visible issue. Add a label photo only when it is safe and relevant.'] },
      { heading: 'Tailor the prompt by trade', bullets: ['Plumbing: affected fixture and surrounding area', 'HVAC: whole unit and accessible model label', 'Painting: whole surface and close damage', 'Landscaping: wide area and access', 'Carpentry: whole item and damaged joint', 'Roofing: indoor damage and ground-level exterior only'] },
      { heading: 'Avoid privacy surprises', paragraphs: ['Ask customers to keep people, documents, screens, vehicle plates and unrelated parts of the home out of frame where practical. Collect only what the job review needs.'] },
      { heading: 'Make unsafe requests impossible', paragraphs: ['Put the boundary in the message and call script. The customer should never feel they must take a risk to receive service.'], callout: { label: 'PHOTO SAFETY', text: 'If the useful angle requires climbing, opening or touching, leave it for the tradie.' } },
    ],
    example: { title: 'A useful air-conditioning upload', text: 'The customer sends one photo of the full indoor unit and one clear photo of the accessible rating label. They are not asked to remove a cover or reach the outdoor unit above ground level.' },
    productVisual: 'photo-request', productCaption: 'The upload experience can show a short, trade-specific request so customers know what is useful and what not to do.',
    table: { headers: ['Useful', 'Avoid'], rows: [['Wide context view', 'Six identical close-ups'], ['Visible issue', 'Removing covers'], ['Accessible model label', 'Climbing for a label'], ['Ground-level access', 'Roof or ladder photos']] },
    faqs: [{ question: 'How many photos can the working upload accept?', answer: 'The current TradieRelay demo accepts up to six images.' }, { question: 'Should the customer include themselves?', answer: 'No. Ask for the job evidence, not a staged photo of the person taking it.' }, { question: 'Are customer photos a final scope?', answer: 'No. They support review and may still require inspection.' }],
    sources: [sources.oaicApp11], related: ['how-ai-receptionist-asks-customer-for-photos', 'customer-photos-help-qualify-trade-job', 'how-long-keep-call-recordings-customer-photos'],
  }),
  makeGuide({
    slug: 'how-ai-receptionist-handles-existing-customer', number: 84, category: 'Customer communication',
    title: 'How Should an AI Receptionist Handle Existing Customers?',
    description: 'A call flow for booking changes, job questions, access, invoices and service issues that does not treat every call as a new lead.',
    directAnswer: 'First identify that the caller has an existing job or relationship, then capture the address, job reference, reason for calling and requested outcome. Route booking changes, access, invoice questions, technical concerns and complaints to their proper owner. Do not force an existing customer through new-lead qualification or promise a resolution the responsible person has not approved.',
    heroImage: '/blog/84-existing-customer-call.webp', heroAlt: 'Australian trade office coordinator helping an existing customer by phone while viewing the job record',
    keyPoints: ['Identify the existing job before asking new-lead questions.', 'Route by issue owner, not only by trade.', 'Keep the new message attached to the existing work.'],
    sections: [
      { heading: 'Ask whether this is about existing work', paragraphs: ['A simple early question prevents the customer from repeating their suburb, job type and sales information. Use phone, address, reference or scheduled date to find the right record.'] },
      { heading: 'Capture the reason for contact', bullets: ['Access or site contact', 'Arrival or booking change', 'Scope or variation question', 'Invoice or payment', 'Workmanship concern', 'Maintenance or new work'] },
      { heading: 'Route to the person who can resolve it', paragraphs: ['The estimator may own a quote question, the office a booking change, the technician a site detail and the owner a complaint. One generic lead notification delays customers who already bought.'] },
      { heading: 'Avoid duplicate jobs', paragraphs: ['Attach the message and any evidence to the original enquiry or job where possible. If the match is uncertain, put it in human review rather than merging the wrong customer records.'] },
      { heading: 'Set a real response expectation', paragraphs: ['Tell the customer who will review the issue and when. Do not use sales-style urgency or pretend the assistant can settle a dispute.'], callout: { label: 'CUSTOMER CONTINUITY', text: 'The caller should feel recognised, not sent back to the start of the sales funnel.' } },
    ],
    example: { title: 'A gate code changes before tomorrow’s job', text: 'The caller identifies the address and scheduled date, supplies the new gate code and asks for confirmation. TradieRelay attaches the note to the existing job and alerts the diary owner instead of creating a second sales lead.' },
    productVisual: 'dashboard', productCaption: 'The job view keeps new customer communication beside the existing status and history.',
    faqs: [{ question: 'Can the assistant look up every customer automatically?', answer: 'Only where the account data and matching rules are connected. Uncertain matches need human review.' }, { question: 'Can it answer invoice questions?', answer: 'It can capture and route them or repeat approved factual information. Disputes and adjustments remain human.' }, { question: 'What if the customer also wants new work?', answer: 'Record the existing issue and new enquiry as linked but separately owned actions.' }],
    sources: [sources.aiStandard, sources.oaicApp11], related: ['ai-receptionist-setup-checklist-australian-tradies', 'ai-receptionist-handle-rescheduling', 'what-happens-when-ai-does-not-know-answer'],
  }),
  makeGuide({
    slug: 'how-ai-receptionist-handles-customer-complaints', number: 85, category: 'Customer communication',
    title: 'Should an AI Receptionist Handle Customer Complaints?',
    description: 'Where AI can help capture a complaint and where it must hand the conversation to a responsible person.',
    directAnswer: 'An AI receptionist can acknowledge the concern, capture the customer, job, issue, impact and requested contact, then alert the complaint owner. It should not debate fault, admit liability, promise compensation, minimise emotion or trap a caller who asks for a person. Complaints need a fast, visible human hand-off.',
    heroImage: '/blog/85-ai-customer-complaint-handoff.webp', heroAlt: 'Australian trade business owner returning a concerned customer call from a quiet office',
    keyPoints: ['Acknowledge and capture—do not argue or adjudicate.', 'High-emotion or high-impact complaints move to a person quickly.', 'Record the promise and owner so the customer is not lost again.'],
    sections: [
      { heading: 'Recognise the complaint lane early', paragraphs: ['If the caller mentions poor work, damage, missed attendance, a disputed charge or repeated failed contact, stop normal sales qualification. Ask what happened and what contact they need.'] },
      { heading: 'Use calm, neutral wording', paragraphs: ['Acknowledge that the customer has a concern without making a legal or technical conclusion. Avoid scripts that sound cheerful, defensive or designed to make the complaint disappear.'] },
      { heading: 'Capture the minimum useful record', bullets: ['Customer and job', 'What they say happened', 'When it happened', 'Immediate impact', 'Evidence offered', 'Requested contact and best time'] },
      { heading: 'Escalate according to impact', paragraphs: ['The business defines which reports require immediate owner contact and which can enter the normal complaint queue. Emergency situations use the approved emergency wording rather than a long complaint interview.'] },
      { heading: 'Close the callback loop', paragraphs: ['Name the responsible person, alert them, record the promised response window and keep later messages on the same case.'], callout: { label: 'HUMAN MOMENT', text: 'AI can stop a complaint becoming a lost voicemail; a person must rebuild the relationship.' } },
    ],
    example: { title: 'A customer says a painter missed the agreed date', text: 'The assistant acknowledges the concern, confirms the quote and property, captures the missed-date claim and requested call, and alerts the owner. It does not blame the crew, promise a refund or defend the schedule.' },
    productVisual: 'alert', productCaption: 'A priority alert can make the complaint visible to the responsible owner without pretending the system resolved it.',
    faqs: [{ question: 'Can the AI apologise?', answer: 'It can use approved acknowledgement wording, but should not admit liability or promise a remedy.' }, { question: 'What if the caller demands a person?', answer: 'Use the approved transfer or prompt human callback path rather than forcing more questions.' }, { question: 'Should complaints enter the sales pipeline?', answer: 'No. They need a distinct owner, status and response expectation.' }],
    sources: [sources.acccClaims, sources.aiGuardrails], related: ['what-happens-when-ai-does-not-know-answer', 'route-different-calls-to-different-staff', 'good-ai-receptionist-greeting-for-tradies'],
  }),
  makeGuide({
    slug: 'recover-abandoned-or-silent-trade-calls', number: 86, category: 'Customer communication',
    title: 'What Should Happen When a Caller Hangs Up or Says Nothing?',
    description: 'A respectful abandoned-call process that preserves useful details without repeatedly chasing an unknown number.',
    directAnswer: 'Preserve only the details actually captured, mark the call incomplete and use a limited callback or text rule based on caller identification, consent and business context. Never invent a job from silence. If the caller cannot be identified or has opted out, leave the record for review rather than starting an automated chase sequence.',
    heroImage: '/blog/86-abandoned-silent-trade-call.webp', heroAlt: 'Australian electrician noticing an incomplete customer call record between jobs',
    keyPoints: ['Incomplete means incomplete—never fill gaps by guessing.', 'A limited recovery attempt should identify the business.', 'Stop when the number, consent or intent is unclear.'],
    sections: [
      { heading: 'Keep the evidence that exists', paragraphs: ['Record the caller number if supplied, time, route, any confirmed name or suburb and where the conversation stopped. Label every missing field rather than generating a polished but false summary.'] },
      { heading: 'Choose when one recovery message is appropriate', paragraphs: ['A recognisable message may help a real customer who was disconnected. It should name the business, explain the missed connection and offer a simple path to continue.'] },
      { heading: 'Do not chase every unknown number', bullets: ['Private or withheld caller with no details', 'Known spam or supplier pattern', 'Immediate hang-up with no business context', 'Number that has opted out', 'Repeated failed delivery', 'Any suspicious or abusive interaction'] },
      { heading: 'Respect commercial-message boundaries', paragraphs: ['A service recovery message and a promotional follow-up are not the same. Do not add an offer simply because the system has a number.'] },
      { heading: 'Make incomplete calls visible but quiet', paragraphs: ['Place them in a low-priority review queue with the reason and any attempted recovery. Do not notify every staff member or create a fake hot lead.'], callout: { label: 'NO INVENTED LEAD', text: 'A phone number and three seconds of silence are not a qualified job.' } },
    ],
    example: { title: 'A call drops after the suburb', text: 'The assistant confirmed “Varsity Lakes” before the connection failed. The job is marked incomplete with no invented name or job type. One business-identified recovery text invites the caller to continue; the customer decides whether to respond.' },
    productVisual: 'dashboard', productCaption: 'Incomplete and message-mode records stay reviewable without being presented as fully qualified leads.',
    faqs: [{ question: 'Should every abandoned call get a text?', answer: 'No. Use a limited rule based on context, identification, consent and delivery.' }, { question: 'Can the AI guess the job from earlier words?', answer: 'It may summarise what was actually said, but must not fill missing facts.' }, { question: 'What if the caller rings again?', answer: 'Where matching is reliable, attach the new interaction to the existing enquiry.' }],
    sources: [sources.acmaSpam, sources.oaicApp11], related: ['what-happens-when-ai-does-not-know-answer', 'what-happens-after-tradie-misses-call', 'customer-confirmation-after-missed-trade-call'],
  }),
  makeGuide({
    slug: 'handle-private-withheld-caller-number-tradie', number: 87, category: 'Customer communication',
    title: 'How Should Tradies Handle Private or Withheld Caller Numbers?',
    description: 'A call flow that collects a usable callback number without rejecting legitimate customers or trusting an unverified number.',
    directAnswer: 'Answer the call normally, explain that the business needs a callback number to continue, ask the caller to say and confirm it, and label it as caller-supplied. If they will not provide one, capture only what the business can act on and explain the limitation. Never treat a withheld number as automatically suspicious or automatically verified.',
    heroImage: '/blog/87-private-withheld-caller.webp', heroAlt: 'Australian plumber taking a private-number customer call while recording callback details',
    keyPoints: ['Private does not mean fake.', 'A spoken callback number must be repeated and confirmed.', 'The business decides what can proceed without a reachable customer.'],
    sections: [
      { heading: 'Keep the greeting normal', paragraphs: ['Do not accuse or challenge the caller because caller ID is unavailable. Explain the practical reason the business needs a number: to return the call, confirm a time or send requested information.'] },
      { heading: 'Confirm the supplied number carefully', paragraphs: ['Repeat it in groups, allow correction and store it as caller-supplied. Do not claim it belongs to the person until the business has reason to trust the match.'] },
      { heading: 'Handle refusal with a business rule', bullets: ['Take a message only', 'Provide a public business email or web form', 'Explain that booking needs a callback number', 'Transfer to a person if available', 'Decline when the business cannot safely act'] },
      { heading: 'Protect customer records from bad matches', paragraphs: ['Do not merge an unverified spoken number with an existing customer solely because the name sounds similar. Send uncertain identity to human review.'] },
      { heading: 'Record the limitation', paragraphs: ['The dashboard should show that the incoming number was withheld and the callback number was manually supplied. That context matters if delivery fails or identity is questioned.'], callout: { label: 'CONFIRM, DON’T ASSUME', text: 'A spoken number can be usable while still being unverified.' } },
    ],
    example: { title: 'A property manager calls from a private line', text: 'The caller supplies an office callback number and work-order reference. The assistant repeats the number, captures the property and labels the contact as caller-supplied. The maintenance coordinator verifies the job before action.' },
    productVisual: 'lead', productCaption: 'The job record can make a withheld incoming number and confirmed callback detail visible to the reviewer.',
    faqs: [{ question: 'Should private callers be blocked?', answer: 'Not automatically. Legitimate customers and organisations may withhold caller ID.' }, { question: 'Can a photo link be sent to the supplied number?', answer: 'Yes, after the number is repeated and confirmed, subject to the business’s message and privacy rules.' }, { question: 'What if the number fails?', answer: 'Show the delivery failure and use the approved alternative rather than repeatedly sending.' }],
    sources: [sources.oaicApp11], related: ['qualify-trade-lead-without-annoying-customer', 'recover-abandoned-or-silent-trade-calls', 'what-happens-when-ai-does-not-know-answer'],
  }),
  makeGuide({
    slug: 'filter-spam-supplier-sales-calls-for-tradies', number: 88, category: 'Customer communication',
    title: 'Can an AI Receptionist Filter Spam, Supplier and Sales Calls?',
    description: 'How to separate customer work from supplier, recruitment and unsolicited sales calls without blocking something important.',
    directAnswer: 'Yes. Ask the caller’s purpose early, use approved categories and route customer jobs, suppliers, recruitment, accounts and sales pitches differently. Obvious unsolicited sales calls can receive a polite decline, but uncertain calls should be captured for review. The system should not rely only on caller ID or make permanent blacklists from one interaction.',
    heroImage: '/blog/88-filter-spam-supplier-calls.webp', heroAlt: 'Australian trade office manager sorting supplier customer and sales calls on a dashboard',
    keyPoints: ['Call intent is more dependable than caller ID alone.', 'Suppliers and accounts need a real route, not the sales bin.', 'Uncertain calls remain reviewable.'],
    sections: [
      { heading: 'Ask the purpose before the full job flow', paragraphs: ['A short intent question can identify a new customer, existing job, supplier, account, employment enquiry or unsolicited sales call. That stops non-customer callers being asked for a job suburb and photo.'] },
      { heading: 'Create useful non-lead routes', bullets: ['Supplier or delivery', 'Accounts and invoice', 'Subcontractor or employment', 'Existing customer', 'New job', 'Sales or media'] },
      { heading: 'Decline politely, not aggressively', paragraphs: ['An unsolicited sales caller can hear that the business is not taking supplier pitches by phone and be directed to an approved email if one exists. Avoid arguments or personal commentary.'] },
      { heading: 'Keep uncertain intent visible', paragraphs: ['A terse caller may still be a real commercial customer or property manager. Capture the organisation, purpose and callback rather than permanently labelling the number as spam.'] },
      { heading: 'Review false positives', paragraphs: ['Check which calls were filtered and whether any real opportunity or supplier issue was delayed. Adjust the intent wording before expanding an exclusion.'], callout: { label: 'FILTER, DON’T GUESS', text: 'Route from what the caller says and the business rule—not from prejudice about a number.' } },
    ],
    example: { title: 'A wholesaler calls about a delayed delivery', text: 'The caller says they are from the wholesaler and provides the purchase reference. The assistant routes the message to the materials owner rather than treating it as a new lead or generic sales pitch.' },
    productVisual: 'rules', productCaption: 'Intent and routing rules give each useful non-customer call a named destination and fallback.',
    faqs: [{ question: 'Can the AI block a known nuisance number?', answer: 'A provider may support blocking, but permanent changes should be deliberate, reviewable and reversible.' }, { question: 'Where should recruitment calls go?', answer: 'Use the business’s chosen careers or office route rather than the customer lead queue.' }, { question: 'Can suppliers leave messages?', answer: 'Yes. Capture the organisation, reference, purpose and callback for the correct owner.' }],
    related: ['qualify-trade-lead-without-annoying-customer', 'route-different-calls-to-different-staff', 'how-tradie-set-call-answering-rules'],
  }),
  makeGuide({
    slug: 'sms-rules-for-tradie-follow-up-australia', number: 89, category: 'Customer communication',
    title: 'What SMS Rules Matter for Tradie Follow-Up in Australia?',
    description: 'The practical difference between operational updates and commercial messages, with consent, sender identity and unsubscribe basics.',
    directAnswer: 'Commercial SMS generally needs consent, clear sender identification and a working unsubscribe method, and the business remains responsible when a provider sends on its behalf. Operational messages should stay limited to the enquiry or service purpose. Classifying a message can depend on its content and context, so seek advice for the actual campaign and keep evidence of consent and opt-outs.',
    heroImage: '/blog/89-tradie-sms-rules-australia.webp', heroAlt: 'Australian trade business owner reviewing compliant customer SMS wording on a phone',
    keyPoints: ['The business cannot outsource spam-law responsibility.', 'Do not turn an operational update into a hidden promotion.', 'STOP and other opt-outs must be captured and honoured.'],
    sections: [
      { heading: 'Separate service from promotion', paragraphs: ['A message confirming an active enquiry has a different purpose from a seasonal offer. Adding promotional content may change how the message is treated, even if it started as an operational update.'] },
      { heading: 'Know the commercial-message basics', bullets: ['Consent', 'Accurate sender identification', 'A clear unsubscribe method', 'Promptly honouring the opt-out', 'Evidence of consent and processing', 'Oversight of the sending provider'] },
      { heading: 'Make the sender recognisable', paragraphs: ['Name the trade business in the message. A customer who called “Coastal Air” should not receive a mysterious link from a technology brand with no explanation.'] },
      { heading: 'Stop follow-up when the event closes', paragraphs: ['Quote acceptance, customer decline, job closure, expiry and STOP should end the relevant automated sequence. Do not keep sending because a timer was already scheduled.'] },
      { heading: 'Review the exact message', paragraphs: ['This guide is practical information, not legal advice. The Spam Act applies to the real content, consent and circumstances. Get advice where the classification or campaign is uncertain.'], callout: { label: 'ACMA RULE OF THUMB', text: 'Consent, identify the sender, provide a working unsubscribe, and supervise providers acting for you.' } },
    ],
    example: { title: 'Quote reminder versus winter promotion', text: '“GC Plumbing: your requested quote is ready” relates to an active enquiry. “Book a discounted winter service” is promotional. Combining the two can turn a useful update into a commercial message that needs the full compliance process.' },
    productVisual: 'customer-quote', productCaption: 'TradieRelay quote messages identify the business and link to a specific customer action rather than sending an unexplained promotion.',
    faqs: [{ question: 'Does replying STOP end quote follow-up?', answer: 'The configured workflow should record the opt-out and stop relevant commercial messages. Review the exact legal effect for the communication.' }, { question: 'Can a provider manage unsubscribe?', answer: 'Yes, but the sending business remains responsible for oversight.' }, { question: 'How quickly must unsubscribe be actioned?', answer: 'ACMA guidance says commercial unsubscribe requests must generally be actioned within five working days, among other requirements.' }],
    sources: [sources.acmaSpam], related: ['best-missed-call-text-back-message-tradies', 'when-automated-quote-follow-up-stop', 'customer-confirmation-after-missed-trade-call'],
  }),
  makeGuide({
    slug: 'write-clear-customer-updates-for-trade-jobs', number: 90, category: 'Customer communication',
    title: 'How Do You Write Clear Customer Updates for Trade Jobs?',
    description: 'A six-part message pattern for confirmations, delays, quote updates and next steps that customers can understand at a glance.',
    directAnswer: 'Use the business name, identify the job, state what changed, give the true current status, explain the next action and provide a reply path. Keep one message to one purpose. Avoid jargon, vague “ASAP” promises, internal status codes and wording that makes a request sound confirmed.',
    heroImage: '/blog/90-clear-customer-job-updates.webp', heroAlt: 'Australian homeowner reading a concise trade job update while a technician prepares nearby',
    keyPoints: ['One message should answer one customer question.', 'Use the same status the team sees.', 'A clear next action beats a long explanation.'],
    sections: [
      { heading: 'Use the six-part pattern', bullets: ['Business name', 'Job or property reference', 'What changed', 'Current status', 'Who does what next', 'How to reply or get help'] },
      { heading: 'Make status words earn trust', paragraphs: ['Received, reviewing, waiting on photos, quote sent, time requested and booked mean different things. Use the word that matches the operating record.'] },
      { heading: 'Write for a phone screen', paragraphs: ['Put the action early, use short sentences and remove office jargon. The customer should not need to open three messages to know what is happening.'] },
      { heading: 'Do not hide bad news', paragraphs: ['If the window has changed or the job cannot be taken, say so promptly and respectfully. A vague delay message usually creates another call.'] },
      { heading: 'Keep the team and customer in sync', paragraphs: ['The message should be recorded against the job. If a person changes the promise by phone, update the status so automation does not send an old version later.'], callout: { label: 'MESSAGE TEST', text: 'Can the customer answer: What happened? What happens next? Do I need to do anything?' } },
    ],
    example: { title: 'A useful delay update', text: '“Coastal Electrical: today’s 12–2 pm arrival window for 18 Palm Ave has moved to 2–4 pm because the earlier job ran over. Reply YES if that still works, or call 07… to rearrange.” It names the change and gives control.' },
    productVisual: 'pipeline', productCaption: 'Customer updates should follow the same needs-you, waiting and booked states visible to the trade business.',
    table: { headers: ['Weak', 'Clear'], rows: [['We’ll be there soon', 'Arrival window is 2–4 pm'], ['Your request is processed', 'Your Thursday time is requested'], ['Action required', 'Reply with one wide photo'], ['We’ll update you ASAP', 'Noah will review this by 10 am tomorrow']] },
    faqs: [{ question: 'Should messages use trade jargon?', answer: 'Only if customers understand it. Plain English is safer.' }, { question: 'Should every update include a phone number?', answer: 'Provide a practical reply or contact route appropriate to the message.' }, { question: 'Can templates still feel personal?', answer: 'Yes. Use accurate business, customer, job and next-step details rather than artificial friendliness.' }],
    sources: [sources.acmaSpam], related: ['customer-confirmation-after-missed-trade-call', 'what-should-quote-follow-up-text-say', 'best-missed-call-text-back-message-tradies'],
  }),
];
