import { makeGuide, sources } from './shared';

export const localGrowthGuides = [
  makeGuide({
    slug: 'local-seo-for-tradies-australia', number: 119, category: 'Local growth',
    title: 'What Is Local SEO for Tradies in Australia?',
    description: 'A practical explanation of the website, Google Business Profile and reputation basics that help local customers understand and find a trade business.',
    directAnswer: 'Local SEO is the work of making a trade business’s real services, locations, contact details, proof and availability easy for customers and search engines to understand. Start with an accurate Google Business Profile, a clear crawlable website, useful service and area information, consistent contact details, genuine reviews and working phone handling. There is no guaranteed ranking shortcut.',
    heroImage: '/blog/119-local-seo-for-tradies.webp', heroAlt: 'Australian electrician reviewing local search results and business details on a laptop',
    keyPoints: ['Accurate business facts come before keyword tricks.', 'Useful service information must be readable as text.', 'A ranking is wasted when the phone response fails.'],
    sections: [
      { heading: 'Make the business entity clear', paragraphs: ['Use the real trading name, primary trade category, phone, website, hours and service area consistently. A service-area business should describe where it travels without pretending to have shopfronts in every suburb.'] },
      { heading: 'Build pages around customer decisions', bullets: ['What work you do', 'Where you do it', 'Who it suits', 'What happens after contact', 'Licences or qualifications where relevant', 'Photos, proof and genuine reviews', 'Clear phone or enquiry route'] },
      { heading: 'Use Google Business Profile properly', paragraphs: ['Claim and verify the eligible business, choose the most accurate category, keep hours and phone current, add useful photos and respond to genuine reviews. Do not stuff the name with services or suburbs that are not part of the real business name.'] },
      { heading: 'Help search systems understand the site', paragraphs: ['Use descriptive titles and headings, crawlable text, internal links, a sitemap and accurate LocalBusiness structured data where appropriate. Structured data describes content; it does not guarantee ranking or a rich result.'] },
      { heading: 'Connect visibility to response', paragraphs: ['Track which local enquiries fit, whether they are answered or recovered and what they become. More visibility is not useful when customers reach voicemail with no next step.'], callout: { label: 'LOCAL SEO TEST', text: 'Can a nearby customer quickly understand the service, area, proof and next step—and can the business respond?' } },
    ],
    example: { title: 'A real Gold Coast service area', text: 'A plumber lists the actual Gold Coast suburbs served, explains emergency versus routine call handling, shows real work and keeps the same phone and hours across the website and Business Profile. It does not create a fake office page for every suburb.' },
    productVisual: 'alert', productCaption: 'TradieRelay helps close the local-search loop by turning selected missed calls into owned, reviewable job enquiries.',
    faqs: [{ question: 'Does adding more suburb pages guarantee rankings?', answer: 'No. Thin or duplicative pages made only to manipulate search can be unhelpful. Publish genuinely useful local information.' }, { question: 'Do tradies need a shopfront?', answer: 'No. Eligible service-area businesses can use a Google Business Profile without showing an address customers do not visit.' }, { question: 'How long does local SEO take?', answer: 'There is no fixed timeline or guaranteed result. Accuracy, competition, site quality and real reputation all matter.' }],
    sources: [sources.googleProfile, sources.googleServiceArea, sources.googleHelpful, sources.googleLocalData], related: ['google-business-profile-for-tradies', 'service-area-pages-for-tradie-websites', 'connect-tradie-marketing-to-phone-answering'],
  }),
  makeGuide({
    slug: 'google-business-profile-for-tradies', number: 120, category: 'Local growth',
    title: 'How Should a Tradie Set Up a Google Business Profile?',
    description: 'A straightforward checklist for service-area, category, phone, hours, photos, access and customer reviews.',
    directAnswer: 'Claim and verify the eligible business, use the real business name, choose the most specific primary category, set an accurate service area or customer-facing address, add the correct phone, website and hours, upload real work photos, invite genuine reviews without incentives, and give each manager their own access. Keep it current after roster, phone or service changes.',
    heroImage: '/blog/120-google-business-profile-tradie.webp', heroAlt: 'Australian landscaper updating a verified Google Business Profile with service area and work photos',
    keyPoints: ['Represent the real business, not a keyword version of it.', 'Use a service area when customers do not visit the address.', 'Keep phone, hours and access ownership current.'],
    sections: [
      { heading: 'Use the real business identity', paragraphs: ['Enter the trading name as it appears in the real world. Choose a specific primary category that best describes the main service and add only relevant secondary categories.'] },
      { heading: 'Set location honestly', paragraphs: ['If customers visit a staffed location, use the accurate address. If the business travels to customers and does not serve them at the address, hide the address and use a specific service area under Google’s guidance.'] },
      { heading: 'Complete the customer details', bullets: ['Primary phone', 'Website', 'Normal and special hours', 'Services', 'Business description', 'Service area', 'Real photos and videos'] },
      { heading: 'Control access', paragraphs: ['Invite owners and managers through their own Google Accounts rather than sharing a password. Keep at least one dependable primary owner and remove former staff promptly.'] },
      { heading: 'Maintain the profile as operations change', paragraphs: ['Update holiday hours, phone routes, categories and service area when the real business changes. Test the published phone path from another device.'], callout: { label: 'PROFILE PROMISE', text: 'Every public phone, hour, service and location should match what a customer experiences.' } },
    ],
    example: { title: 'A mobile electrician in Carrara', text: 'The business hides its home address because customers do not visit, lists its actual service area, uses Electrician as the primary category, publishes the existing business number and tests no-answer forwarding after every phone change.' },
    productVisual: 'rules', productCaption: 'TradieRelay’s answer mode and hours should match the public availability and phone expectations shown on the Business Profile.',
    faqs: [{ question: 'Can a home-based tradie hide the address?', answer: 'Google allows eligible service-area businesses to hide an address customers do not visit and list a service area instead.' }, { question: 'Can the business add suburb names to its profile name?', answer: 'Use the real-world business name and follow Google’s representation guidelines rather than adding keywords.' }, { question: 'Should Noah manage the customer’s profile with a shared password?', answer: 'No. Google provides owner and manager roles so each user can have their own access.' }],
    sources: [sources.googleProfile, sources.googleServiceArea], related: ['local-seo-for-tradies-australia', 'get-more-google-reviews-for-tradie-business', 'connect-tradie-marketing-to-phone-answering'],
  }),
  makeGuide({
    slug: 'service-area-pages-for-tradie-websites', number: 121, category: 'Local growth',
    title: 'Should Tradies Create a Website Page for Every Service Area?',
    description: 'When a local page helps customers and when copied suburb pages become thin, repetitive content.',
    directAnswer: 'Create a service-area page only when it provides genuinely useful, distinct information for customers in that area: actual coverage, common work, access or response realities, relevant proof and a clear next step. Do not mass-produce near-identical suburb pages with swapped place names. One strong service-area page may be better than dozens of empty ones.',
    heroImage: '/blog/121-tradie-service-area-pages.webp', heroAlt: 'Australian roofing contractor planning useful website pages for real service areas on a map',
    keyPoints: ['A local page must help a local customer decide.', 'Real experience and proof make pages distinct.', 'Do not claim offices or availability that do not exist.'],
    sections: [
      { heading: 'Start with how the business actually travels', paragraphs: ['Map the areas regularly served, boundary areas and places usually declined. Your website, Business Profile and phone rules should agree.'] },
      { heading: 'Give each page a local reason to exist', bullets: ['Real services available there', 'Travel or booking expectations', 'Common property or access context', 'Relevant completed work with permission', 'Local contact and next step', 'Honest limitations'] },
      { heading: 'Avoid search-engine-first duplication', paragraphs: ['Changing Carrara to Robina in the heading while leaving the page otherwise identical creates little value. Google advises people-first content and warns against scaled pages made primarily to manipulate search.'] },
      { heading: 'Use a hub when detail is thin', paragraphs: ['A single Gold Coast service-area page can list suburbs and explain the shared service. Add individual pages later when real experience, demand and distinct information justify them.'] },
      { heading: 'Connect the page to call handling', paragraphs: ['When an area is promoted, make sure the call rules accept it or clearly explain the limitation. Review out-of-area calls as evidence that the page or ad may be confusing.'], callout: { label: 'PAGE TEST', text: 'Would this page still be useful if the suburb name were removed from the heading?' } },
    ],
    example: { title: 'One useful southern Gold Coast page', text: 'A landscaper explains the southern service run, typical access constraints, project types, recent permitted work and booking process. It does not invent separate offices or copy the same page across twenty suburbs.' },
    productVisual: 'rules', productCaption: 'Published service areas should match the suburb and boundary rules used when customer calls are qualified.',
    faqs: [{ question: 'How many suburb pages should a tradie have?', answer: 'There is no correct number. Publish only pages with distinct customer value and real service coverage.' }, { question: 'Can the same testimonial appear on every page?', answer: 'It may be visible site-wide, but local pages need more than repeated proof and swapped place names.' }, { question: 'Should out-of-area suburbs be listed?', answer: 'Explain boundaries clearly; do not promote an area the business routinely declines.' }],
    sources: [sources.googleHelpful, sources.googleAiSearch, sources.googleServiceArea], related: ['local-seo-for-tradies-australia', 'questions-tradie-service-pages-should-answer', 'use-call-reasons-improve-tradie-marketing'],
  }),
  makeGuide({
    slug: 'get-more-google-reviews-for-tradie-business', number: 122, category: 'Local growth',
    title: 'How Can Tradies Get More Google Reviews?',
    description: 'A compliant, low-friction review request process based on real jobs, genuine experiences and respectful follow-up.',
    directAnswer: 'Ask real customers after a clear service milestone, use Google’s review link or QR code, make the request easy, and respond professionally to positive and negative feedback. Do not buy reviews, offer incentives for them, ask only happy customers in a misleading way, or pressure people to change or remove genuine criticism.',
    heroImage: '/blog/122-get-more-google-reviews.webp', heroAlt: 'Australian homeowner leaving a genuine Google review after a completed trade job',
    keyPoints: ['Ask after a real customer experience.', 'Make the link easy and the choice voluntary.', 'Never reward, manufacture or manipulate reviews.'],
    sections: [
      { heading: 'Choose the right moment', paragraphs: ['Ask after the customer can judge the experience: completion, handover or a resolved service issue. Do not request a five-star rating before the work is finished.'] },
      { heading: 'Use a simple request', paragraphs: ['Name the business, thank the customer and ask for an honest review using the official link. Keep it separate from a disputed invoice or pressure to approve more work.'] },
      { heading: 'Avoid misleading practices', bullets: ['No purchased reviews', 'No staff or family posing as customers', 'No discount for a positive review', 'No pressure to remove genuine criticism', 'No fake competitor reviews', 'No promises the business cannot verify'] },
      { heading: 'Respond like future customers are reading', paragraphs: ['Thank reviewers, keep private details out of public replies and move disputes into an appropriate private process. A calm response can demonstrate how the business handles problems.'] },
      { heading: 'Connect the request to the job status', paragraphs: ['Trigger the request only after the approved milestone and stop if the customer has complained, opted out or the job remains unresolved.'], callout: { label: 'GOOGLE POLICY', text: 'Reviews must reflect genuine experience; incentives for reviews are prohibited by Google.' } },
    ],
    example: { title: 'A simple completion request', text: 'After the paid job is marked complete, the customer receives: “Thanks for choosing Coastal Electrical. If you’d like to share your genuine experience, here is our Google review link.” No rating or reward is requested.' },
    productVisual: 'pipeline', productCaption: 'A reliable completed-job status is the right operational trigger for any future review-request workflow.',
    faqs: [{ question: 'Can a tradie offer a discount for a review?', answer: 'Google says incentives such as free or discounted goods or services in exchange for reviews are prohibited.' }, { question: 'Should negative reviewers be contacted?', answer: 'Respond respectfully and use an appropriate private channel to understand and resolve the issue.' }, { question: 'Does TradieRelay automatically request reviews today?', answer: 'Not as a universal standard feature. A customer-specific workflow would need to be configured and tested before it is offered.' }],
    sources: [sources.googleReviews, sources.acccReviews, sources.acmaSpam], related: ['google-business-profile-for-tradies', 'write-clear-customer-updates-for-trade-jobs', 'ai-receptionist-recurring-maintenance-bookings'],
  }),
  makeGuide({
    slug: 'what-should-tradie-website-include', number: 123, category: 'Local growth',
    title: 'What Should a Tradie Website Include?',
    description: 'The essential pages and proof that help a customer understand fit, trust the business and know what happens after contact.',
    directAnswer: 'A tradie website should clearly state the trade and service area, explain preferred services and exclusions, show genuine proof, provide business and licence information where relevant, answer common customer questions, explain the enquiry process, display clear contact options and work well on mobile. It should not hide the phone behind marketing fluff or claim results it cannot prove.',
    heroImage: '/blog/123-what-tradie-website-needs.webp', heroAlt: 'Australian carpenter reviewing a clear mobile-friendly trade business website',
    keyPoints: ['Answer who, what, where and next step immediately.', 'Use genuine proof and accurate business information.', 'Design for the customer holding a phone on site.'],
    sections: [
      { heading: 'Make the first screen clear', bullets: ['Trade and main service', 'Actual service area', 'Who the service suits', 'Primary phone or enquiry action', 'What happens next', 'Important availability limits'] },
      { heading: 'Explain the work in customer language', paragraphs: ['Use service pages that answer the questions customers ask before calling. Keep technical authority, but avoid expecting the customer to diagnose the problem or know industry terms.'] },
      { heading: 'Show trustworthy proof', paragraphs: ['Use real project photos with permission, genuine reviews, licences or qualifications where relevant, business contact details and a clear about page. Avoid anonymous claims such as “number one” without support.'] },
      { heading: 'Cover privacy and expectations', paragraphs: ['Explain how enquiries and photos are handled, how prices or quotes work, service boundaries and how customers can contact the business about data or complaints.'] },
      { heading: 'Test the phone journey', paragraphs: ['Call the published number during answered, missed and after-hours conditions. The website promise, Business Profile and call flow should tell one consistent story.'], callout: { label: 'MOBILE TEST', text: 'Can a customer understand fit and contact the business with one hand in under a minute?' } },
    ],
    example: { title: 'A useful electrician homepage', text: 'The page says which electrical work is handled, lists the real Gold Coast service area, shows genuine project evidence, explains that missed calls are captured by an automated assistant and gives a clear callback expectation.' },
    productVisual: 'lead', productCaption: 'A clear website promise should produce the same useful job details and next step when the customer calls.',
    faqs: [{ question: 'Does every tradie need online booking?', answer: 'No. A clear phone or enquiry flow may be better when jobs need human assessment.' }, { question: 'Should licence numbers be shown?', answer: 'Follow the requirements for the trade and jurisdiction and present accurate current details.' }, { question: 'How much copy is enough?', answer: 'Enough to answer the customer’s decision without padding to a target word count.' }],
    sources: [sources.googleHelpful, sources.googleAiSearch, sources.acccClaims], related: ['local-seo-for-tradies-australia', 'questions-tradie-service-pages-should-answer', 'should-tradies-show-prices-on-website'],
  }),
  makeGuide({
    slug: 'should-tradies-show-prices-on-website', number: 124, category: 'Local growth',
    title: 'Should Tradies Show Prices on Their Website?',
    description: 'When fixed fees, “from” prices and quoting-process information help—and when a number creates a misleading expectation.',
    directAnswer: 'Show prices when the service and inclusions are standard enough to state a clear total or valid starting condition. For variable work, explain the quoting process, inspection fee and main price drivers instead of inventing a ballpark. Display mandatory taxes and unavoidable fees appropriately for the audience, and keep website, phone and saved product prices consistent.',
    heroImage: '/blog/124-show-trade-prices-website.webp', heroAlt: 'Australian plumber comparing an approved service price with the business website',
    keyPoints: ['A displayed price needs clear scope and conditions.', 'Explain the process when the work cannot be priced remotely.', 'Update every channel from the same approved price source.'],
    sections: [
      { heading: 'Good candidates for a public price', paragraphs: ['A defined call-out, inspection, consultation or repeatable service may be clear enough if inclusions, area, timing and GST treatment are stated.'] },
      { heading: 'Use “from” carefully', paragraphs: ['A starting price needs a genuine lowest available scope and an explanation of what changes it. It should not be a teaser that no normal customer can obtain.'] },
      { heading: 'Explain variable-work pricing', bullets: ['Why inspection is needed', 'What information helps', 'Whether the quote is free or paid', 'How variations are approved', 'When the quote expires', 'What the customer receives'] },
      { heading: 'Keep channels consistent', paragraphs: ['The website, AI receptionist, quote editor and staff should use the same current approved source. If an old webpage conflicts with the app, stop displaying the price until corrected.'] },
      { heading: 'Check Australian price-display obligations', paragraphs: ['The ACCC says businesses must communicate clear and accurate prices and, for consumer displays, generally show the minimum total price including taxes and unavoidable or preselected fees. Obtain advice for the business and audience.'], callout: { label: 'PRICE TRUST', text: 'Clear scope + current amount + real conditions + no hidden unavoidable cost.' } },
    ],
    example: { title: 'Inspection fee with defined inclusions', text: 'The website shows a $165 consumer inspection fee including GST and explains the service area and what the visit includes. Repair work is quoted after assessment. The saved product uses the same approved amount. Illustrative price only.' },
    productVisual: 'products-prices', productCaption: 'The working saved-products screen helps the tradie keep approved website, phone and quote items aligned.',
    faqs: [{ question: 'Can prices be shown plus GST?', answer: 'It depends on whether the display is to consumers or businesses and the context. ACCC guidance generally requires consumer total prices to include taxes and unavoidable fees.' }, { question: 'Should every service have a price?', answer: 'No. Explain the process when scope cannot be responsibly standardised.' }, { question: 'Can the AI repeat a website price?', answer: 'Only when the same current approved item and conditions are configured.' }],
    sources: [sources.acccPrices, sources.acccClaims], related: ['prevent-ai-receptionist-inventing-prices', 'saved-products-prices-speed-up-trade-quotes', 'what-should-tradie-website-include'],
  }),
  makeGuide({
    slug: 'questions-tradie-service-pages-should-answer', number: 125, category: 'Local growth',
    title: 'What Questions Should Every Tradie Service Page Answer?',
    description: 'A customer-first service-page checklist covering fit, evidence, process, timing, price and the phone conversation.',
    directAnswer: 'Answer what the service is, which problems or projects it covers, who it suits, where it is available, what information or photos help, what happens after contact, how timing and quotes work, what is excluded, and how to reach the business. Use the same plain terms customers use on real calls and keep the answers accurate to operations.',
    heroImage: '/blog/125-tradie-service-page-questions.webp', heroAlt: 'Australian painter and customer reviewing a clear service-page question checklist',
    keyPoints: ['Answer the decision before asking for contact.', 'Use customer questions from real enquiries.', 'Keep page and call promises consistent.'],
    sections: [
      { heading: 'Answer the fit questions', bullets: ['What work is included?', 'What is not included?', 'Which properties or customers?', 'Which service area?', 'What minimum or project size?', 'Which licences or specialist limits?'] },
      { heading: 'Explain the evidence', paragraphs: ['Tell customers which safe photos, model details, plans or access information will help and why. Do not ask them to diagnose the problem before calling.'] },
      { heading: 'Explain the next step', paragraphs: ['State whether the first action is a callback, site visit, paid inspection, quote review, booking request or another process. This reduces calls from customers expecting instant pricing or attendance.'] },
      { heading: 'Cover timing and price honestly', paragraphs: ['Explain booking windows, urgent-review boundaries, quote process, known fees and the factors that require inspection. Avoid vague “fastest service” claims.'] },
      { heading: 'Use real call evidence to improve the page', paragraphs: ['Review recurring customer questions and poor-fit calls. Add an answer when it helps a customer decide—not to create another keyword section.'], callout: { label: 'SERVICE PAGE TEST', text: 'After reading, can the right customer explain the service and next step in one sentence?' } },
    ],
    example: { title: 'A useful hot-water service page', text: 'The page explains repair and replacement coverage, actual suburbs, safe unit photos, the callback process, inspection pricing and that diagnosis and final quote follow review. The call flow asks the same core questions.' },
    productVisual: 'photo-request', productCaption: 'A service page can prepare the customer for the exact safe photo request used in the working call flow.',
    faqs: [{ question: 'Should the page answer emergency questions?', answer: 'State the service boundary and appropriate emergency direction without publishing unqualified remote advice.' }, { question: 'Should FAQs copy competitors?', answer: 'No. Use the business’s real customer questions and process.' }, { question: 'How often should pages be reviewed?', answer: 'When services, areas, prices or repeated call questions change, plus a scheduled periodic check.' }],
    sources: [sources.googleHelpful, sources.googleAiSearch], related: ['what-should-tradie-website-include', 'service-area-pages-for-tradie-websites', 'what-job-photos-should-tradies-request'],
  }),
  makeGuide({
    slug: 'answer-engine-optimisation-aeo-for-tradies', number: 126, category: 'Local growth',
    title: 'What Is Answer Engine Optimisation for Tradies?',
    description: 'How clear, sourced, direct answers can help customers and machine-generated search experiences understand a trade business.',
    directAnswer: 'Answer engine optimisation means publishing useful, direct, well-structured answers that search and AI systems can understand and cite when appropriate. For tradies, that means real service expertise, accurate business facts, question-led pages, concise answers followed by detail, clear authorship and sources, descriptive images, internal links and structured data that matches visible content. It is not a guarantee of recommendation.',
    heroImage: '/blog/126-aeo-for-tradies.webp', heroAlt: 'Australian electrician reviewing a direct-answer trade guide on a laptop and phone',
    keyPoints: ['Write for customer decisions first.', 'Put the short answer before the detailed explanation.', 'Use real evidence, sources and accurate structured data.'],
    sections: [
      { heading: 'Start with a real customer question', paragraphs: ['Use questions the business repeatedly hears and can answer from experience. Avoid creating pages for every tiny wording variation solely to occupy search results.'] },
      { heading: 'Use an answer-first structure', bullets: ['Descriptive question title', 'Direct plain-English answer', 'Decision points and boundaries', 'Worked example', 'Checklist or comparison', 'Common follow-up questions', 'Sources where the answer depends on external rules'] },
      { heading: 'Show who and how', paragraphs: ['Make the publisher and product context clear. Demonstrate the process with actual screenshots, labelled demo data and explicit limitations rather than generic claims.'] },
      { heading: 'Use structured data accurately', paragraphs: ['Article, breadcrumb and relevant FAQ data can help systems understand the page. The markup must match visible content and does not guarantee a rich result or AI citation.'] },
      { heading: 'Measure satisfied readers, not only rankings', paragraphs: ['Track useful visits, searches, demo clicks and calls, then review whether the article actually resolves the question. Google recommends helpful, reliable, people-first content and warns against scaled content created to manipulate ranking.'], callout: { label: 'AEO PRINCIPLE', text: 'Give the clearest useful answer you would send a real customer—even if search engines did not exist.' } },
    ],
    example: { title: 'An answer-first call-forwarding guide', text: 'The page begins with what call forwarding does, then explains provider control, setup, failure and tests. It uses a real TradieRelay screen and official carrier sources instead of padding the question with sales copy.' },
    productVisual: 'dashboard', productCaption: 'Product screenshots and precise captions give readers and answer systems evidence of what the software actually does.',
    faqs: [{ question: 'Does FAQ schema guarantee an answer result?', answer: 'No. Structured data helps describe content but does not guarantee display or ranking.' }, { question: 'Should every article be very long?', answer: 'No. Google says there is no preferred word count; cover the question completely and clearly.' }, { question: 'Can AI write the content?', answer: 'Tools may assist, but the published work should add accurate, useful, reviewed value and comply with search policies.' }],
    sources: [sources.googleHelpful, sources.googleAiSearch, sources.googleLocalData], related: ['generative-engine-optimisation-geo-for-tradies', 'local-seo-for-tradies-australia', 'questions-tradie-service-pages-should-answer'],
  }),
  makeGuide({
    slug: 'generative-engine-optimisation-geo-for-tradies', number: 127, category: 'Local growth',
    title: 'What Is Generative Engine Optimisation for Tradies?',
    description: 'A practical approach to being understandable and recommendable in AI-assisted search without chasing gimmicks or mass-producing thin pages.',
    directAnswer: 'Generative engine optimisation is the effort to make a business and its expertise easy for AI-assisted search systems to understand and responsibly reference. The durable approach is the same foundation as good SEO: unique first-hand value, accurate entity and service facts, useful answers, high-quality images, clear sourcing, crawlable pages, internal connections and a trustworthy customer experience. There is no special file or hack that guarantees recommendation.',
    heroImage: '/blog/127-geo-for-tradies.webp', heroAlt: 'Australian plumber comparing AI-assisted search answers with the trade business website',
    keyPoints: ['Useful non-commodity content matters more than GEO tricks.', 'Consistent business facts help systems identify the right entity.', 'Recommendation still depends on reputation, relevance and customer experience.'],
    sections: [
      { heading: 'Build a trustworthy business entity', paragraphs: ['Keep the name, category, service area, phone, website, hours and proof accurate across the site and Business Profile. Conflicting facts make the business harder for customers and systems to understand.'] },
      { heading: 'Publish experience other sites cannot copy', bullets: ['Real call-flow decisions', 'Trade-specific boundaries', 'Original product screenshots', 'Worked examples labelled accurately', 'Customer-approved outcomes when available', 'Clear operator and review process'] },
      { heading: 'Answer the whole decision', paragraphs: ['A short definition is useful, but the page should also explain fit, limitations, cost, safety, privacy and next steps where relevant so the reader does not need another search.'] },
      { heading: 'Avoid scaled-content shortcuts', paragraphs: ['Google’s current guidance says creating many query-variation pages primarily to manipulate generative responses can violate spam policy. Build distinct pages around distinct customer jobs and questions.'] },
      { heading: 'Make the offline experience support the online claim', paragraphs: ['AI systems can surface a business, but customers still judge the call, quote and work. Answer the phone consistently, follow through and earn genuine reviews.'], callout: { label: 'GEO PRINCIPLE', text: 'Be the clearest credible source on the customer problem—not the loudest producer of pages.' } },
    ],
    example: { title: 'A distinct plumber resource', text: 'Instead of publishing 50 copied “plumber in suburb” pages, the business publishes its real leak intake process, safe photo brief, service boundaries, pricing process and local coverage, backed by genuine work and a dependable phone path.' },
    productVisual: 'lead', productCaption: 'TradieRelay’s real workflow evidence makes product claims inspectable instead of generic AI marketing.',
    faqs: [{ question: 'Does llms.txt guarantee AI visibility?', answer: 'No. Google’s current AI-search guidance says to focus on effective SEO and useful content rather than unnecessary AI-specific files or hacks.' }, { question: 'Should content be split into tiny chunks for AI?', answer: 'Use headings for readers and clarity, not artificial fragmentation to manipulate systems.' }, { question: 'Can TradieRelay guarantee it will be recommended?', answer: 'No. No provider can guarantee rankings or recommendations across independent search and AI systems.' }],
    sources: [sources.googleAiSearch, sources.googleHelpful, sources.googleProfile], related: ['answer-engine-optimisation-aeo-for-tradies', 'local-seo-for-tradies-australia', 'connect-tradie-marketing-to-phone-answering'],
  }),
  makeGuide({
    slug: 'connect-tradie-marketing-to-phone-answering', number: 128, category: 'Local growth',
    title: 'How Do Tradies Connect Marketing to Phone Answering?',
    description: 'The final link between ads, local search, website promises, qualified calls, human response and measurable booked work.',
    directAnswer: 'Promote only the services and areas the business wants, publish a tracked phone or enquiry route where appropriate, make the call greeting and qualification match the offer, assign one person to each suitable lead, record source and outcome, and feed poor-fit calls back into marketing. The goal is not more calls; it is more wanted work with a dependable customer hand-off.',
    heroImage: '/blog/128-marketing-to-phone-answering.webp', heroAlt: 'Australian trade business team connecting website advertising phone leads and booked jobs on one planning wall',
    keyPoints: ['The ad, page and call flow must promise the same service.', 'Every suitable lead needs an owner after capture.', 'Optimise marketing from fit and outcome, not call volume.'],
    sections: [
      { heading: 'Align the offer', paragraphs: ['Write down the promoted service, service area, customer type, availability and next step. The call flow should collect the facts needed for that exact offer and politely handle everything else.'] },
      { heading: 'Preserve useful source context', bullets: ['Campaign number or page', 'Caller-reported source when useful', 'Service and suburb', 'New or existing customer', 'Fit and requested timing', 'Owner and final outcome'] },
      { heading: 'Design the hand-off before buying traffic', paragraphs: ['Name who reviews daytime, after-hours, project and urgent enquiries. More advertising will amplify an unowned callback problem.'] },
      { heading: 'Review poor-fit calls as feedback', paragraphs: ['Out-of-area, wrong-trade, price-only and unavailable-service calls may reveal unclear ads or pages. Correct the promise before adding more qualification questions.'] },
      { heading: 'Measure the full path', paragraphs: ['Compare spend with legitimate enquiries, contact, suitable work, quotes or bookings and contribution. Keep attribution uncertainty visible and review customer complaints or opt-outs alongside commercial outcomes.'], callout: { label: 'FULL LOOP', text: 'Promise → call → useful job → named owner → customer decision → marketing learning.' } },
    ],
    example: { title: 'A hot-water campaign that closes the loop', text: 'The ad and page promote hot-water service in the actual Gold Coast area. Missed calls enter the matching intake flow, model photos attach to the job, the service coordinator owns the callback and outcomes feed the next campaign review.' },
    productVisual: 'dashboard', productCaption: 'The working call, job and quote views create the operating trail needed to connect marketing promises with real outcomes.',
    checklist: ['Name the wanted service and area.', 'Make the page and call flow agree.', 'Choose the source signal.', 'Assign the next-action owner.', 'Set the customer response promise.', 'Track fit, quote or booking and contribution.', 'Review poor-fit calls monthly.', 'Stop campaigns the operation cannot fulfil.'],
    faqs: [{ question: 'Should every campaign use a different phone number?', answer: 'Only when the tracking value justifies the number management and the customer experience remains clear.' }, { question: 'Does answering more calls fix poor marketing?', answer: 'No. It makes the real fit visible; the offer and targeting may still need correction.' }, { question: 'What is the first TradieRelay pilot?', answer: 'Usually no-answer or after-hours recovery for one real phone problem, with a named lead owner and review date.' }],
    sources: [sources.googleHelpful, sources.googleAiSearch, sources.oaicApp11], related: ['use-call-reasons-improve-tradie-marketing', 'local-seo-for-tradies-australia', 'build-business-case-ai-receptionist-pilot'],
  }),
];
