import { makeGuide, sources } from './shared';

export const revenueMeasurementGuides = [
  makeGuide({
    slug: 'how-many-missed-calls-too-many-tradie', number: 101, category: 'Revenue & measurement',
    title: 'How Many Missed Calls Are Too Many for a Tradie?',
    description: 'A practical way to judge missed-call pain from opportunity, customer impact and callback capacity—not a magic industry percentage.',
    directAnswer: 'There is no universal acceptable number. A single missed high-value call can matter, while many spam calls may not. Measure total missed business calls, legitimate new enquiries, how many receive a timely callback, what they become and whether the team has capacity to respond. The problem is “valuable calls with no useful recovery”, not a raw missed-call count.',
    heroImage: '/blog/101-how-many-missed-calls.webp', heroAlt: 'Australian sole trader reviewing a week of missed business calls after finishing work',
    keyPoints: ['Count legitimate opportunities, not every ring.', 'Measure recovery and outcome, not only misses.', 'Capacity matters: captured leads still need an owner.'],
    sections: [
      { heading: 'Start with one normal fortnight', paragraphs: ['Record answered, missed, abandoned, supplier, spam, existing-customer and new-job calls. Do not buy a solution from a single unusually busy day.'] },
      { heading: 'Find the unrecovered opportunity', bullets: ['New enquiry missed', 'No callback or callback too late', 'Customer already chose someone else', 'Job was in service area and preferred scope', 'Business had capacity or could schedule it', 'Likely value justified the follow-up'] },
      { heading: 'Include customer-service misses', paragraphs: ['Existing customers calling about access, timing or a problem may not create new revenue, but leaving them unanswered can create rework and lost trust. Measure them separately from new leads.'] },
      { heading: 'Check the human bottleneck', paragraphs: ['If captured leads still sit unreviewed, more call automation will not solve the ownership problem. Name the reviewer and response expectation before expanding coverage.'] },
      { heading: 'Set a business threshold', paragraphs: ['Choose the level of unrecovered preferred work that justifies action, then compare the cost and effort of coverage with realistic recovered contribution—not revenue alone.'], callout: { label: 'RIGHT QUESTION', text: 'How much wanted work is going cold because nobody captured and owned the next step?' } },
    ],
    example: { title: 'Twelve missed calls, three real opportunities', text: 'In one week the business misses twelve calls. Five are suppliers or spam, four call back, and three are preferred new jobs with no recovery. The decision is based on those three and their likely contribution—not the headline twelve.' },
    productVisual: 'dashboard', productCaption: 'A useful dashboard separates calls, jobs and outcomes so the business can measure recovered work instead of raw ring volume.',
    faqs: [{ question: 'Is a 10% missed-call rate bad?', answer: 'It depends on which calls were missed, recovery speed, outcomes and capacity. Avoid a generic benchmark.' }, { question: 'Should spam calls count?', answer: 'Track them operationally but separate them from legitimate opportunity.' }, { question: 'How long should the baseline be?', answer: 'At least a normal fortnight is a practical start; use longer if call volume is low or seasonal.' }],
    related: ['calculate-value-of-missed-tradie-call', 'what-happens-after-tradie-misses-call', 'who-is-ai-receptionist-best-suited-to'],
  }),
  makeGuide({
    slug: 'calculate-value-of-missed-tradie-call', number: 102, category: 'Revenue & measurement',
    title: 'How Do You Calculate the Value of a Missed Tradie Call?',
    description: 'A simple contribution-based calculation that avoids treating every ring as a guaranteed full-price job.',
    directAnswer: 'Estimate the number of legitimate preferred enquiries that go unrecovered, multiply by the realistic booking rate and average contribution per completed job, then subtract the cost of handling and delivery. Use contribution after direct labour, materials and variable costs—not the full invoice value—and show a range because call quality varies.',
    heroImage: '/blog/102-value-missed-tradie-call.webp', heroAlt: 'Australian plumbing business owner calculating missed-call value with invoices and a phone log',
    keyPoints: ['A missed call is not automatically a lost job.', 'Use contribution, not headline revenue.', 'Model conservative, expected and strong cases.'],
    sections: [
      { heading: 'Count legitimate unrecovered enquiries', paragraphs: ['Remove spam, suppliers, out-of-area work, unsuitable jobs and callers who were successfully recovered another way. Keep the calls the business wanted and could have served.'] },
      { heading: 'Estimate booking probability', paragraphs: ['Use the business’s own lead outcomes where possible. If data is thin, use a conservative range and update it after a pilot instead of claiming an industry conversion rate.'] },
      { heading: 'Calculate job contribution', bullets: ['Invoice value', 'Less materials', 'Less direct labour or subcontract cost', 'Less job-specific travel and fees', 'Equals contribution before fixed overhead'] },
      { heading: 'Compare recovery cost', paragraphs: ['Include monthly plan, setup spread across the test period, phone usage, staff review time and any integration cost. A cheap tool that creates unowned admin is not free.'] },
      { heading: 'Use a range', paragraphs: ['Show what happens if only one, three or five additional suitable jobs are recovered. The decision should survive a conservative case.'], callout: { label: 'SIMPLE MODEL', text: 'Unrecovered suitable enquiries × booking rate × average contribution − recovery cost.' } },
    ],
    example: { title: 'A conservative service calculation', text: 'The plumber identifies six suitable unrecovered enquiries a month. At a cautious one-third booking rate and $280 average contribution, expected contribution is $560 before recovery cost. The owner can compare that with the actual plan and setup cost; the numbers are illustrative, not a TradieRelay claim.' },
    productVisual: 'dashboard', productCaption: 'TradieRelay can show captured jobs and outcomes; the business supplies its own contribution assumptions.',
    faqs: [{ question: 'Should average invoice value be used?', answer: 'Contribution is more useful because materials and direct job costs vary.' }, { question: 'Can TradieRelay guarantee recovered revenue?', answer: 'No. Call quality, capacity, response and customer choice determine outcomes.' }, { question: 'How often should the assumptions change?', answer: 'Replace estimates with actual pilot outcomes as soon as there is enough data.' }],
    related: ['how-many-missed-calls-too-many-tradie', 'ai-receptionist-cost-tradies-australia', 'measure-quote-follow-up-winning-more-jobs'],
  }),
  makeGuide({
    slug: 'first-30-days-ai-receptionist-metrics', number: 103, category: 'Revenue & measurement',
    title: 'What Should Tradies Measure in the First 30 Days of an AI Receptionist?',
    description: 'A small launch scorecard covering caller experience, capture quality, human response and business outcomes.',
    directAnswer: 'Measure routed calls, legitimate enquiries captured, completion and correction rates, wrong routes, urgent and fallback performance, customer opt-outs or complaints, lead review time, contact rate, bookings or quotes and the staff work removed. Keep safety, privacy and routing failures as separate gates rather than averaging them into a score.',
    heroImage: '/blog/103-first-30-days-scorecard.webp', heroAlt: 'Australian tradie and young software founder reviewing a 30-day receptionist scorecard',
    keyPoints: ['Measure the caller, system and human hand-off separately.', 'High-consequence failures are gates, not averages.', 'Track work removed as well as leads captured.'],
    sections: [
      { heading: 'Week one: prove control', bullets: ['Correct greeting and disclosure', 'Correct account', 'Normal and urgent route', 'Message-mode fallback', 'Photo attachment', 'Opt-out handling'] },
      { heading: 'Week two: improve capture', paragraphs: ['Review incomplete calls, corrected names and suburbs, repeated questions and unclear next-step wording. Tighten the flow without adding questions for every edge case.'] },
      { heading: 'Week three: check human response', paragraphs: ['Measure how quickly owners review new jobs and whether notifications produce action. A correct lead can still fail commercially when it sits untouched.'] },
      { heading: 'Week four: judge business value', paragraphs: ['Compare preferred enquiries, contact, quote or booking outcomes, contribution estimates and office interruptions removed. Separate seasonal noise and test calls.'] },
      { heading: 'Make a keep, change or stop decision', paragraphs: ['Expand only the paths that work. Fix or pause any control failure. Remove questions, routes or messages that add work without improving an outcome.'], callout: { label: '30-DAY OUTPUT', text: 'Keep, change or stop each workflow—with evidence and an owner.' } },
    ],
    example: { title: 'A useful pilot result', text: 'The service captures 28 legitimate enquiries; 25 are correct without edit, three need suburb corrections, one urgent backup fails and is fixed before continued use. The owner reviews 22 within the target and books eight. These are illustrative numbers, not customer results.' },
    productVisual: 'dashboard', productCaption: 'The working dashboard provides the call, job and outcome trail needed for a small operating scorecard.',
    faqs: [{ question: 'Should call minutes be the main metric?', answer: 'No. Minutes are a cost input; useful outcomes and controlled failures matter more.' }, { question: 'What should stop the pilot?', answer: 'Unresolved safety, privacy, account-isolation or urgent-routing failures should pause the affected path.' }, { question: 'Should we compare with the prior month?', answer: 'Yes, while noting seasonality, marketing changes and different capacity.' }],
    sources: [sources.aiGuardrails], related: ['test-ai-receptionist-before-going-live', 'fortnightly-ai-receptionist-optimisation-review', 'calculate-value-of-missed-tradie-call'],
  }),
  makeGuide({
    slug: 'how-fast-should-tradie-call-new-lead-back', number: 104, category: 'Revenue & measurement',
    title: 'How Fast Should a Tradie Call a New Lead Back?',
    description: 'How to set a realistic response standard by urgency, job value, time of day and who actually owns the callback.',
    directAnswer: 'Call suitable new enquiries as soon as the responsible person can give them useful attention. Set different internal targets for approved urgent reviews, daytime preferred leads and after-hours routine work. Do not publish a callback promise the roster cannot keep, and do not chase speed at the expense of reading the job details first.',
    heroImage: '/blog/104-tradie-lead-callback-speed.webp', heroAlt: 'Australian electrician returning a qualified customer call from a parked work van',
    keyPoints: ['Use different targets for different lead types.', 'Read the captured context before calling.', 'A dependable promise beats a vague “immediate” claim.'],
    sections: [
      { heading: 'Define response lanes', bullets: ['Approved urgent: immediate human review', 'Preferred daytime: short same-day target', 'After hours: named morning-review time', 'Project quote: estimator target', 'Unclear fit: owner review', 'Existing customer: issue-owner target'] },
      { heading: 'Match the promise to the roster', paragraphs: ['A sole trader on the tools may not call in five minutes. A coordinator may. Choose the standard the real owner can keep across a normal working week.'] },
      { heading: 'Use the context before the call', paragraphs: ['A 60-second review of suburb, job, urgency, photos and preferred time can make the callback shorter and more credible. Speed without preparation forces the customer to repeat everything.'] },
      { heading: 'Escalate overdue work visibly', paragraphs: ['An overdue lead should appear in a review list for the owner or office. Avoid repeated group alerts that make everybody mute the system.'] },
      { heading: 'Measure contact and outcome', paragraphs: ['Track whether the customer was reached, whether the business fit and what happened. A fast missed callback and three voicemails are not a successful response.'], callout: { label: 'RESPONSE STANDARD', text: 'Fast enough to keep the opportunity; prepared enough to make the callback useful.' } },
    ],
    example: { title: 'On the tools versus in the office', text: 'The business sets urgent review to the on-call person, daytime service leads to a coordinator within 20 minutes and after-hours routine leads for review by 8:30 am. These are business-chosen examples, not universal benchmarks.' },
    productVisual: 'alert', productCaption: 'The alert gives the lead owner enough context to prioritise and prepare the callback.',
    faqs: [{ question: 'Is five minutes always best?', answer: 'No. The target must reflect lead type, roster and the ability to respond usefully.' }, { question: 'Should the AI promise the callback time?', answer: 'Only the approved, operationally supported window.' }, { question: 'What if the customer does not answer?', answer: 'Use a limited, respectful callback and message rule and keep the outcome on the job.' }],
    related: ['what-information-tradie-needs-before-calling-back', 'who-owns-recovered-tradie-lead', 'what-happens-after-tradie-misses-call'],
  }),
  makeGuide({
    slug: 'measure-tradie-lead-to-booking-conversion', number: 105, category: 'Revenue & measurement',
    title: 'How Do Tradies Measure Lead-to-Booking Conversion?',
    description: 'A clear funnel from legitimate enquiry to contact, fit, quote or booking without hiding unsuitable calls in the denominator.',
    directAnswer: 'Count legitimate new enquiries, then track contacted, suitable, quoted or offered a time, booked and completed. Report the reasons unsuitable work was declined and keep duplicates, spam and supplier calls separate. Conversion is useful only when the stages and time period are defined consistently.',
    heroImage: '/blog/105-lead-to-booking-conversion.webp', heroAlt: 'Australian trade business owner reviewing a lead-to-booking funnel on a workshop whiteboard',
    keyPoints: ['Define each stage before calculating a rate.', 'Separate unsuitable calls from response failures.', 'Track completed work as well as bookings.'],
    sections: [
      { heading: 'Use a simple funnel', bullets: ['Legitimate new enquiry', 'Contacted', 'Suitable preferred work', 'Quoted or time offered', 'Booked', 'Completed', 'Paid or closed'] },
      { heading: 'Choose the denominator', paragraphs: ['Booked divided by all rings is rarely useful. Booked divided by suitable contacted enquiries may explain sales performance; captured divided by legitimate missed calls explains recovery. Name the question before choosing the rate.'] },
      { heading: 'Record loss reasons', paragraphs: ['Out of area, wrong trade, no capacity, price, timing, customer unreachable and competitor chosen are different problems. One “lost” status hides the action.'] },
      { heading: 'Use cohorts, not mixed ages', paragraphs: ['Give new leads enough time to progress and compare enquiries from the same period. Do not treat yesterday’s open quote as a lost booking.'] },
      { heading: 'Protect quality', paragraphs: ['A higher booking rate can be bad if the business accepts poor-fit work or creates cancellations. Review contribution, customer outcome and capacity alongside the funnel.'], callout: { label: 'FUNNEL RULE', text: 'A rate is only meaningful when every stage means the same thing every week.' } },
    ],
    example: { title: 'A small monthly funnel', text: 'The business captures 40 legitimate new enquiries, contacts 34, finds 25 suitable, offers 18 quotes or times and books 12. The manager can investigate the six uncontacted and seven suitable leads that never received an offer. Illustrative data only.' },
    productVisual: 'pipeline', productCaption: 'Consistent job statuses make a lead funnel measurable without relying on memory.',
    faqs: [{ question: 'Should out-of-area leads count as lost?', answer: 'Record them, but separate them from suitable opportunities when judging sales conversion.' }, { question: 'What about repeat customers?', answer: 'Track them separately when their buying path is materially different.' }, { question: 'How often should the funnel be reviewed?', answer: 'Weekly for operational exceptions and monthly for a more stable conversion view.' }],
    related: ['what-information-tradie-needs-before-calling-back', 'first-30-days-ai-receptionist-metrics', 'measure-quote-follow-up-winning-more-jobs'],
  }),
  makeGuide({
    slug: 'measure-automated-quote-follow-up', number: 106, category: 'Revenue & measurement',
    title: 'How Do You Measure Automated Quote Follow-Up?',
    description: 'The sent, delivered, viewed, replied, accepted and stopped events that show whether follow-up is helping customers decide.',
    directAnswer: 'Track quotes eligible for follow-up, messages sent and delivered, quote views, replies or questions, acceptance, decline, expiry, opt-out and manual stop. Compare with a similar baseline and review contribution from genuinely won jobs. A viewed quote is engagement, not acceptance, and follow-up should stop when the customer decides.',
    heroImage: '/blog/106-measure-quote-follow-up.webp', heroAlt: 'Australian painting contractor reviewing quote follow-up outcomes on a tablet',
    keyPoints: ['Measure the whole event trail, not only sent messages.', 'Viewed does not mean accepted.', 'Stop events are part of quality, not lost automation.'],
    sections: [
      { heading: 'Define eligible quotes', paragraphs: ['Exclude test, withdrawn, already accepted, expired or disputed quotes before measuring a sequence. Otherwise the denominator makes the workflow look worse or busier than it is.'] },
      { heading: 'Track the useful events', bullets: ['Sent', 'Delivered or failed', 'Opened or viewed where available', 'Customer reply or question', 'Accepted', 'Declined', 'Expired', 'STOP or manual stop'] },
      { heading: 'Separate engagement from revenue', paragraphs: ['A view shows that a link was opened under the system’s measurement method. It does not prove who read it, whether they understood it or whether they will proceed.'] },
      { heading: 'Check customer friction', paragraphs: ['Review opt-outs, negative replies, repeated questions and messages sent after a decision. A sequence that wins work while irritating many customers needs correction.'] },
      { heading: 'Compare contribution, not vanity', paragraphs: ['Estimate the additional accepted contribution after message and staff costs. Use a baseline or controlled period and avoid claiming every accepted quote was caused by the reminder.'], callout: { label: 'MEASUREMENT CAUTION', text: 'The sequence may assist the decision; acceptance still depends on scope, price, timing and trust.' } },
    ],
    example: { title: 'A clean quote cohort', text: 'Twenty eligible quotes receive the approved sequence. Eighteen messages deliver, twelve links are viewed, four customers ask a question, five accept and two decline. The business reviews the two failures and stops all closed sequences. Illustrative data only.' },
    productVisual: 'customer-quote', productCaption: 'The customer quote and status trail support sent, viewed and decision tracking without treating a view as a win.',
    faqs: [{ question: 'Does a quote view prove the customer read it?', answer: 'No. It is a useful interaction signal with measurement limits.' }, { question: 'Should accepted quotes keep receiving reminders?', answer: 'No. Acceptance should stop the sequence.' }, { question: 'Can follow-up success be guaranteed?', answer: 'No. Use actual customer and commercial outcomes, not promises.' }],
    sources: [sources.acmaSpam], related: ['measure-quote-follow-up-winning-more-jobs', 'track-whether-customer-viewed-trade-quote', 'when-automated-quote-follow-up-stop'],
  }),
  makeGuide({
    slug: 'which-missed-tradie-calls-worth-chasing', number: 107, category: 'Revenue & measurement',
    title: 'Which Missed Tradie Calls Are Worth Chasing?',
    description: 'A fit, value, urgency and capacity filter that helps the team return the right calls first without ignoring customers unfairly.',
    directAnswer: 'Prioritise legitimate enquiries inside the service area and preferred work, especially where the caller supplied useful details, timing fits and the business has capacity. Existing-customer problems and approved urgent indicators may take priority for trust or risk reasons. Do not rank people by accent, postcode stereotypes or ability to sound confident.',
    heroImage: '/blog/107-which-missed-calls-chase.webp', heroAlt: 'Australian landscaper prioritising several missed customer enquiries beside a work trailer',
    keyPoints: ['Use business fit and customer need, not personal assumptions.', 'Existing-customer risk can outrank new revenue.', 'Show the reason for priority so a person can review it.'],
    sections: [
      { heading: 'Check whether the call is actionable', bullets: ['Valid callback route', 'Service location', 'Job type or customer issue', 'Requested timing', 'Enough context for the next call', 'No known duplicate or spam pattern'] },
      { heading: 'Apply the business fit rules', paragraphs: ['Preferred trades, minimum job rules, territory and capacity make the callback useful. Keep boundary and uncertain work visible for human review instead of silently discarding it.'] },
      { heading: 'Protect existing customers', paragraphs: ['An access problem, complaint or failed visit may not be a new sale, but prompt recovery can prevent rework and damage. Give these calls a separate priority path.'] },
      { heading: 'Avoid unfair shortcuts', paragraphs: ['Do not use the caller’s accent, name, emotion, suburb reputation or communication style as a value score. Prioritise observable business facts and declared need.'] },
      { heading: 'Review what the priority produced', paragraphs: ['Check whether high-priority leads were genuinely suitable and whether low-priority leads were overlooked. Adjust the rule, not individual customer stereotypes.'], callout: { label: 'FAIR PRIORITY', text: 'Fit, urgency, commitment and capacity—not who “sounds valuable”.' } },
    ],
    example: { title: 'Three calls at once', text: 'An existing customer cannot provide access, a new in-area preferred job includes photos and an out-of-area sales pitch arrives. The first two receive owned callback actions; the sales pitch follows the polite non-lead route.' },
    productVisual: 'pipeline', productCaption: 'The action pipeline can show reasoned priorities while leaving the final callback decision with a person.',
    faqs: [{ question: 'Should the highest invoice always come first?', answer: 'No. Existing commitments, urgency, fit and capacity also matter.' }, { question: 'Can the AI score a caller’s quality?', answer: 'It should apply approved observable rules, not subjective judgments about the person.' }, { question: 'What happens to uncertain leads?', answer: 'Place them in human review with the uncertainty visible.' }],
    sources: [sources.aiGuardrails], related: ['what-information-tradie-needs-before-calling-back', 'qualify-trade-lead-without-annoying-customer', 'what-happens-after-tradie-misses-call'],
  }),
  makeGuide({
    slug: 'use-call-reasons-improve-tradie-marketing', number: 108, category: 'Revenue & measurement',
    title: 'How Can Tradies Use Call Reasons to Improve Marketing?',
    description: 'How to connect enquiry type, source and outcome so marketing spend is judged by wanted work—not just phone volume.',
    directAnswer: 'Tag calls by source where known, job type, service area, new or existing customer, fit, outcome and reason lost. Compare the wanted booked or quoted work from each campaign with spend and capacity. Do not claim the last visible source caused the whole sale, and do not optimise toward high call volume that creates poor-fit enquiries.',
    heroImage: '/blog/108-call-reasons-improve-marketing.webp', heroAlt: 'Australian trade business owner comparing call reasons with local advertising campaigns',
    keyPoints: ['Connect calls to wanted outcomes, not volume.', 'Use source evidence when available and label uncertainty.', 'Feed repeated customer language back into pages and ads.'],
    sections: [
      { heading: 'Capture the minimum marketing context', bullets: ['Published number or campaign line', 'Caller-reported source if asked', 'Job type', 'Suburb', 'New or existing customer', 'Fit and outcome', 'Reason lost or declined'] },
      { heading: 'Judge quality by business goal', paragraphs: ['A campaign that produces fewer but better project enquiries may beat one generating many small out-of-area calls. Define the work the business wants before reading the dashboard.'] },
      { heading: 'Respect attribution limits', paragraphs: ['A customer may see a van, a review and a search result before calling. Treat phone source as evidence, not perfect causal proof.'] },
      { heading: 'Use customer language carefully', paragraphs: ['Repeated plain-English questions can improve service pages and FAQs. Answer the real question; do not create dozens of thin pages for every wording variation.'] },
      { heading: 'Close the marketing-to-phone loop', paragraphs: ['Check that promoted services, territories, hours and phone promises match what the call flow accepts. Advertising work the system declines wastes budget and trust.'], callout: { label: 'MARKETING TEST', text: 'Did the campaign create wanted, serviceable work the business actually progressed?' } },
    ],
    example: { title: 'A campaign with the wrong suburbs', text: 'Paid ads drive many roofing calls, but half fall outside the service area. The business narrows targeting and updates its service-area page instead of celebrating the call count.' },
    productVisual: 'dashboard', productCaption: 'Call and job records can connect source context with fit and outcome when the business captures the fields consistently.',
    faqs: [{ question: 'Can caller ID show the ad source?', answer: 'Not by itself. Dedicated numbers, campaign parameters or caller answers may provide source evidence.' }, { question: 'Should every call ask “how did you hear about us”?', answer: 'Only if the answer will be used and the question does not add unnecessary friction.' }, { question: 'Can call summaries improve website copy?', answer: 'Yes, by revealing recurring customer questions while protecting personal information.' }],
    sources: [sources.googleHelpful, sources.oaicApp11], related: ['what-information-tradie-needs-before-calling-back', 'measure-tradie-lead-to-booking-conversion', 'local-seo-for-tradies-australia'],
  }),
  makeGuide({
    slug: 'is-ai-receptionist-worth-it-sole-trader', number: 109, category: 'Revenue & measurement',
    title: 'Is an AI Receptionist Worth It for a Sole Trader?',
    description: 'A decision guide for one-person trade businesses based on call demand, job contribution, interruptions and response capacity.',
    directAnswer: 'It can be worthwhile when a sole trader regularly misses suitable calls while on the tools, the recovered contribution can exceed the full cost and there is time to review the captured leads. It is poor value when call volume is tiny, most work arrives elsewhere, the business has no capacity or the system adds another queue the owner will not check.',
    heroImage: '/blog/109-ai-receptionist-sole-trader-value.webp', heroAlt: 'Australian sole trader reviewing captured leads after completing a residential job',
    keyPoints: ['Measure wanted missed calls before buying.', 'A captured lead still needs owner time.', 'Start with a narrow no-answer pilot.'],
    sections: [
      { heading: 'Look for a real phone problem', paragraphs: ['Review a normal fortnight of missed, recovered and lost enquiries. The service should solve evidence, not anxiety about what might be happening.'] },
      { heading: 'Check whether the work fits', bullets: ['Preferred job types are calling', 'Service area is clear', 'Average contribution is known', 'Owner can return suitable leads', 'Existing number can forward', 'Caller experience can be tested'] },
      { heading: 'Count the work removed', paragraphs: ['Useful displacement may include stopping work to answer routine questions, calling vague missed numbers, retyping details and manually chasing every open quote.'] },
      { heading: 'Count the new work created', paragraphs: ['The owner still reviews leads, returns calls, corrects uncertain details and manages exceptions. If this work is not scheduled, the system may only make the backlog more visible.'] },
      { heading: 'Run a reversible pilot', paragraphs: ['Use no-answer or after-hours forwarding, one job flow, one owner and a fallback. Compare the full cost with actual recovered suitable contribution and interruptions removed.'], callout: { label: 'SOLE-TRADER TEST', text: 'Does it recover useful work and protect tool time without creating an ignored admin queue?' } },
    ],
    example: { title: 'A plumber who misses calls under sinks', text: 'The plumber misses six suitable enquiries a month and can handle two more jobs. A no-answer pilot captures them with photos and clear callbacks. The owner measures actual bookings and contribution before adding broader reception.' },
    productVisual: 'alert', productCaption: 'A sole trader can receive a concise lead alert without adopting a complicated office workflow.',
    faqs: [{ question: 'What is the smallest TradieRelay plan?', answer: 'Catch is currently the founding sole-trader plan at $399 per month plus a $499 setup, plus GST, subject to current offer and scope confirmation.' }, { question: 'Should a brand-new business use it?', answer: 'Only if there is enough demand and a clear offer. Reception does not create leads by itself.' }, { question: 'Can the owner switch forwarding off?', answer: 'Yes. The phone-provider forwarding instructions and off switch should be documented during setup.' }],
    sources: [sources.acccPrices], related: ['who-is-ai-receptionist-best-suited-to', 'ai-receptionist-cost-tradies-australia', 'calculate-value-of-missed-tradie-call'],
  }),
  makeGuide({
    slug: 'build-business-case-ai-receptionist-pilot', number: 110, category: 'Revenue & measurement',
    title: 'How Do You Build a Business Case for an AI Receptionist Pilot?',
    description: 'A one-page pilot decision covering the problem, scope, cost, expected displacement, risks, owner and keep-or-stop date.',
    directAnswer: 'Write the current call problem and baseline, choose one narrow workflow, state the work it should remove, name the person who acts on leads, calculate the full pilot cost, define outcome and control measures, and set a review date. Approve expansion only if the pilot creates useful customer and business outcomes without unresolved safety, privacy or routing failures.',
    heroImage: '/blog/110-ai-receptionist-business-case.webp', heroAlt: 'Australian trade business partners reviewing a one-page AI receptionist pilot business case',
    keyPoints: ['One problem and one owner make a test meaningful.', 'Include setup, usage and staff time in cost.', 'Set the stop or expand date before launch.'],
    sections: [
      { heading: 'Write the baseline problem', paragraphs: ['Use the number and type of missed suitable calls, current callback process, customer complaints or office interruptions. Avoid “we should use AI” as the problem statement.'] },
      { heading: 'Define the smallest scope', bullets: ['One business number', 'No-answer or after-hours condition', 'One trade flow', 'One primary owner and fallback', 'One customer next-step promise', 'One-month review period'] },
      { heading: 'State the displacement', paragraphs: ['Name the calls, retyping, chasing or interruptions the pilot should remove. If it only adds dashboards and messages, the business case fails.'] },
      { heading: 'Price the whole pilot', paragraphs: ['Include setup, monthly plan, expected usage, integrations, staff review time and exit or porting implications. Compare against realistic contribution and admin time—not revenue fantasy.'] },
      { heading: 'Set decision gates', paragraphs: ['Outcome measures can improve gradually; safety, privacy, account isolation and urgent-route controls must pass. Decide the review date and who signs off keep, change or stop.'], callout: { label: 'ONE-PAGE CASE', text: 'Problem + displacement + owner + cost + measures + risks + review date.' } },
    ],
    example: { title: 'A 30-day missed-call pilot', text: 'The electrical business forwards no-answer new enquiries, expects to remove blind callback work and names the service coordinator as owner. It measures captured suitable jobs, response and bookings, with a day-30 keep-or-stop decision.' },
    productVisual: 'rules', productCaption: 'A pilot should be traceable to the exact call condition, boundaries, owner and fallback shown in the account rules.',
    faqs: [{ question: 'How long should the pilot run?', answer: 'Long enough to see representative calls; 30 days is a practical starting point when volume is sufficient.' }, { question: 'Should every feature be included?', answer: 'No. Test the smallest workflow that can prove or disprove the value.' }, { question: 'What should stop expansion?', answer: 'Unresolved safety, privacy, isolation or routing failures, or a workflow that adds work without useful outcomes.' }],
    sources: [sources.aiGuardrails, sources.acccPrices], related: ['first-30-days-ai-receptionist-metrics', 'test-ai-receptionist-before-going-live', 'ai-receptionist-cost-tradies-australia'],
  }),
];
