import { makeGuide, sources } from './shared';

export const safetyReliabilityGuides = [
  makeGuide({
    slug: 'what-if-ai-receptionist-gets-detail-wrong', number: 111, category: 'Safety & reliability',
    title: 'What Happens If an AI Receptionist Gets a Customer Detail Wrong?',
    description: 'How confirmation, uncertainty labels, human review and correction stop a misheard suburb or phone number becoming a bad promise.',
    directAnswer: 'Important details should be repeated or otherwise confirmed, uncertain fields should be labelled, and the tradie should be able to compare the structured job with the source and correct it. A correction must update later routing and messages without hiding the original capture. High-consequence uncertainty should trigger human review rather than a guess.',
    heroImage: '/blog/111-ai-gets-customer-detail-wrong.webp', heroAlt: 'Australian trade coordinator comparing a call transcript with corrected customer address details',
    keyPoints: ['Confirm names, numbers, addresses and promises.', 'Show uncertainty instead of polishing it away.', 'Correct downstream routes and preserve an audit trail.'],
    sections: [
      { heading: 'Expect normal recognition errors', paragraphs: ['Mobile connections, road noise, accents, unfamiliar suburbs and trade terms create ambiguity. The system should be designed around that reality rather than marketed as perfect transcription.'] },
      { heading: 'Confirm decision-changing details', bullets: ['Caller name', 'Callback number', 'Service address or suburb', 'Job type', 'Reported urgency indicator', 'Requested or confirmed time', 'Price or scope item'] },
      { heading: 'Expose uncertainty', paragraphs: ['If the system is not confident or the caller corrects it, mark the field for review. A blank or uncertain field is safer than a confident wrong address.'] },
      { heading: 'Correct the record and consequences', paragraphs: ['A suburb correction may change territory; a number correction affects messages; a job-type correction affects owner. Show these consequences before resending or rerouting.'] },
      { heading: 'Improve the pattern', paragraphs: ['Repeated corrections for a suburb or business term should improve vocabulary and the confirmation question. One unusual call should not cause a broad new rule.'], callout: { label: 'FAIL SAFELY', text: 'Confirm, label uncertainty, hand off, correct and learn—never bluff.' } },
    ],
    example: { title: 'A misheard unit number', text: 'The job shows Unit 15, but the customer’s reply confirms Unit 50. The coordinator corrects the address before scheduling; the audit record preserves the original value and the new confirmation source.' },
    productVisual: 'lead', productCaption: 'The lead view presents AI-captured details as reviewable information rather than unquestionable truth.',
    faqs: [{ question: 'Can the transcript be wrong while the summary looks right?', answer: 'Yes. Important actions should use confirmed structured fields and source review where needed.' }, { question: 'Should every field be read back?', answer: 'Confirm the fields that change contact, route, safety or promise without making the call unnecessarily long.' }, { question: 'Can customers correct details by SMS?', answer: 'Yes, when two-way messaging is enabled and the reply is attached to the job.' }],
    sources: [sources.aiGuardrails], related: ['correct-ai-captured-tradie-job', 'what-happens-when-ai-does-not-know-answer', 'test-ai-receptionist-before-going-live'],
  }),
  makeGuide({
    slug: 'prevent-ai-receptionist-inventing-prices', number: 112, category: 'Safety & reliability',
    title: 'How Do You Stop an AI Receptionist Inventing Prices?',
    description: 'A closed-price-list, permission and human-review design that keeps phone answers and quotes inside approved business data.',
    directAnswer: 'Disable open-ended price generation. Allow the assistant to quote only an active approved item or rule with clear conditions, version and GST treatment; otherwise capture the enquiry for a person. Restrict who can change prices, log changes, test price questions and make customer quotes reviewable before sending.',
    heroImage: '/blog/112-stop-ai-inventing-prices.webp', heroAlt: 'Australian plumber reviewing an approved service price list before answering a customer',
    keyPoints: ['No approved item means no price.', 'Account owners control saved products and prices.', 'Complex scope and exceptions go to a person.'],
    sections: [
      { heading: 'Use a closed set of approved data', paragraphs: ['The system can repeat an approved call-out fee, inspection fee or saved product only when the business has defined exactly when it applies. It should not calculate from generic market information.'] },
      { heading: 'Include the price conditions', bullets: ['GST treatment', 'What is included', 'What is excluded', 'Location or after-hours conditions', 'Expiry or effective date', 'Who approved it'] },
      { heading: 'Give complex work a human path', paragraphs: ['Unknown site condition, diagnosis, material quantity, access, variation and project work belong in review. “We need to inspect before pricing” is a useful answer.'] },
      { heading: 'Control edits', paragraphs: ['The tradie can add, edit, save and delete their products and prices. Changes should be authorised and visible so an old or accidental figure is not used.'] },
      { heading: 'Test how the system refuses', paragraphs: ['Ask for discounts, bundles, competitor matching, after-hours exceptions and a price not in the library. The assistant should not be pressured into a number.'], callout: { label: 'PRICE RULE', text: 'Approved active item with matching conditions—or human review.' } },
    ],
    example: { title: 'A fixed call-out fee, not a repair quote', text: 'The account has an approved $165 inspection fee including the defined inclusions. The assistant may repeat it when the rule matches. It does not estimate the repair until the plumber reviews the job. Illustrative product data only.' },
    productVisual: 'products-prices', productCaption: 'The working products and prices screen gives the account owner direct control of the items used in quotes.',
    faqs: [{ question: 'Can tradies change their own prices?', answer: 'Yes. The working app allows account users to add, edit, save and delete products and prices.' }, { question: 'Can the AI discount a price?', answer: 'Only under a specific authorised rule; the safe default is human approval.' }, { question: 'Should prices include GST?', answer: 'Price-display requirements depend on audience and context. Confirm the business’s legal and accounting treatment.' }],
    sources: [sources.acccPrices, sources.acccClaims, sources.aiGuardrails], related: ['saved-products-prices-speed-up-trade-quotes', 'saved-products-prices-speed-up-trade-quotes', 'what-can-ai-receptionist-do-and-never-do'],
  }),
  makeGuide({
    slug: 'write-emergency-wording-ai-receptionist', number: 113, category: 'Safety & reliability',
    title: 'How Should Tradies Write Emergency Wording for an AI Receptionist?',
    description: 'A short, business-approved emergency path that stops intake, avoids remote advice and sends the caller to appropriate help.',
    directAnswer: 'Define the observable reports that trigger the emergency path, use short wording approved for the trade and jurisdiction, direct the caller to the appropriate emergency service where required, and end or hand over the call without diagnosis. The assistant must not claim the situation is safe, keep asking qualification questions or promise that the tradie is attending.',
    heroImage: '/blog/113-emergency-wording-ai-receptionist.webp', heroAlt: 'Australian trade business owner and safety adviser reviewing emergency call wording',
    keyPoints: ['Emergency wording is written before the call.', 'Stop normal qualification when the trigger is met.', 'Emergency services and qualified humans make emergency decisions.'],
    sections: [
      { heading: 'Separate emergency from urgent business work', paragraphs: ['Urgent may mean prompt owner review. Emergency means the business’s call flow must direct the caller toward immediate appropriate help rather than continue sales intake.'] },
      { heading: 'Use observable trigger wording', paragraphs: ['Write what a caller might report, not a diagnosis the assistant must infer. Have the licensed or responsible business person approve the trigger and response.'] },
      { heading: 'Keep the response short', bullets: ['Acknowledge the report', 'State that the assistant cannot provide emergency or trade advice', 'Use the approved emergency-services direction', 'Do not promise attendance', 'End or transfer under the tested rule', 'Alert the business if appropriate'] },
      { heading: 'Do not improvise', paragraphs: ['The assistant should not add safety steps, reassure the caller, or debate whether the trigger is serious. This is a boundary, not a conversational opportunity.'] },
      { heading: 'Test exact scenarios', paragraphs: ['Run emergency, urgent-but-not-emergency and ambiguous calls for each trade. A missed emergency path is a launch-stopping failure for that flow.'], callout: { label: 'EMERGENCY GATE', text: 'Stop intake, use approved direction, make no attendance promise.' } },
    ],
    example: { title: 'Emergency language interrupts qualification', text: 'A caller describes a condition that matches the electrical business’s emergency trigger. The assistant stops asking for quote details, uses the approved emergency direction and does not claim an electrician is on the way.' },
    productVisual: 'rules', productCaption: 'Emergency and urgent boundaries belong in the visible, approved call rules and acceptance tests.',
    faqs: [{ question: 'Can TradieRelay diagnose an emergency?', answer: 'No. It applies approved reported-condition triggers and directs the caller under the business’s rule.' }, { question: 'Should it keep collecting the address?', answer: 'The approved emergency path determines the minimum action; it should not delay appropriate emergency contact.' }, { question: 'Is this legal or safety advice?', answer: 'No. Each business must obtain appropriate professional guidance for its wording, trade and jurisdictions.' }],
    sources: [sources.aiStandard, sources.aiGuardrails], related: ['urgent-jobs-vs-emergency-jobs', 'ai-receptionist-transfer-urgent-calls', 'what-can-ai-receptionist-do-and-never-do'],
  }),
  makeGuide({
    slug: 'privacy-notice-ai-receptionist-tradies', number: 114, category: 'Safety & reliability',
    title: 'What Should a Tradie’s AI Receptionist Privacy Notice Cover?',
    description: 'The collection, purpose, disclosure, access, retention and contact information customers need in plain English.',
    directAnswer: 'Explain who is collecting the information, that an automated assistant is involved, what call, contact, job, photo and message data is collected, why it is needed, who may receive or process it, what happens if it is not provided, how long it is kept, and how a person can access, correct, complain or contact the business. Tailor the notice to the actual setup and legal obligations.',
    heroImage: '/blog/114-ai-receptionist-privacy-notice.webp', heroAlt: 'Australian trade business owner reviewing a plain-English customer privacy notice',
    keyPoints: ['Describe the real data flow, not generic privacy language.', 'Give essential notice at collection and link to the full policy.', 'Include access, correction, complaint and contact routes.'],
    sections: [
      { heading: 'Name the collector and service', paragraphs: ['The caller should know which trade business is handling the enquiry and that an automated assistant is taking details. Avoid making the technology provider look like the customer-facing business.'] },
      { heading: 'List the information and purposes', bullets: ['Caller identity and contact', 'Service address and job details', 'Call audio or transcript if used', 'Customer photos', 'Messages and quote interactions', 'Routing, booking and service administration'] },
      { heading: 'Explain sharing and processing', paragraphs: ['Name the types of providers and people that handle the information, including phone, messaging, hosting and authorised business staff. State any relevant overseas handling based on the actual setup.'] },
      { heading: 'Provide choices and rights', paragraphs: ['Explain what happens if required information is not provided and how a person can request access or correction, complain or contact the business.'] },
      { heading: 'Keep the notice in sync', paragraphs: ['Update the notice when recording, photo collection, integrations, providers or purposes change. A copied policy that does not match the service creates risk.'], callout: { label: 'PLAIN-ENGLISH TEST', text: 'Could a customer understand what is collected, why, who sees it and how to ask a question?' } },
    ],
    example: { title: 'Layered notice on the call and website', text: 'The greeting identifies the automated assistant and purpose. The follow-up SMS links to the full privacy notice describing call details, photos, providers, retention and contact rights. The business checks the notice against the live account.' },
    productVisual: 'photo-request', productCaption: 'Photo collection is one concrete data flow the privacy notice should describe accurately.',
    faqs: [{ question: 'Does every small business fall under the Privacy Act?', answer: 'Not necessarily; exemptions and exceptions apply. Businesses should check their position and can still adopt good privacy practices.' }, { question: 'Is AI disclosure the same as a full privacy notice?', answer: 'No. The introduction can give essential context and point to fuller information.' }, { question: 'Who should review the notice?', answer: 'The business should obtain legal or privacy advice appropriate to its actual data, providers and jurisdictions.' }],
    sources: [sources.oaicApp5, sources.oaicAi, sources.oaicApp11], related: ['tell-callers-speaking-to-ai-australia', 'is-customer-call-data-safe-ai-receptionist', 'how-long-keep-call-recordings-customer-photos'],
  }),
  makeGuide({
    slug: 'customer-access-delete-ai-call-data', number: 115, category: 'Safety & reliability',
    title: 'How Should Tradies Handle Requests to Access, Correct or Delete AI Call Data?',
    description: 'A practical identity, search, review and response process for customer call records, messages and photos.',
    directAnswer: 'Provide one contact route, verify the requester proportionately, identify the relevant account and records, preserve anything subject to a legal or dispute hold, and have an authorised person assess access, correction or deletion under applicable law and policy. Record the request and outcome. Do not delete blindly from one screen while copies remain elsewhere.',
    heroImage: '/blog/115-customer-data-request.webp', heroAlt: 'Australian trade administrator processing a customer request about call and photo data',
    keyPoints: ['Verify identity without collecting excessive new data.', 'Search every relevant system and provider.', 'Record the legal or policy reason for the outcome.'],
    sections: [
      { heading: 'Give customers one route', paragraphs: ['Publish a privacy contact that can receive access, correction and complaint requests. Staff should know where to send the request instead of handling it informally on a personal phone.'] },
      { heading: 'Verify and scope the request', bullets: ['Requester identity', 'Business account', 'Phone number or address', 'Approximate call or job date', 'Records requested', 'Preferred response route'] },
      { heading: 'Search the full data path', paragraphs: ['Check the TradieRelay account, phone or messaging provider, exports, support records and connected systems. A deletion button in one product may not remove legally retained or separately stored copies.'] },
      { heading: 'Assess the response', paragraphs: ['Applicable privacy, contractual, accounting, dispute and safety obligations may affect access or deletion. Use an authorised human and obtain advice where needed.'] },
      { heading: 'Close and record the request', paragraphs: ['Tell the customer what was corrected, supplied, deleted or retained and why, within the applicable process. Record who completed the action and any follow-up.'], callout: { label: 'NO ONE-CLICK ASSUMPTION', text: 'A complete response follows the data across every system that holds it.' } },
    ],
    example: { title: 'A customer asks to remove job photos', text: 'The privacy contact verifies the customer and job, checks the TradieRelay record and any connected export, reviews whether the images are still needed for an active dispute, and records the final decision and response.' },
    productVisual: 'dashboard', productCaption: 'The account and job record provide the starting identifiers for a controlled data request, not the whole legal analysis.',
    faqs: [{ question: 'Must every deletion request be granted?', answer: 'Not always. Applicable law and legitimate retention obligations may affect the response; obtain advice.' }, { question: 'Can staff ask for identification?', answer: 'Use proportionate verification and avoid collecting more information than needed.' }, { question: 'Should a correction change the original recording?', answer: 'Usually preserve the source and correct the structured record with an audit note.' }],
    sources: [sources.oaicApp11, sources.oaicApp5], related: ['how-long-keep-call-recordings-customer-photos', 'privacy-notice-ai-receptionist-tradies', 'correct-ai-captured-tradie-job'],
  }),
  makeGuide({
    slug: 'staff-access-security-ai-receptionist', number: 116, category: 'Safety & reliability',
    title: 'How Should Staff Access Be Controlled in an AI Receptionist System?',
    description: 'Least privilege, named accounts, fast offboarding and audit basics for customer calls, photos, prices and routes.',
    directAnswer: 'Give each person a named account and only the access needed for their job. Separate tradie, office and operator controls; use strong authentication; review access regularly; remove it promptly when roles change; and log sensitive actions such as routing, pricing, export and deletion. Shared passwords and permanent ex-staff access are avoidable risks.',
    heroImage: '/blog/116-staff-access-security.webp', heroAlt: 'Australian trade company manager reviewing staff access permissions on a laptop',
    keyPoints: ['Named accounts make actions attributable.', 'Tradie and operator permissions should be separated.', 'Offboarding is part of the access design.'],
    sections: [
      { heading: 'Map roles to real work', bullets: ['Owner: account and commercial control', 'Office: customers, jobs and bookings', 'Technician: assigned job information', 'Estimator: quotes and approved products', 'Operator: setup and support within authorised scope', 'No access: former or unrelated staff'] },
      { heading: 'Use least privilege', paragraphs: ['A technician who only needs assigned jobs should not be able to change business routing or export every customer. An operator who supports configuration should not see more customer information than the task requires.'] },
      { heading: 'Protect high-impact actions', paragraphs: ['Price changes, number routes, access grants, data exports and deletions need stronger authorisation and logging than reading a routine job.'] },
      { heading: 'Build the joiner–mover–leaver loop', paragraphs: ['Grant access from an approved request, update it when responsibilities change and remove it promptly when a person leaves. Check shared devices and provider accounts too.'] },
      { heading: 'Review and test access', paragraphs: ['Quarterly or change-driven reviews should compare actual users with the current team. Test that one customer account cannot see another.'], callout: { label: 'ACCESS TEST', text: 'Right person, right account, right action, right duration.' } },
    ],
    example: { title: 'A technician becomes an estimator', text: 'The owner expands the user’s role to prepare quotes but does not grant account routing or staff-management control. The change is recorded, and the old technician-only permission is replaced rather than layered indefinitely.' },
    productVisual: 'rules', productCaption: 'Routing and pricing controls are high-impact account settings and should be limited to authorised roles.',
    faqs: [{ question: 'Can a small team share one login?', answer: 'Named accounts are safer because permissions and actions remain attributable.' }, { question: 'Should Noah and Jake see every customer call?', answer: 'Only where support duties and customer authorisation require access, under defined operator controls.' }, { question: 'How quickly should ex-staff access be removed?', answer: 'Promptly as part of the offboarding process, including connected providers and shared devices.' }],
    sources: [sources.oaicApp11, sources.aiGuardrails], related: ['is-customer-call-data-safe-ai-receptionist', 'questions-before-buying-ai-receptionist', 'what-operator-console-should-show-ai-receptionist'],
  }),
  makeGuide({
    slug: 'data-breach-response-ai-receptionist', number: 117, category: 'Safety & reliability',
    title: 'What Should Happen If an AI Receptionist Has a Data Breach?',
    description: 'A practical contain, assess, notify and improve process across the trade business, TradieRelay and service providers.',
    directAnswer: 'Contain the incident, preserve evidence, identify the systems, people and data affected, assess likely harm and legal notification obligations, communicate through the approved incident team, restore safely and fix the cause. The response plan should name business and provider responsibilities before an incident and be tested with a realistic scenario.',
    heroImage: '/blog/117-ai-receptionist-data-breach-response.webp', heroAlt: 'Australian small-business owners and technology operator responding to a customer data incident',
    keyPoints: ['Contain first without destroying evidence.', 'Know which business and provider owns each response action.', 'Test the plan before a real incident.'],
    sections: [
      { heading: 'Activate the response owner', paragraphs: ['The person discovering the issue should know who coordinates containment, legal and privacy assessment, customer communication, technical recovery and business continuity.'] },
      { heading: 'Contain and preserve evidence', bullets: ['Disable compromised access', 'Protect unaffected accounts', 'Preserve relevant logs', 'Stop unsafe integrations or exports', 'Record decisions and times', 'Use the approved fallback for live calls'] },
      { heading: 'Assess the incident', paragraphs: ['Identify the personal information, customers, accounts, providers and period involved. Consider whether serious harm is likely and whether the Notifiable Data Breaches scheme or other obligations apply. Obtain advice.'] },
      { heading: 'Communicate accurately', paragraphs: ['Tell affected customers and authorities when required, using confirmed facts, protective steps and a contact route. Avoid speculation or minimising the impact.'] },
      { heading: 'Recover and learn', paragraphs: ['Restore from a known safe state, test account isolation and routing, update controls and rehearse the changed plan.'], callout: { label: 'INCIDENT LOOP', text: 'Contain → assess → notify where required → restore → learn.' } },
    ],
    example: { title: 'An operator account is compromised', text: 'The team disables the account, checks which tenants and records were accessed, preserves logs, rotates relevant credentials, engages privacy advice and follows the notification assessment. Customer call fallback remains active while affected admin access is paused.' },
    productVisual: 'dashboard', productCaption: 'Account and job identifiers help scope an incident, while provider logs and formal response records complete the evidence.',
    faqs: [{ question: 'Does every breach require customer notification?', answer: 'Not every incident does. The NDB scheme and other obligations depend on the circumstances and likely serious harm; obtain advice.' }, { question: 'Who is responsible—the tradie or the software provider?', answer: 'Responsibilities depend on the data flow, contracts and law. Define operational roles before an incident.' }, { question: 'Should the system stay live?', answer: 'Pause affected functions when needed and use the tested call or message fallback while risk is assessed.' }],
    sources: [sources.oaicBreach, sources.oaicApp11], related: ['is-customer-call-data-safe-ai-receptionist', 'staff-access-security-ai-receptionist', 'what-if-ai-receptionist-service-goes-down'],
  }),
  makeGuide({
    slug: 'when-pause-ai-receptionist-automation', number: 118, category: 'Safety & reliability',
    title: 'When Should a Tradie Pause AI Receptionist Automation?',
    description: 'The failures, business changes and customer signals that should switch a workflow back to message capture or human handling.',
    directAnswer: 'Pause the affected workflow when safety or emergency wording fails, calls or data reach the wrong account, urgent routing is unreliable, customer promises are false, a provider or integration is unstable, privacy or security is uncertain, or staff cannot own the resulting queue. Use the documented fallback, investigate and repeat the acceptance test before resuming.',
    heroImage: '/blog/118-pause-ai-automation.webp', heroAlt: 'Australian trade business owner switching a phone workflow to manual fallback during review',
    keyPoints: ['Pause the broken path, not necessarily the whole service.', 'A fallback must already exist and be understood.', 'Resume only after the exact failure passes retest.'],
    sections: [
      { heading: 'Use non-negotiable stop conditions', bullets: ['Wrong business greeting or account', 'Emergency path failure', 'Urgent route failure', 'Invented price or booking promise', 'Customer data exposure', 'Repeated unusable call experience'] },
      { heading: 'Pause for operational mismatch', paragraphs: ['A roster change, closed service area, holiday shutdown, full capacity or provider migration can make yesterday’s correct rules wrong today. Update the workflow before continuing.'] },
      { heading: 'Switch to the tested fallback', paragraphs: ['Depending on the failure, use message capture, voicemail, the original number, a human line or a narrowed answer condition. Tell callers only what the fallback can actually do.'] },
      { heading: 'Investigate with evidence', paragraphs: ['Keep the failed call, logs, configuration revision and customer impact. Identify whether the problem occurred in carrier forwarding, voice, AI, routing, messaging, account data or human response.'] },
      { heading: 'Retest before resuming', paragraphs: ['Correct the cause, run the exact failed case plus a normal case and record the pass. Do not resume because the provider dashboard looks green.'], callout: { label: 'RESUME GATE', text: 'Cause fixed + failure retested + fallback removed deliberately + owner informed.' } },
    ],
    example: { title: 'Urgent alerts reach an old number', text: 'The business pauses the urgent automation and uses message capture plus the office line. The operator corrects the roster, repeats urgent and normal test calls, confirms the primary and backup, then re-enables the route.' },
    productVisual: 'rules', productCaption: 'Visible answer mode, fallback and urgent routes make it possible to narrow or pause one affected workflow safely.',
    faqs: [{ question: 'Does pausing mean losing the business number?', answer: 'No. Phone-provider routing can be narrowed or disabled while the original number remains the customer entry point.' }, { question: 'Who can pause the workflow?', answer: 'The authorised business or operator role defined in the incident and change process.' }, { question: 'Should a customer complaint pause automation?', answer: 'Investigate the impact and pattern. A serious control failure should pause the affected path; ordinary feedback may lead to a tested improvement.' }],
    sources: [sources.aiGuardrails, sources.oaicBreach], related: ['what-if-ai-receptionist-service-goes-down', 'test-ai-receptionist-before-going-live', 'fortnightly-ai-receptionist-optimisation-review'],
  }),
];
