import { makeGuide, sources } from './shared';

export const teamOperationsGuides = [
  makeGuide({
    slug: 'who-owns-recovered-tradie-lead', number: 91, category: 'Team & operations',
    title: 'Who Should Own a Recovered Tradie Lead?',
    description: 'Why every captured job needs one named owner, a response time and a fallback instead of another shared inbox.',
    directAnswer: 'Assign one person to the next action based on job type, territory or shift. Give them a response expectation and name a fallback for absence or failed notification. Others may see the lead, but shared visibility is not shared ownership: one person must call, quote, book, ask or decline.',
    heroImage: '/blog/91-owner-recovered-tradie-lead.webp', heroAlt: 'Australian trade business owner assigning a new lead to one coordinator in a morning meeting',
    keyPoints: ['One lead has one next-action owner.', 'Visibility and ownership are different.', 'Fallback activates on absence or delivery failure.'],
    sections: [
      { heading: 'Define the decision, not just the recipient', paragraphs: ['The owner is responsible for the next outcome: review and call, prepare the quote, confirm the time or decide fit. Sending an SMS to somebody is not enough.'] },
      { heading: 'Use rules the team already understands', bullets: ['Routine service by territory', 'Projects to estimator', 'Existing bookings to office', 'Approved urgent indicators to on-call person', 'Unclear or excluded work to owner review'] },
      { heading: 'Set the response expectation', paragraphs: ['Urgent review, same-day new lead and next-morning after-hours work may need different targets. Choose promises the actual roster can support.'] },
      { heading: 'Make fallback visible', paragraphs: ['A backup can receive urgent copies or delivery-failure notifications. For normal work, an overdue review list can prompt the office or owner without notifying the whole crew.'] },
      { heading: 'Track outcomes, not notification volume', paragraphs: ['Measure whether the lead was reviewed and what happened. More alerts are not evidence of better response.'], callout: { label: 'OWNERSHIP TEST', text: 'If two people both think the other person will call, the lead has no owner.' } },
    ],
    example: { title: 'One service lead, one owner', text: 'A routine plumbing lead in Robina routes to Mia, the service coordinator. Lee sees urgent copies only. If the primary SMS fails, the backup receives the delivery fallback. Mia remains responsible for the next status.' },
    productVisual: 'pipeline', productCaption: 'The action pipeline shows which jobs need a person and stops notification from being mistaken for completion.',
    faqs: [{ question: 'Can two people receive the same lead?', answer: 'They can, especially for urgent backup, but one person should own the next action.' }, { question: 'Should the business owner own every lead?', answer: 'Only if that matches the operation. A coordinator or estimator may be the better owner.' }, { question: 'What if the owner is on leave?', answer: 'Update the route or roster before calls arrive and test the fallback.' }],
    related: ['route-different-calls-to-different-staff', 'how-small-trade-business-handle-several-calls', 'what-happens-after-tradie-misses-call'],
  }),
  makeGuide({
    slug: 'update-on-call-roster-ai-receptionist', number: 92, category: 'Team & operations',
    title: 'How Do You Keep an AI Receptionist’s On-Call Roster Current?',
    description: 'A simple ownership, change and test process for urgent routes when staff rotate, take leave or swap weekends.',
    directAnswer: 'Keep one approved roster source, name the person allowed to change it, set an effective date and time, preserve the previous route for audit, and make a test call after every material change. A roster entry should include primary, backup and no-answer behaviour—not only a mobile number.',
    heroImage: '/blog/92-on-call-roster-update.webp', heroAlt: 'Australian electrical crew updating the weekend on-call roster in a workshop',
    keyPoints: ['One roster is the source of truth.', 'Every change has an effective time and owner.', 'A route change is not complete until it is tested.'],
    sections: [
      { heading: 'Choose where the roster lives', paragraphs: ['Use the existing roster habit rather than creating a separate secret list. The operator configuration should follow that approved source and record who changed the route.'] },
      { heading: 'Include the whole urgent path', bullets: ['Primary on-call person', 'Backup person', 'Effective start and end', 'Which job indicators alert them', 'No-answer or failed-delivery action', 'Escalation and emergency wording'] },
      { heading: 'Control last-minute swaps', paragraphs: ['A staff text saying “can you cover?” is not enough. The authorised person updates the route, confirms both people and records the time the change takes effect.'] },
      { heading: 'Test from the outside', paragraphs: ['Make a real test call using the urgent scenario and confirm the correct account, primary and backup receive the expected information. Remove or label test data afterwards.'] },
      { heading: 'Review every failed route', paragraphs: ['A missed urgent notification is a control failure, not a coaching note. Correct the route, repeat the test and record the evidence before relying on it.'], callout: { label: 'CHANGE GATE', text: 'Roster updated + people confirmed + route tested.' } },
    ],
    example: { title: 'A weekend swap', text: 'Noah changes Saturday coverage from Jake to Mia at 4 pm Friday, keeps Lee as backup and makes the urgent test call. The alert reaches Mia with the correct business and job context before the old route is considered retired.' },
    productVisual: 'rules', productCaption: 'The operator console provides a visible home for the primary, backup and urgent-routing configuration.',
    faqs: [{ question: 'Can staff change the route themselves?', answer: 'Only people with the approved operator access should change account routing.' }, { question: 'Should the previous number be deleted?', answer: 'Remove it from the active route but preserve the change record for audit.' }, { question: 'What if nobody is available?', answer: 'Use the approved message and callback fallback; do not promise a live transfer.' }],
    sources: [sources.aiGuardrails], related: ['ai-receptionist-transfer-urgent-calls', 'route-different-calls-to-different-staff', 'test-ai-receptionist-before-going-live'],
  }),
  makeGuide({
    slug: 'handover-open-leads-between-tradie-shifts', number: 93, category: 'Team & operations',
    title: 'How Should Tradies Hand Over Open Leads Between Shifts?',
    description: 'A five-minute handover based on jobs that need action, promised callbacks and unresolved customer evidence.',
    directAnswer: 'Handover should cover only open commitments: urgent reviews, overdue callbacks, quote decisions, requested times, missing evidence and customer issues. Update each job’s status and next owner before the shift ends. Do not rely on a group-chat summary that separates the promise from the job record.',
    heroImage: '/blog/93-tradie-shift-handover.webp', heroAlt: 'Australian morning and afternoon trade supervisors handing over open customer jobs',
    keyPoints: ['Handover commitments, not every call.', 'Change the owner on the job record.', 'State what the customer was promised and by when.'],
    sections: [
      { heading: 'Start with “Needs you”', paragraphs: ['Review jobs that require a human decision before reading completed or waiting items. The handover is a risk-control moment, not a full activity report.'] },
      { heading: 'Use six fields for every open item', bullets: ['Customer and job', 'Current status', 'What was promised', 'Due time', 'Next action', 'New owner'] },
      { heading: 'Resolve ambiguous ownership', paragraphs: ['If a job crosses service, quote and booking work, decide who owns the next immediate action. The next owner can reassign after closing that commitment.'] },
      { heading: 'Keep evidence with the record', paragraphs: ['Photos, caller corrections, quote views and delivery failures should be attached to the job. The handover note can point to them instead of copying them into another channel.'] },
      { heading: 'Finish with a verbal exception check', paragraphs: ['Ask whether any promise was made outside the system. Add it to the record before the person leaves.'], callout: { label: 'FIVE-MINUTE HANDOVER', text: 'Open promise + due time + next owner. Everything else can wait.' } },
    ],
    example: { title: 'Friday afternoon to weekend cover', text: 'The outgoing coordinator hands over one urgent review, two Saturday time requests and a quote question. Each job shows the customer promise and weekend owner; no one needs to reconstruct it from messages.' },
    productVisual: 'pipeline', productCaption: 'Needs-you, waiting and booked states make a short exception-based handover possible.',
    faqs: [{ question: 'Should completed jobs be discussed?', answer: 'Only if they create a new risk or follow-up. Focus on open commitments.' }, { question: 'Can a shared inbox replace handover?', answer: 'Not when ownership and due time are unclear.' }, { question: 'Who runs the handover?', answer: 'The person giving up responsibility should confirm the new owner accepts it.' }],
    related: ['who-owns-recovered-tradie-lead', 'how-small-trade-business-handle-several-calls', 'route-different-calls-to-different-staff'],
  }),
  makeGuide({
    slug: 'route-tradie-leads-by-suburb-territory', number: 94, category: 'Team & operations',
    title: 'Can TradieRelay Route Leads by Suburb or Territory?',
    description: 'How to build simple, reviewable service zones with boundary and backup rules for small trade teams.',
    directAnswer: 'Yes. A trade business can map suburbs or postcodes to a primary person or crew, then add job-type, urgency and fallback rules. Keep zones simple, define boundary suburbs and send unclear locations to human review. The route should not promise attendance merely because the address falls inside a territory.',
    heroImage: '/blog/94-route-leads-by-territory.webp', heroAlt: 'Australian trade dispatcher mapping Gold Coast suburbs to service crews',
    keyPoints: ['Use stable service zones the team already knows.', 'Boundary and missing-address cases need a fallback.', 'Territory selects an owner, not a guaranteed booking.'],
    sections: [
      { heading: 'Start with the current run', paragraphs: ['Translate the team’s real northern, central, southern or specialist coverage into a short mapping. Avoid a complex postcode engine when five suburb groups describe the work.'] },
      { heading: 'Decide what happens at the edge', paragraphs: ['List the boundary suburbs, nearby out-of-area work and addresses that need review. A typo or new estate should not silently go to the wrong crew.'] },
      { heading: 'Layer only the rules that matter', bullets: ['Trade or job type', 'Normal or approved urgent indicator', 'Customer type', 'Primary territory owner', 'Backup or delivery fallback', 'Human review for uncertainty'] },
      { heading: 'Check route versus capacity', paragraphs: ['Territory ownership does not prove that the technician is free. It tells the system who should review or receive the lead; booking remains separate.'] },
      { heading: 'Review misroutes fortnightly', paragraphs: ['Use actual corrected jobs to improve the map. Change the zone only when the business process has changed, not for one unusual request.'], callout: { label: 'ROUTE MEANING', text: 'Inside territory means “send to this owner”, not “we will attend”.' } },
    ],
    example: { title: 'North and south service crews', text: 'Southport and Labrador route to the north crew; Robina and Burleigh route to the south crew. A new suburb at the boundary enters owner review until the map is approved.' },
    productVisual: 'rules', productCaption: 'Territory rules belong in the visible account configuration where they can be explained, tested and changed.',
    faqs: [{ question: 'Can a suburb route to more than one person?', answer: 'A primary and fallback can be configured, while keeping one next-action owner.' }, { question: 'Can out-of-area calls be declined automatically?', answer: 'They can receive approved polite wording when the location is certain; boundary cases should be reviewed.' }, { question: 'Does territory routing use live GPS?', answer: 'Not by default. It applies the configured suburb or area rule.' }],
    related: ['route-different-calls-to-different-staff', 'route-different-job-types-right-person', 'allow-travel-time-in-tradie-bookings'],
  }),
  makeGuide({
    slug: 'route-tradie-leads-by-job-type', number: 95, category: 'Team & operations',
    title: 'How Do You Route Tradie Leads by Job Type?',
    description: 'A plain-English method for sending service, project, maintenance and existing-customer work to the right person.',
    directAnswer: 'Create a small list of job lanes that match how the business works, define the caller observations that place a job in each lane, name the owner and fallback, and keep uncertain work in review. Avoid dozens of labels and never let a job-type rule make a technical diagnosis.',
    heroImage: '/blog/95-route-leads-by-job-type.webp', heroAlt: 'Australian trade team sorting service project maintenance and quote leads on a planning board',
    keyPoints: ['Use the team’s real operating lanes.', 'Classification uses caller facts, not technical conclusions.', 'Every lane has an owner and exception path.'],
    sections: [
      { heading: 'Create four to six useful lanes', paragraphs: ['Common lanes include routine service, urgent review, project quote, recurring maintenance, existing booking and accounts or supplier. Add one only when it changes the person or next action.'] },
      { heading: 'Define entry in caller language', paragraphs: ['“Wants a new ducted system quote” is a useful project signal. “Compressor failure” is a diagnosis the caller or AI may not be qualified to make.'] },
      { heading: 'Name the route and fallback', bullets: ['Primary owner', 'Backup or office review', 'Expected response', 'Customer wording', 'Required evidence', 'Excluded or uncertain path'] },
      { heading: 'Test overlapping jobs', paragraphs: ['A customer may have an existing booking and request new work, or report urgent damage during a quote call. Decide which immediate action takes priority while preserving both needs.'] },
      { heading: 'Remove labels nobody uses', paragraphs: ['If two categories always go to the same person with the same questions and next step, combine them. Simpler rules are easier to trust.'], callout: { label: 'LABEL TEST', text: 'A category earns its place only when it changes a question, owner or outcome.' } },
    ],
    example: { title: 'Service work and renovation quotes', text: 'A plumbing business sends leaking taps and blocked fixtures to the service coordinator, bathroom renovations to the estimator and existing-job issues to the office. “Not sure” enters owner review.' },
    productVisual: 'pipeline', productCaption: 'The pipeline keeps different job lanes visible after routing so the owner can correct a wrong classification.',
    faqs: [{ question: 'How many job types should we start with?', answer: 'Usually four to six operating lanes are enough for the first setup.' }, { question: 'Can one job have two labels?', answer: 'It can carry context, but one next action should have one owner.' }, { question: 'Can staff correct the job type?', answer: 'Yes. Human correction is part of the reviewable workflow.' }],
    related: ['route-different-job-types-right-person', 'route-different-calls-to-different-staff', 'how-tradie-set-call-answering-rules'],
  }),
  makeGuide({
    slug: 'ai-receptionist-multiple-branches-numbers', number: 96, category: 'Team & operations',
    title: 'Can an AI Receptionist Support Multiple Branches or Phone Numbers?',
    description: 'How to keep brand, number, territory, greeting and data separate when one trade business has more than one route.',
    directAnswer: 'Yes, when each incoming number or branch is mapped to the correct business identity, service area, questions, staff, data account and fallback. The caller must hear the right business name, and every job must land in the correct tenant. Start with one branch and add the next only after cross-account isolation and routing tests pass.',
    heroImage: '/blog/96-multiple-branches-phone-numbers.webp', heroAlt: 'Australian multi-branch trade managers comparing phone routes and service territories',
    keyPoints: ['The incoming number must select the correct business context.', 'Jobs and photos cannot leak across accounts.', 'Expand branch by branch after isolation tests.'],
    sections: [
      { heading: 'Map the incoming identity', paragraphs: ['Record which published number, campaign or branch line reached the service. That route selects the greeting, service area, staff and account before job questions begin.'] },
      { heading: 'Keep tenant data isolated', paragraphs: ['The customer, job, photo, quote and message belong only to the selected business account. Test similar customer names and simultaneous calls across branches.'] },
      { heading: 'Allow real branch differences', bullets: ['Trading name and greeting', 'Hours and after-hours promise', 'Service suburbs', 'Job types and exclusions', 'Primary and backup staff', 'Products, prices and quote process'] },
      { heading: 'Use a central exception route carefully', paragraphs: ['Head office may review unclear branch calls, but it should see only the information authorised for that role. A central fallback is not permission for broad account access.'] },
      { heading: 'Test one branch at a time', paragraphs: ['Pass normal, urgent, photo, quote, opt-out and failure scenarios in branch A before copying the design. Repeat them in branch B with distinct test data.'], callout: { label: 'ISOLATION GATE', text: 'Wrong greeting or wrong account is a launch-stopping failure.' } },
    ],
    example: { title: 'Gold Coast and Brisbane branches', text: 'The Gold Coast number uses Gold Coast suburbs and staff; the Brisbane number uses Brisbane rules. Two test customers with the same surname remain in separate accounts with the correct photos and alerts.' },
    productVisual: 'dashboard', productCaption: 'The dashboard context must clearly identify the current business account before an operator reviews or changes data.',
    faqs: [{ question: 'Can both branches use one greeting?', answer: 'They can share a structure, but the business identity and local expectation must remain accurate.' }, { question: 'Can head office see every branch?', answer: 'Only if the product role and business authorisation deliberately allow it.' }, { question: 'Should all branches launch together?', answer: 'No. Prove one branch, then repeat the acceptance test for each additional branch.' }],
    sources: [sources.oaicApp11, sources.aiGuardrails], related: ['route-different-calls-to-different-staff', 'test-ai-receptionist-before-going-live', 'is-customer-call-data-safe-ai-receptionist'],
  }),
  makeGuide({
    slug: 'connect-ai-receptionist-job-management-software', number: 97, category: 'Team & operations',
    title: 'Can TradieRelay Connect to Job-Management Software?',
    description: 'What a safe integration should send, who owns each field and why “integration available” is not the same as connected today.',
    directAnswer: 'It can connect where the job-management platform offers a suitable API or supported workflow and the customer setup is built and tested. Define exactly which records and fields move, which system owns updates, how duplicates are matched and what happens on failure. TradieRelay’s working core operates in its own dashboard; a specific external integration must be confirmed before it is sold as live.',
    heroImage: '/blog/97-job-management-integration.webp', heroAlt: 'Australian trade operations manager mapping job fields between two software systems',
    keyPoints: ['Name the exact platform, objects and direction.', 'Choose the source of truth for every shared field.', 'Failed syncs must create a visible retry or review task.'],
    sections: [
      { heading: 'Start with the work you want to delete', paragraphs: ['A good first integration removes retyping of customer and job basics. Do not connect every field because the API allows it.'] },
      { heading: 'Map the minimum record', bullets: ['Customer name and contact', 'Service address', 'Job type and description', 'Urgency label as reported', 'Source and call reference', 'Photo link or attachment capability', 'Current owner and status'] },
      { heading: 'Assign a source of truth', paragraphs: ['If staff change the address, status or booking in two systems, decide which update wins and whether it syncs both ways. Ambiguous ownership creates silent data loss.'] },
      { heading: 'Design duplicate and failure handling', paragraphs: ['Use stable identifiers, show uncertain matches and record rejected writes. A failed sync must not tell the customer that the job was created in the field system.'] },
      { heading: 'Describe the current scope precisely', paragraphs: ['TradieRelay’s own jobs, photos, quotes, products and rules are working. External job-management integration is customer- and vendor-specific until the exact connection has passed.'], callout: { label: 'SALES WORDING', text: '“Can integrate after scoped setup” is not “already integrated”.' } },
    ],
    example: { title: 'Removing double entry', text: 'After qualification, the approved integration creates a draft job with the customer, address, summary and source reference. The dispatcher checks it before scheduling. If the external API rejects the record, TradieRelay shows a sync review task.' },
    productVisual: 'dashboard', productCaption: 'TradieRelay’s working dashboard remains the current reviewable record; external sync scope is confirmed per customer.',
    faqs: [{ question: 'Which job-management systems are already connected?', answer: 'Confirm the current integration list with TradieRelay. Do not assume a vendor is live from a generic “integrates with” statement.' }, { question: 'Can photos be synced?', answer: 'Only if the destination API supports the required attachment or secure-link method.' }, { question: 'What happens if the sync fails?', answer: 'The lead should remain visible in TradieRelay with a retry or human-review status.' }],
    sources: [sources.oaicApp11, sources.aiGuardrails], related: ['what-ai-receptionist-pricing-should-include', 'questions-before-buying-ai-receptionist', 'what-if-ai-receptionist-service-goes-down'],
  }),
  makeGuide({
    slug: 'correct-ai-captured-tradie-job', number: 98, category: 'Team & operations',
    title: 'How Should Staff Correct an AI-Captured Job?',
    description: 'A fast review process for names, numbers, suburbs, job types and summaries without hiding what the caller originally said.',
    directAnswer: 'Show the captured value and source, let an authorised user correct it, preserve the original interaction for audit, record who changed what, and make downstream notifications or integrations use the corrected value. High-consequence fields such as address, callback number, urgency and price should require deliberate review.',
    heroImage: '/blog/98-correct-ai-captured-job.webp', heroAlt: 'Australian trade coordinator correcting a suburb and phone number in a customer job record',
    keyPoints: ['Correction should be easy and traceable.', 'Preserve the source interaction instead of rewriting history.', 'Corrected facts must flow to later actions.'],
    sections: [
      { heading: 'Prioritise decision-changing fields', bullets: ['Customer name', 'Callback number', 'Service address or suburb', 'Job type', 'Urgency indicators', 'Requested time', 'Scope and price items'] },
      { heading: 'Compare with the source', paragraphs: ['Use the call audio or transcript, customer reply and photo where available. If the source is still uncertain, ask the customer rather than choosing the most likely spelling.'] },
      { heading: 'Record the correction', paragraphs: ['Keep the original value, corrected value, editor and time. This helps explain a route change and improve future recognition without hiding the mistake.'] },
      { heading: 'Update the workflow safely', paragraphs: ['A changed suburb may alter territory; a changed job type may alter owner; a corrected number affects messages. Show the operator which downstream action will change before re-sending.'] },
      { heading: 'Feed patterns into optimisation', paragraphs: ['Repeated errors in a suburb, supplier or trade term should improve the call vocabulary or confirmation question. One-off corrections should not create a sweeping rule.'], callout: { label: 'REVIEW PRINCIPLE', text: 'Correct the record, preserve the source, then fix the pattern.' } },
    ],
    example: { title: '“Currumbin” becomes “Carrara”', text: 'The transcript is unclear, but the customer’s SMS confirms Carrara. The coordinator corrects the suburb, the route changes to the central crew and the audit record keeps the original capture and source.' },
    productVisual: 'lead', productCaption: 'The working job view presents captured details for human review instead of treating AI extraction as unquestionable.',
    faqs: [{ question: 'Should staff edit the transcript?', answer: 'Preserve source evidence. Correct the structured job fields and note the supporting evidence.' }, { question: 'Can a correction resend an alert?', answer: 'It can when the route changed, but the system should prevent accidental duplicate notifications.' }, { question: 'Who may correct prices?', answer: 'Only authorised account users under the business’s pricing controls.' }],
    sources: [sources.aiGuardrails], related: ['what-happens-when-ai-does-not-know-answer', 'test-ai-receptionist-before-going-live', 'how-tradie-set-call-answering-rules'],
  }),
  makeGuide({
    slug: 'what-operator-console-should-show-ai-receptionist', number: 99, category: 'Team & operations',
    title: 'What Should an AI Receptionist Operator Console Show?',
    description: 'The minimum information Noah and Jake need to set up, support and explain each tradie account with confidence.',
    directAnswer: 'The operator console should show account status, number and provider setup, approved greeting, answer mode, service area, job questions, urgency and fallback rules, staff routes, products and prices, test evidence, failures, changes and optimisation notes. Operators need to see what is live, what requires setup and who approved it.',
    heroImage: '/blog/99-ai-operator-console.webp', heroAlt: 'Two young Australian software operators reviewing a trade customer call configuration console',
    keyPoints: ['Live, planned and unavailable features must look different.', 'Every rule needs an owner, approval and test.', 'Support history should stay with the customer account.'],
    sections: [
      { heading: 'Show the service identity', bullets: ['Business and account', 'Published and Relay numbers', 'Provider and forwarding state', 'Plan and usage', 'Primary owner and support contact', 'Go-live status'] },
      { heading: 'Make call behaviour explainable', paragraphs: ['An operator should be able to answer what the caller hears, which questions are asked, what counts as urgent, what is never promised and where every outcome goes.'] },
      { heading: 'Separate live from setup-dependent', paragraphs: ['Urgent alerts may be live while transfer is not; preferred-time capture may be live while direct calendar booking is not. The console must make that boundary visible.'] },
      { heading: 'Keep test and change evidence', paragraphs: ['Store the acceptance scenarios, result, date, tester and configuration revision. A successful call from six months ago is not proof after a provider or roster change.'] },
      { heading: 'Teach the operator inside the workflow', paragraphs: ['A call-routing and technical-architecture tab should explain the sequence, providers, failure modes, privacy boundaries and customer setup tasks in plain English.'], callout: { label: 'OPERATOR STANDARD', text: 'Noah and Jake should be able to explain a feature by showing its rule and test—not by guessing.' } },
    ],
    example: { title: 'Explaining urgent transfer', text: 'The console shows urgent SMS alert as active, backup delivery as active and live transfer as “setup required”. Noah can explain the current behaviour and the exact provider and roster test needed before transfer is offered.' },
    productVisual: 'rules', productCaption: 'The actual TradieRelay operator console includes call-flow and growth-plan guidance alongside tenant configuration.',
    faqs: [{ question: 'Should tradies see the operator console?', answer: 'They should see and approve their own rules through the appropriate account view; internal provider and support controls can remain operator-only.' }, { question: 'What does “setup required” mean?', answer: 'The feature is possible but is not active until the named integration, route and acceptance test are complete.' }, { question: 'Who approves changes?', answer: 'The account owner or authorised business contact should approve customer-facing and routing changes.' }],
    sources: [sources.aiGuardrails], related: ['how-tradie-set-call-answering-rules', 'test-ai-receptionist-before-going-live', 'questions-before-buying-ai-receptionist'],
  }),
  makeGuide({
    slug: 'fortnightly-ai-receptionist-optimisation-review', number: 100, category: 'Team & operations',
    title: 'What Happens in a Fortnightly AI Receptionist Optimisation Review?',
    description: 'A 30-minute review of caller friction, wrong routes, missed promises and business outcomes—not a meeting about AI buzzwords.',
    directAnswer: 'Review the calls that failed, confused callers, required corrections, triggered the wrong route, missed a customer promise or produced no useful outcome. Compare them with successful calls, choose one or two rule or wording changes, assign owners, retest and record the result. Do not change many variables at once.',
    heroImage: '/blog/100-fortnightly-optimisation-review.webp', heroAlt: 'Australian tradie and TradieRelay founders reviewing call outcomes around a workshop table',
    keyPoints: ['Review exceptions before averages.', 'Change one or two things with an expected outcome.', 'Retest the exact failed scenario.'],
    sections: [
      { heading: 'Bring the evidence', bullets: ['Failed or dropped calls', 'Unclear or corrected fields', 'Wrong routes', 'Alert delivery failures', 'Customer opt-outs or complaints', 'Lead, booking and quote outcomes'] },
      { heading: 'Listen to the customer friction', paragraphs: ['Look for repeated questions, long introductions, confusing status language and places people ask for a human. The fastest improvement is often removing a question or making the next step clearer.'] },
      { heading: 'Check business behaviour too', paragraphs: ['A good call can still fail if nobody reviews the lead. Separate system capture, routing, notification and human response so the right problem is fixed.'] },
      { heading: 'Make a controlled change', paragraphs: ['State the rule or wording change, expected result, owner and test. Avoid rewriting every script because one unusual caller had difficulty.'] },
      { heading: 'Close the loop next review', paragraphs: ['Bring back the changed scenarios and outcome. Keep, adjust or reverse the change. Remove features that add work without improving customer or business results.'], callout: { label: 'REVIEW OUTPUT', text: 'Evidence → one change → owner → retest → result.' } },
    ],
    example: { title: 'Too many callers repeat the suburb', text: 'The review finds the assistant asks for the suburb after it was already confirmed. Jake removes the duplicate question, retests three call types and checks the next fortnight for shorter calls and unchanged routing accuracy.' },
    productVisual: 'dashboard', productCaption: 'The dashboard and operator evidence make the review about actual calls, routes and outcomes.',
    faqs: [{ question: 'Should every account be reviewed fortnightly forever?', answer: 'Frequent review is useful during launch. Stable accounts can move to an agreed rhythm based on volume and change.' }, { question: 'What if the problem is slow human response?', answer: 'Fix ownership and response process rather than changing the call script.' }, { question: 'How many changes should be made?', answer: 'Usually one or two measurable changes per review are easier to test and learn from.' }],
    sources: [sources.aiGuardrails], related: ['test-ai-receptionist-before-going-live', 'how-tradie-set-call-answering-rules', 'measure-quote-follow-up-winning-more-jobs'],
  }),
];
