import { makeGuide, sources } from './shared';

export const tradePlaybookGuides = [
  makeGuide({
    slug: 'ai-receptionist-plumbing-call-flow', number: 61, category: 'Trade call playbooks',
    title: 'How Should an AI Receptionist Handle Plumbing Calls?',
    description: 'A plumbing-specific call flow for leaks, blockages, hot water, maintenance and quote requests—without remote diagnosis or false attendance promises.',
    directAnswer: 'A plumbing call flow should first identify the caller, property and affected fixture, then capture what the caller can see, whether water is still flowing, access details and preferred timing. It can mark approved urgency indicators and request photos, but a plumber must decide the diagnosis, safety advice, price and attendance.',
    heroImage: '/blog/61-plumbing-call-playbook.webp', heroAlt: 'Australian plumber reviewing a customer call beside a residential hot-water system',
    keyPoints: ['Capture the visible problem and water status—not a guessed diagnosis.', 'Separate urgent service calls from maintenance and quote work.', 'Keep photos, access notes and the human decision on one job.'],
    sections: [
      { heading: 'Start with the property and affected fixture', paragraphs: ['Ask where the work is, whether it is a house, unit, commercial site or managed property, and which fixture or area is affected. That gives the plumber a usable starting point without turning the caller into a technician.'] },
      { heading: 'Ask what the caller can see', paragraphs: ['Plain observations such as “water is coming through the ceiling” or “the toilet is backing up” are more dependable than asking the caller to name the fault. Record their words and avoid rewriting them as a confirmed cause.'] },
      { heading: 'Use approved urgency indicators', paragraphs: ['The business defines which reported conditions trigger an urgent alert and what emergency wording the caller hears. The assistant applies that rule; it does not certify that the site is safe or promise a plumber will attend.'], callout: { label: 'BOUNDARY', text: 'Urgent classification is a routing signal for the plumber, not a remote plumbing diagnosis.' } },
      { heading: 'Request the evidence that changes the callback', bullets: ['Photo of the affected area from a safe position', 'Hot-water unit make or model when visible', 'Body-corporate, tenant or owner contact', 'Parking, gate and access notes', 'Best callback time and who will be on site'] },
      { heading: 'End with one clear next step', paragraphs: ['Tell the caller that the plumber will review the details and call back, or use another approved outcome. Do not imply that submitting a photo creates a booking. The dashboard should show the summary, urgency, photo and requested action together.'] },
    ],
    example: { title: 'A ceiling leak in Robina', text: 'Mia reports water staining and an active drip below an upstairs bathroom. The assistant captures the address, visible issue, whether water is still flowing, access and two photos. It marks the approved urgent indicators and alerts the nominated plumber, who decides the next action. Fictional demo data is used.' },
    productVisual: 'photo-request', productCaption: 'The working photo flow links customer evidence to the same plumbing enquiry; the plumber still reviews and decides.',
    table: { headers: ['Call type', 'Useful capture', 'Human decision'], rows: [['Leak', 'Location, visible flow, affected area, photos', 'Urgency and attendance'], ['Blockage', 'Affected fixtures, property type, access', 'Likely work and equipment'], ['Hot water', 'Unit type/model if visible, symptom', 'Diagnosis and parts'], ['Quote', 'Scope, suburb, timing, photos', 'Site visit and price']] },
    faqs: [{ question: 'Can the AI tell a caller how to stop a leak?', answer: 'Only approved general wording may be used. It should not improvise plumbing or safety instructions.' }, { question: 'Can it price a blocked drain?', answer: 'Only if the business has approved a specific saved fee and the conditions for using it. Otherwise it captures the job for review.' }, { question: 'Do plumbing photos appear in the dashboard?', answer: 'Yes. Photos submitted through the enabled secure link attach to the same job record.' }],
    sources: [sources.aiStandard], related: ['questions-ai-receptionist-ask-plumbing-caller', 'customer-photos-help-qualify-trade-job', 'urgent-jobs-vs-emergency-jobs'],
  }),
  makeGuide({
    slug: 'ai-receptionist-electrical-call-flow', number: 62, category: 'Trade call playbooks',
    title: 'How Should an AI Receptionist Handle Electrical Calls?',
    description: 'A controlled electrical intake flow that captures faults, installations and quote requests while keeping diagnosis and safety decisions with a licensed person.',
    directAnswer: 'An electrical call flow should capture the property, affected area, what the caller has observed, whether the issue affects all or part of the site, access and callback availability. It may apply electrician-approved urgency wording, but it must never diagnose a fault, direct electrical work or declare the site safe.',
    heroImage: '/blog/62-electrical-call-playbook.webp', heroAlt: 'Australian electrician receiving a structured customer enquiry beside a residential switchboard',
    keyPoints: ['Record observations, not an AI diagnosis.', 'Separate fault calls from planned installation and quote work.', 'Escalate only against rules approved by the electrical business.'],
    sections: [
      { heading: 'Identify the site and call purpose', paragraphs: ['Start with the caller, suburb, property type and whether this is a new fault, planned installation, inspection, quote or existing booking. Commercial and managed-property calls may also need an authorised contact or purchase-order process.'] },
      { heading: 'Capture symptoms in the caller’s own words', paragraphs: ['Ask what has happened and which area is affected. Do not convert “lights flickered” into a failed component. The electrician needs a faithful summary and a route to the caller, not a confident guess.'] },
      { heading: 'Keep safety and emergency language controlled', paragraphs: ['Use only the emergency and urgent wording supplied by the licensed business. If the caller describes an immediate threat, the assistant should use the approved emergency path rather than extending the intake conversation.'], callout: { label: 'NO REMOTE DIAGNOSIS', text: 'The assistant captures reported facts; a licensed electrician determines the fault and response.' } },
      { heading: 'Collect practical callback details', bullets: ['Whether the issue affects the whole property or one area', 'Visible indicators the business has chosen to ask about', 'Site access and responsible contact', 'Preferred callback window', 'Photos only where safe and useful'] },
      { heading: 'Route faults and projects differently', paragraphs: ['An approved urgent fault can alert the on-call electrician. Planned work can route to the estimator. Existing-booking changes can go to the office. Each route needs an owner and fallback rather than one noisy group message.'] },
    ],
    example: { title: 'Partial power loss in Southport', text: 'A caller says power is out in one part of the house. The assistant records the address, affected area, visible observations and callback details without suggesting a cause. The electrician receives an urgent review job and decides the response. Fictional demo data is used.' },
    productVisual: 'alert', productCaption: 'A structured alert shows what the caller reported and why the rule marked it for prompt human review.',
    table: { headers: ['Enquiry', 'Route'], rows: [['Fault or outage', 'Service electrician or approved urgent route'], ['New installation', 'Estimator or projects owner'], ['Inspection/compliance', 'Licensed reviewer'], ['Existing booking', 'Office or diary owner']] },
    faqs: [{ question: 'Can AI decide an electrical fault is safe?', answer: 'No. It must not make that judgment.' }, { question: 'Can it ask the caller to open a switchboard?', answer: 'Not unless the licensed business has expressly approved safe wording; the cautious default is not to direct physical checks.' }, { question: 'Can project enquiries go to a different person?', answer: 'Yes. A tested job-type rule can route project work separately from service faults.' }],
    sources: [sources.aiStandard, sources.aiGuardrails], related: ['questions-ai-receptionist-ask-electrical-caller', 'urgent-jobs-vs-emergency-jobs', 'route-different-calls-to-different-staff'],
  }),
  makeGuide({
    slug: 'ai-receptionist-air-conditioning-call-flow', number: 63, category: 'Trade call playbooks',
    title: 'How Should an AI Receptionist Handle Air-Conditioning Calls?',
    description: 'The useful first questions for split systems, ducted units, breakdowns, maintenance and installation enquiries.',
    directAnswer: 'An air-conditioning call flow should capture the site type, unit type and model if known, the symptom in plain English, when it began, preferred timing and access. It can distinguish service, maintenance and installation enquiries, request unit photos and route the job, but an HVAC technician must diagnose the equipment and confirm parts, price and attendance.',
    heroImage: '/blog/63-air-conditioning-call-playbook.webp', heroAlt: 'Australian air-conditioning technician reviewing unit details on a tablet beside an outdoor condenser',
    keyPoints: ['Unit details and photos reduce the first callback friction.', 'Service, maintenance and installation need different routes.', 'The technician—not the assistant—diagnoses and promises attendance.'],
    sections: [
      { heading: 'Separate service from installation', paragraphs: ['Ask whether the caller needs a breakdown visit, routine maintenance, replacement advice or a new installation quote. That single distinction changes the owner, questions and next step.'] },
      { heading: 'Collect the unit facts that are easy to confirm', bullets: ['Split, multi-split, ducted or commercial system', 'Make and model if visible', 'Indoor or outdoor unit affected', 'Cooling, heating, power, airflow, water or noise symptom', 'When the issue began and whether it is intermittent'] },
      { heading: 'Use photos for identification—not diagnosis', paragraphs: ['A clear rating-plate photo and a wider safe photo of the unit can help the technician prepare. The assistant should not infer refrigerant, electrical or mechanical failure from an image.'], callout: { label: 'PHOTO RULE', text: 'Ask for safe, identifying evidence. Never ask a customer to remove covers or access unsafe areas.' } },
      { heading: 'Route seasonal demand without overpromising', paragraphs: ['During heatwaves, capture preferred timing and make the review expectation explicit. “We will review and call” is different from “we will be there today”. Availability comes from the business, not the weather or the caller’s urgency.'] },
      { heading: 'Keep maintenance opportunities visible', paragraphs: ['Routine service and recurring maintenance should not disappear behind urgent breakdowns. Give them a clear pipeline status and named owner so they can be scheduled when capacity allows.'] },
    ],
    example: { title: 'A ducted system that is not cooling', text: 'Priya calls from a small office in Burleigh. The assistant captures the system type, reported airflow, start time, access and a rating-plate photo. The service coordinator receives one complete job and calls to assess the next step. Fictional demo data is used.' },
    productVisual: 'lead', productCaption: 'The lead view keeps model information, symptoms, customer evidence and callback requirements together.',
    faqs: [{ question: 'Can the AI diagnose low refrigerant?', answer: 'No. It records symptoms and leaves diagnosis to a qualified technician.' }, { question: 'Can it collect a model number?', answer: 'Yes, from the caller or a safe photo when the business has enabled that request.' }, { question: 'Can installation enquiries route to sales?', answer: 'Yes. A tested call-type rule can send them to the estimator or sales owner.' }],
    sources: [sources.aiStandard], related: ['customer-photos-help-qualify-trade-job', 'qualify-trade-lead-without-annoying-customer', 'customer-photos-help-qualify-trade-job'],
  }),
  makeGuide({
    slug: 'ai-receptionist-builder-renovation-call-flow', number: 64, category: 'Trade call playbooks',
    title: 'How Should an AI Receptionist Handle Builder and Renovation Enquiries?',
    description: 'A practical way to separate real project opportunities, service questions and vague price shopping before the builder returns the call.',
    directAnswer: 'A builder-focused call flow should capture the project type, suburb, ownership or decision role, current stage, plans or approvals, target timing and a broad budget band only if the builder chooses to ask. It should arrange a qualified callback or request for plans—not invent a square-metre rate or promise a start date.',
    heroImage: '/blog/64-builder-renovation-call-playbook.webp', heroAlt: 'Australian residential builder reviewing renovation plans and a new enquiry on site',
    keyPoints: ['Project stage matters more than a long list of room details.', 'Plans, decision role and timing reveal whether a callback is useful.', 'Ballpark prices and start dates remain human decisions.'],
    sections: [
      { heading: 'Identify the project lane', paragraphs: ['Distinguish renovation, extension, new build, repair, defect question, subcontractor call and existing project. Each lane needs different questions and a different owner.'] },
      { heading: 'Qualify readiness without making the call hostile', paragraphs: ['Ask what the customer wants to change, where the property is, whether they own it, what stage they are at and what they already have. A short, respectful flow is more useful than a twenty-question interrogation.'] },
      { heading: 'Request plans and photos deliberately', paragraphs: ['If a plan, sketch or current-site photo will change the review, send a secure upload request. Explain what is useful and that the builder still needs to inspect and scope the work.'] },
      { heading: 'Keep price questions inside the boundary', paragraphs: ['The assistant can explain the builder’s quoting process or repeat an approved consultation fee. It should not produce a project estimate from a phone description.'], callout: { label: 'NO BALLPARK PROMISE', text: 'A captured budget is a fit signal, not a quote or commitment.' } },
      { heading: 'Create an estimator-ready summary', bullets: ['Project type and suburb', 'Owner or decision-maker status', 'Current stage and documents', 'Target timing', 'Approved budget question if used', 'Best callback and site-visit availability'] },
    ],
    example: { title: 'A kitchen and rear extension enquiry', text: 'Daniel owns a home in Palm Beach and has concept drawings but no engineering. The assistant captures the project, stage, target timing and upload link. The estimator reviews the plans before deciding whether to offer a discovery call. Fictional demo data is used.' },
    productVisual: 'pipeline', productCaption: 'Qualified project enquiries can sit in a clear needs-review lane instead of disappearing into a voicemail list.',
    faqs: [{ question: 'Should the assistant ask for a budget?', answer: 'Only if the builder wants that question and has approved the wording. Explain why it is being asked.' }, { question: 'Can it book a site visit?', answer: 'It can capture preferred times. A live booking requires current connected availability and tested rules.' }, { question: 'Can customers upload plans?', answer: 'The product currently supports customer image uploads. Broader document handling should be confirmed for the specific setup before it is promised.' }],
    sources: [sources.aiStandard], related: ['what-is-lead-qualification-for-tradies', 'what-is-lead-qualification-for-tradies', 'questions-before-buying-ai-receptionist'],
  }),
  makeGuide({
    slug: 'ai-receptionist-carpentry-call-flow', number: 65, category: 'Trade call playbooks',
    title: 'How Should an AI Receptionist Handle Carpentry Calls?',
    description: 'A carpentry intake flow for repairs, doors, decks, fit-outs and custom work that captures enough evidence without quoting blind.',
    directAnswer: 'A carpentry call flow should capture the job type, property, approximate size, materials if known, current condition, timing, access and photos. It can separate small repairs from custom or project work and route the enquiry, but the carpenter must confirm measurements, suitability, materials, scope and price.',
    heroImage: '/blog/65-carpentry-call-playbook.webp', heroAlt: 'Australian carpenter reviewing customer job photos in a timber workshop',
    keyPoints: ['Photos help sort repair work from larger custom jobs.', 'Measurements supplied by callers are leads, not final take-offs.', 'Small jobs and project quotes should have different next steps.'],
    sections: [
      { heading: 'Name the job before asking for detail', paragraphs: ['Start by separating door or window work, deck repair, framing, cabinetry, fit-out, maintenance and custom construction. The category determines whether a photo, site visit or estimator callback matters.'] },
      { heading: 'Capture dimensions as approximate', paragraphs: ['Caller measurements can help with triage, but they should be labelled as customer-supplied. Final material orders and quotes require the carpenter’s verified measure and scope.'] },
      { heading: 'Use a clear photo brief', bullets: ['One wide photo showing the whole item', 'One close photo of the damaged or joining area', 'A safe view of access', 'Existing finish or material when visible', 'No climbing or unsafe positioning for a photo'] },
      { heading: 'Separate repair urgency from project timing', paragraphs: ['A security or access issue may use an approved urgent path. A deck, fit-out or custom piece needs project timing and a review queue. The assistant records the reason; it does not decide structural safety.'] },
      { heading: 'End with the carpenter’s real process', paragraphs: ['Tell the customer whether the next step is a callback, photo review, site measure or polite decline. Never promise that a phone description is enough for a fixed quote.'], callout: { label: 'MEASURE TWICE', text: 'Customer dimensions help triage; the carpenter verifies dimensions before scope, ordering or price.' } },
    ],
    example: { title: 'A swollen external door', text: 'A homeowner reports that an external timber door will no longer close. The assistant captures the suburb, security concern, approximate door size, access and two photos. The carpenter reviews the job and decides whether it fits the service run. Fictional demo data is used.' },
    productVisual: 'photo-request', productCaption: 'Wide and close customer photos land on the same carpentry lead for a faster, safer callback decision.',
    faqs: [{ question: 'Can the AI quote from a photo?', answer: 'No. It may help organise the evidence, but the carpenter reviews scope and price.' }, { question: 'Can it separate handyman work from carpentry projects?', answer: 'Yes, using the job types and minimum-work rules supplied by the business.' }, { question: 'Can callers send measurements?', answer: 'Yes, but the record should label them as unverified customer information.' }],
    sources: [sources.aiStandard], related: ['customer-photos-help-qualify-trade-job', 'customer-photos-help-qualify-trade-job', 'what-information-tradie-needs-before-calling-back'],
  }),
  makeGuide({
    slug: 'ai-receptionist-painting-call-flow', number: 66, category: 'Trade call playbooks',
    title: 'How Should an AI Receptionist Handle Painting Enquiries?',
    description: 'The useful questions for interior, exterior, repaint, repair and commercial painting leads before the estimator calls back.',
    directAnswer: 'A painting call flow should capture the property type, interior or exterior scope, rooms or surfaces, current condition, colour-change intent, access, timing and photos. It can organise the enquiry and collect preferred quote times, but the painter must inspect preparation, access, coatings and final scope before pricing.',
    heroImage: '/blog/66-painting-call-playbook.webp', heroAlt: 'Australian painter reviewing room photos and an estimate notebook at a residential repaint',
    keyPoints: ['Preparation and access often matter more than the room count.', 'A wide photo plus detail photos make the estimator callback useful.', 'The assistant captures scope; the painter confirms coatings and price.'],
    sections: [
      { heading: 'Separate interior, exterior and commercial work', paragraphs: ['Ask where the painting is, what the customer wants painted and whether the site is occupied. Commercial access, body-corporate approval and after-hours work may change the route.'] },
      { heading: 'Capture surfaces and condition in plain English', paragraphs: ['Record walls, ceilings, trim, doors, cladding or other visible surfaces and what the customer notices. Do not turn “flaking” into a confirmed substrate or moisture diagnosis.'] },
      { heading: 'Ask for useful—not beautiful—photos', bullets: ['Wide view of each main area', 'Close view of peeling, cracking or damage', 'Exterior height and access from ground level', 'Furniture or occupancy constraints', 'No risky ladder photos'] },
      { heading: 'Treat timing as a planning input', paragraphs: ['Move-in dates, tenant turnover and other trades may affect priority. Capture the target and constraints without promising that the crew can meet them.'] },
      { heading: 'Give the estimator a clean summary', paragraphs: ['The callback should begin with the painter already knowing the property, broad scope, condition, photos and decision-maker. That makes the conversation feel prepared instead of repetitive.'], callout: { label: 'SCOPE FIRST', text: 'Room count is useful, but preparation, height, access and occupancy often decide the real work.' } },
    ],
    example: { title: 'An occupied three-bedroom repaint', text: 'The customer wants walls and ceilings repainted before a family event. The assistant captures rooms, current condition, timing, access constraints and photos. The estimator reviews the evidence and offers a site visit—not a blind price. Fictional demo data is used.' },
    productVisual: 'lead', productCaption: 'The lead summary gives the painter enough context to plan the estimate without treating customer observations as a final scope.',
    faqs: [{ question: 'Can it estimate from room count?', answer: 'It should not invent a price. Room count is only one input for the painter.' }, { question: 'Can it ask about colours?', answer: 'Yes, when that helps the estimator, while leaving final product and coating advice to the painter.' }, { question: 'Can painting leads upload several photos?', answer: 'Yes. The enabled photo flow accepts up to six images and attaches them to the job.' }],
    sources: [sources.aiStandard], related: ['saved-products-prices-speed-up-trade-quotes', 'qualify-trade-lead-without-annoying-customer', 'saved-products-prices-speed-up-trade-quotes'],
  }),
  makeGuide({
    slug: 'ai-receptionist-landscaping-call-flow', number: 67, category: 'Trade call playbooks',
    title: 'How Should an AI Receptionist Handle Landscaping Enquiries?',
    description: 'A landscaping call flow that captures site size, access, project type, timing and visual evidence before a long site visit is booked.',
    directAnswer: 'A landscaping call flow should capture the property, broad project type, approximate area, slope and access as the caller understands them, current condition, target timing and photos. It can separate maintenance, repair and design-and-build work, but the landscaper must assess drainage, levels, structures, materials and final price.',
    heroImage: '/blog/67-landscaping-call-playbook.webp', heroAlt: 'Australian landscaper reviewing a customer garden enquiry beside a work ute',
    keyPoints: ['Project type and access quickly show which team should review the lead.', 'Wide site photos help without replacing a site inspection.', 'Maintenance and design work belong in different pipelines.'],
    sections: [
      { heading: 'Start with the outcome the customer wants', paragraphs: ['Ask whether this is regular maintenance, a clean-up, turf, planting, paving, retaining, drainage, irrigation or a larger redesign. Use the customer’s words and avoid implying engineering or structural conclusions.'] },
      { heading: 'Capture the site constraints', bullets: ['Suburb and property type', 'Approximate area', 'Flat, sloped or mixed site as reported', 'Side access, stairs, gates and parking', 'Pets, tenants or body-corporate access', 'Target timing'] },
      { heading: 'Use photos to qualify the site visit', paragraphs: ['Request wide ground-level photos of the area and access. A photo may reveal that a different crew or equipment is needed, but it does not replace level checks, service location or an on-site assessment.'] },
      { heading: 'Route recurring work separately', paragraphs: ['Regular mowing or maintenance can go to the maintenance owner. Construction-style work should go to the estimator. A clean route stops valuable projects and small recurring jobs competing in the same unowned inbox.'] },
      { heading: 'Avoid instant landscape pricing', paragraphs: ['The assistant can state an approved consultation fee or process. It should not price earthworks, drainage, retaining or material quantities from a caller’s estimate.'], callout: { label: 'SITE REALITY', text: 'Photos qualify the conversation; the landscaper verifies levels, access, services and scope.' } },
    ],
    example: { title: 'A sloped backyard redesign', text: 'A homeowner in Elanora wants turf, planting and a small paved area. The assistant captures access, approximate size, slope, timing and four ground-level photos. The design owner reviews the lead and decides whether to book a consultation. Fictional demo data is used.' },
    productVisual: 'pipeline', productCaption: 'Maintenance requests and larger project opportunities can be kept in visible, separately owned lanes.',
    faqs: [{ question: 'Can it ask about budget?', answer: 'Yes, if the landscaper approves the wording and explains why the range helps qualify the project.' }, { question: 'Can it diagnose drainage from a photo?', answer: 'No. It records the customer’s concern for on-site assessment.' }, { question: 'Can maintenance calls route to a crew leader?', answer: 'Yes, when the account has a tested job-type route for that person.' }],
    sources: [sources.aiStandard], related: ['how-tradies-define-service-area', 'what-is-lead-qualification-for-tradies', 'route-different-job-types-right-person'],
  }),
  makeGuide({
    slug: 'ai-receptionist-property-maintenance-call-flow', number: 68, category: 'Trade call playbooks',
    title: 'How Should an AI Receptionist Handle Property-Maintenance Calls?',
    description: 'A practical intake flow for owners, tenants, property managers and recurring maintenance across mixed job types.',
    directAnswer: 'A property-maintenance call flow should identify the property, caller role, responsible contact, job type, access, urgency, approval or work-order details and any useful photos. It should route new work, tenant issues and existing jobs to the right person without diagnosing the problem or authorising spend.',
    heroImage: '/blog/68-property-maintenance-call-playbook.webp', heroAlt: 'Australian property maintenance supervisor reviewing tenant job details outside an apartment complex',
    keyPoints: ['Caller role and approval authority matter as much as the fault.', 'Mixed trades need clear job-type and territory routes.', 'Access, tenant contact and work-order details should stay on the job.'],
    sections: [
      { heading: 'Identify who is calling', paragraphs: ['Owner, tenant, property manager, body corporate and supplier calls can describe the same issue but require different approvals and communication. Capture the role and the authorised contact before assuming who can approve work.'] },
      { heading: 'Keep property and access details together', bullets: ['Full service address and unit', 'Tenant or site contact', 'Keys, gate, parking and access windows', 'Pets or occupancy notes', 'Work-order or reference number', 'Approved contact for variations'] },
      { heading: 'Use trade and urgency rules carefully', paragraphs: ['Route plumbing, electrical, handyman, grounds and general maintenance to named owners. The system can mark approved urgent indicators, but the licensed or responsible person decides the response.'] },
      { heading: 'Connect customer evidence to the job', paragraphs: ['A photo link can reduce the back-and-forth between tenant, manager and contractor. The evidence should remain visible with the original caller, property and approval chain.'] },
      { heading: 'Do not let automation approve spend', paragraphs: ['The assistant may repeat an authorised limit if the business has a controlled rule, but it should not create authority that the caller did not provide. Variations and disputes remain human decisions.'], callout: { label: 'AUTHORITY CHECK', text: 'Capture who can approve the work; do not assume the person reporting it can approve the cost.' } },
    ],
    example: { title: 'A tenant reports a damaged door closer', text: 'The assistant captures the unit, tenant details, property-manager reference, access window and photos. The maintenance coordinator reviews the job, confirms authority and routes it to the right technician. Fictional demo data is used.' },
    productVisual: 'dashboard', productCaption: 'The dashboard keeps caller, property, evidence, route and current status in one reviewable record.',
    faqs: [{ question: 'Can it collect a work-order number?', answer: 'Yes. Add it as a required field for the relevant caller type.' }, { question: 'Can it route different trades?', answer: 'Yes, when each job type has a named primary and fallback owner.' }, { question: 'Can it tell a tenant the job is approved?', answer: 'Only if that approval already exists in a connected, tested process. Otherwise it confirms that the request will be reviewed.' }],
    sources: [sources.aiStandard], related: ['route-different-job-types-right-person', 'route-different-calls-to-different-staff', 'customer-photos-help-qualify-trade-job'],
  }),
  makeGuide({
    slug: 'ai-receptionist-roofing-gutter-call-flow', number: 69, category: 'Trade call playbooks',
    title: 'How Should an AI Receptionist Handle Roofing and Gutter Calls?',
    description: 'A safe intake flow for leaks, storm damage, gutter work, inspections and replacement enquiries without asking customers to climb.',
    directAnswer: 'A roofing call flow should capture the property, affected area, what is visible from a safe position, when the issue occurs, storm context, access, insurance or manager details and ground-level photos. It must never ask a caller to climb, diagnose structural safety or promise emergency attendance.',
    heroImage: '/blog/69-roofing-gutter-call-playbook.webp', heroAlt: 'Australian roofer reviewing storm-damage enquiry details safely from ground level',
    keyPoints: ['No photo or question should require the caller to climb.', 'Storm, leak, gutter and replacement enquiries need different review paths.', 'The roofer decides safety, access equipment, diagnosis and timing.'],
    sections: [
      { heading: 'Capture what is visible from safety', paragraphs: ['Ask where the water or damage is noticed and when it appears. Record ceiling stains, displaced material seen from the ground or overflowing gutters as observations—not as a confirmed roof failure.'] },
      { heading: 'Ask about storm and access context', bullets: ['Recent wind, hail or heavy rain as reported', 'Single or multi-storey property', 'Safe ground-level access', 'Tenant, owner, body-corporate or insurer contact', 'Whether internal damage is active', 'Best callback availability'] },
      { heading: 'Make the photo boundary explicit', paragraphs: ['Request ground-level, indoor or existing photos only. Never ask the caller to climb a ladder, enter a roof space or walk on a roof to help the quote.'], callout: { label: 'SAFETY RULE', text: 'No customer photo is worth a ladder or roof risk.' } },
      { heading: 'Separate immediate review from attendance', paragraphs: ['An approved urgent indicator can send an immediate alert. It does not create a booking or promise the roofer can attend during a storm. The caller hears the business’s actual review expectation.'] },
      { heading: 'Prepare the roofer for the callback', paragraphs: ['A clear summary should make property height, reported damage, timing, safe photos and decision-maker visible. The roofer can then ask the right next questions or arrange an inspection.'] },
    ],
    example: { title: 'A leak after a Gold Coast storm', text: 'The homeowner reports a new ceiling stain after heavy rain. The assistant captures the affected room, property height, safe access, insurer status and indoor and ground-level photos. The roofer receives an urgent review alert and decides the response. Fictional demo data is used.' },
    productVisual: 'alert', productCaption: 'The urgent review alert carries the observations and safe evidence without claiming the roof has been diagnosed.',
    faqs: [{ question: 'Should the caller photograph the roof?', answer: 'Only from a safe ground-level position. Never ask them to climb.' }, { question: 'Can the AI decide storm damage is urgent?', answer: 'It can apply the roofer’s approved reported-condition rule; the roofer decides the response.' }, { question: 'Can insurance details be captured?', answer: 'Yes, if the business needs them and handles the information appropriately.' }],
    sources: [sources.aiStandard], related: ['urgent-jobs-vs-emergency-jobs', 'customer-photos-help-qualify-trade-job', 'what-can-ai-receptionist-do-and-never-do'],
  }),
  makeGuide({
    slug: 'why-one-ai-call-script-does-not-fit-every-trade', number: 70, category: 'Trade call playbooks',
    title: 'Why Doesn’t One AI Call Script Work for Every Trade?',
    description: 'Why plumbers, electricians, builders and landscapers need different questions, boundaries, urgency rules and hand-offs.',
    directAnswer: 'One generic script fails because the facts that change a decision differ by trade. A plumber may need water status; an air-conditioning technician may need the unit model; a builder may need project stage; a landscaper may need access and approximate area. The greeting can be shared, but questions, safety boundaries and routing must match the work.',
    heroImage: '/blog/70-different-trade-call-scripts.webp', heroAlt: 'Australian plumber electrician painter and landscaper comparing different customer call checklists',
    keyPoints: ['Use one operating structure but trade-specific questions.', 'Urgency language must match the business and licensed judgment.', 'Remove every question that does not change the next action.'],
    sections: [
      { heading: 'The structure can stay consistent', paragraphs: ['Business introduction, AI disclosure, caller identity, location, intent, clear next step and fallback belong in most flows. Consistency helps operators test and support the service.'] },
      { heading: 'The evidence changes by trade', paragraphs: ['Model plates help HVAC calls; wide site photos help landscaping; project documents help builders; affected-fixture details help plumbers. A generic “tell us more” prompt collects stories instead of decision-ready information.'] },
      { heading: 'The risk boundary changes too', paragraphs: ['Electrical, roof, plumbing and structural calls have different high-consequence edges. The assistant should use the specific boundaries approved by the business and avoid remote diagnosis across every trade.'] },
      { heading: 'Routing reflects the real team', bullets: ['Service technician for routine faults', 'Estimator for projects', 'On-call person for approved urgent indicators', 'Office for existing bookings', 'Human review for unclear or excluded work'] },
      { heading: 'Improve one trade flow at a time', paragraphs: ['Review whether the questions changed a real callback decision. Remove unused questions, tighten misunderstood wording and add a rule only when someone owns the result.'], callout: { label: 'DESIGN TEST', text: 'If an answer does not change fit, urgency, evidence, route or next step, the question may not belong in the call.' } },
    ],
    example: { title: 'The same “water problem” means different intake', text: 'A plumber needs the affected fixture and visible flow. A roofer needs the affected room, weather context and safe ground-level evidence. A property-maintenance operator also needs tenant and approval details. One phrase produces three different useful call flows.' },
    productVisual: 'rules', productCaption: 'TradieRelay stores business-specific call rules so a trade flow can be tested without changing every other customer account.',
    table: { headers: ['Trade', 'Decision-changing detail'], rows: [['Plumbing', 'Affected fixture and visible water status'], ['Electrical', 'Affected area and approved indicators'], ['Air conditioning', 'Unit type, model and symptom'], ['Building', 'Project stage, plans and decision role'], ['Landscaping', 'Area, slope, access and project type']] },
    faqs: [{ question: 'Can one business run more than one trade flow?', answer: 'Yes, if each call type has distinct questions, routes and owners.' }, { question: 'Should every flow ask the same number of questions?', answer: 'No. Ask only what changes the next decision.' }, { question: 'Who approves the script?', answer: 'The business owner and the people responsible for the trade, routing and customer response should approve and test it.' }],
    sources: [sources.aiStandard, sources.aiGuardrails], related: ['how-tradie-set-call-answering-rules', 'what-can-ai-receptionist-do-and-never-do', 'what-is-lead-qualification-for-tradies'],
  }),
];
