export type BlogSection = {
  heading: string;
  paragraphs?: string[];
  bullets?: string[];
  callout?: { label: string; text: string };
};

export type BlogArticle = {
  slug: string;
  number: number;
  category: 'AI receptionist basics' | 'Missed-call recovery';
  title: string;
  description: string;
  directAnswer: string;
  readMinutes: number;
  heroImage: string;
  heroAlt: string;
  heroPosition?: string;
  secondaryImage: string;
  secondaryAlt: string;
  secondaryCaption: string;
  keyPoints: string[];
  sections: BlogSection[];
  example: { title: string; text: string };
  productVisual: 'alert' | 'lead' | 'pipeline' | 'dashboard' | 'rules' | 'photo-request';
  productCaption: string;
  checklist?: string[];
  table?: { headers: string[]; rows: string[][] };
  faqs: { question: string; answer: string }[];
  sources?: { label: string; url: string }[];
  related: string[];
};

export const blogArticles: BlogArticle[] = [
  {
    slug: 'what-is-an-ai-receptionist-for-tradies',
    number: 1,
    category: 'AI receptionist basics',
    title: 'What Is an AI Receptionist for Tradies?',
    description: 'A plain-English guide to what an AI receptionist can answer, capture and route for an Australian trade business—and where the tradie stays in control.',
    directAnswer: 'An AI receptionist is a phone assistant that answers selected business calls using wording and rules approved by the tradie. It can collect the caller’s name, number, suburb, job details and urgency, then send the tradie a structured lead. It should not diagnose faults, invent prices or promise attendance.',
    readMinutes: 7,
    heroImage: '/blog/plumber-missed-call.webp',
    heroAlt: 'Australian plumber working under a kitchen sink while a business call rings nearby',
    secondaryImage: '/customer-sends-job-photo.jpg',
    secondaryAlt: 'Customer taking a useful job photo to send to a trade business',
    secondaryCaption: 'When the approved flow asks for a photo, the customer receives a secure upload link and the image attaches to the same job.',
    keyPoints: [
      'It answers only the calls and situations you choose.',
      'It turns an interruption into a useful, structured job enquiry.',
      'You keep control of prices, bookings, technical advice and final decisions.',
    ],
    sections: [
      {
        heading: 'Think of it as a first-response system for your phone',
        paragraphs: [
          'When you are under a sink, on a ladder or driving between jobs, answering every call is not realistic. An AI receptionist can step in when a call is missed, busy, unanswered or outside your chosen hours. It greets the caller in your business name, explains that it is an automated assistant and asks the questions you approved.',
          'The goal is not to run the trade business on your behalf. The goal is to stop a potentially good job becoming a vague missed-call notification with no context.',
        ],
      },
      {
        heading: 'What it can collect from a caller',
        paragraphs: ['A useful setup asks only for information that helps you decide the next step. For most trade businesses, that means:'],
        bullets: [
          'Name and best callback number',
          'Suburb or service location',
          'Type of job and a plain-English description',
          'Whether the caller says it is urgent',
          'Preferred timing and access notes',
          'Photos or model details when your approved flow asks for them',
        ],
      },
      {
        heading: 'What happens after the call',
        paragraphs: [
          'TradieRelay keeps the enquiry together as one job. The tradie sees the call summary, the captured details and any customer photos in the dashboard. From there, a person chooses what should happen: call the customer, ask for more information, prepare a quote, offer a time or politely decline.',
          'That human decision matters. AI can organise the facts, but it should not pretend to know your day, your stock, your price or the condition of a job it has never inspected.',
        ],
        callout: { label: 'CONTROL POINT', text: 'A captured lead is not an automatic promise. The tradie reviews it and chooses the next step.' },
      },
      {
        heading: 'What a good AI receptionist should never do',
        bullets: [
          'Diagnose electrical, plumbing, HVAC or structural problems over the phone',
          'Give safety instructions beyond wording the business has approved',
          'Make up a price, discount or availability',
          'Hide that the caller is speaking with an automated assistant',
          'Book over a human decision when the rules require approval',
          'Keep pushing when a caller needs emergency services or a human hand-off',
        ],
      },
      {
        heading: 'Why this is different from voicemail',
        paragraphs: [
          'Voicemail asks the customer to do all the work and often produces a name, half a number and “call me back”. An AI receptionist holds a short two-way conversation, checks the important details and confirms what will happen next.',
          'That gives the tradie enough information to return the most useful calls first instead of calling every unknown number blind.',
        ],
      },
    ],
    example: {
      title: 'Example: Sarah’s burst flexi hose',
      text: 'Sarah calls while the plumber is on another job. TradieRelay says it is the business’s automated assistant, captures that Sarah is in Burleigh Waters, that a flexi hose has burst and that she says the mains are off. It requests a photo using the approved text flow. The plumber receives one job card with the call summary and photo, then decides whether to call, attend or refer the work. This is fictional demo data, but it matches the working product flow shown below.',
    },
    productVisual: 'lead',
    productCaption: 'The working TradieRelay demo turns the call into a reviewable job. Fake customer data is used here.',
    checklist: [
      'Choose which calls the assistant may answer.',
      'Approve the greeting and AI disclosure.',
      'List the job types and suburbs you want.',
      'Set urgent-job and human hand-off rules.',
      'Decide which questions may trigger a photo request.',
      'Test the flow with real-world calls before switching it on.',
    ],
    faqs: [
      { question: 'Does the AI answer every call?', answer: 'It does not have to. TradieRelay can be set to handle only missed calls, busy calls, overflow, after-hours calls or another approved combination.' },
      { question: 'Can it book jobs automatically?', answer: 'Only if the business explicitly chooses a booking rule and provides valid availability. A cautious starting setup captures the lead and lets the tradie approve the time.' },
      { question: 'Will callers know it is AI?', answer: 'They should. TradieRelay’s standard flow includes a clear automated-assistant disclosure in the introduction.' },
    ],
    sources: [
      { label: 'Australian Government Voluntary AI Safety Standard', url: 'https://www.industry.gov.au/publications/voluntary-ai-safety-standard' },
      { label: 'OAIC guidance on privacy and commercially available AI', url: 'https://www.oaic.gov.au/privacy/privacy-guidance-for-organisations-and-government-agencies/guidance-on-privacy-and-the-use-of-commercially-available-ai-products' },
    ],
    related: ['how-does-an-ai-receptionist-handle-a-tradie-call', 'what-can-ai-receptionist-do-and-never-do', 'ai-receptionist-setup-checklist-australian-tradies'],
  },
  {
    slug: 'how-does-an-ai-receptionist-handle-a-tradie-call', number: 2, category: 'AI receptionist basics',
    title: 'How Does an AI Receptionist Handle a Tradie Call?',
    description: 'Follow a trade enquiry from the first ring through qualification, photo collection, routing and the tradie’s final decision.',
    directAnswer: 'A well-configured AI receptionist follows a controlled call flow: it answers under an approved call rule, identifies the business and itself, captures the caller’s intent and job basics, checks fit and urgency, then confirms the next step. The tradie receives a structured job—not an unqualified promise.',
    readMinutes: 8, heroImage: '/customer-call.jpg', heroAlt: 'Australian homeowner calling a trade business from home', heroPosition: 'center',
    secondaryImage: '/blog/tradierelay-photo-request.png', secondaryAlt: 'TradieRelay secure customer photo upload screen', secondaryCaption: 'If photos will help, the caller is told a secure link will arrive by text. The upload screen accepts up to six images.',
    keyPoints: ['The greeting says whose business answered and that the assistant is automated.', 'Each question earns its place by helping the tradie decide what to do.', 'The caller hears a clear next step; the tradie keeps the final decision.'],
    sections: [
      { heading: '1. Your normal number rings under your rule', paragraphs: ['You choose when TradieRelay steps in. A simple starting point is no-answer and after-hours only. Busy and overflow rules can be added once the first flow is working. The customer still calls the number they already know.'], callout: { label: 'START SMALL', text: 'Missed-call recovery is easier to test than handing over every call on day one.' } },
      { heading: '2. The caller hears a clear introduction', paragraphs: ['The assistant uses the business name and says it is an automated assistant that can take the job details. That sets the right expectation and gives the caller a reason to continue. It does not pretend to be Noah, Jake or an office employee.'] },
      { heading: '3. The useful facts are captured', bullets: ['Is this a new job, existing booking, quote question or something else?', 'What is the caller’s name and callback number?', 'Where is the job and what is happening?', 'How urgent does the caller say it is?', 'What timing, access or evidence would help?'] },
      { heading: '4. The rules decide the lane—not the outcome', paragraphs: ['Service area, job type, timing and exclusions are checked against the business’s approved rules. A matching lead can be marked for callback. An urgent lead can trigger an immediate alert. An out-of-area job can receive a polite response. None of those actions requires the AI to diagnose the fault.'] },
      { heading: '5. One job lands with context attached', paragraphs: ['The summary, call details, requested next action and customer photos stay together. The tradie can listen, review uncertain details and choose the next step. Replies and status changes should stay on that same enquiry instead of creating loose messages.'] },
    ],
    example: { title: 'From ring to reviewable job', text: 'Sarah calls about a burst flexi hose. The business number rings first, then TradieRelay answers under the no-answer rule. It collects her suburb, description, callback details and preferred time, and sends a photo link. The plumber sees one urgent job card and decides whether to call or attend. Fictional demo data is used.' },
    productVisual: 'dashboard', productCaption: 'The actual working demo shows the lead, call summary and customer photo in one job detail view.',
    table: { headers: ['Stage', 'Caller experiences', 'Tradie receives'], rows: [['Answer', 'Business name and AI disclosure', 'No interruption unless the rule routes the call'], ['Capture', 'Short questions in plain English', 'Name, number, suburb, job and urgency'], ['Evidence', 'Optional text link for photos', 'Images attached to the same job'], ['Decision', 'A clear expectation', 'Call, quote, book, ask or decline']] },
    checklist: ['Choose the call condition.', 'Approve the exact introduction.', 'Limit the first flow to essential questions.', 'Set escalation and emergency wording.', 'Test fit, non-fit, unclear and silent-caller cases.', 'Review the first real calls and tighten the wording.'],
    faqs: [{ question: 'How long should the call take?', answer: 'Long enough to capture a useful lead, but no longer. The exact time depends on the trade and job. Removing questions that do not change the next decision keeps the flow focused.' }, { question: 'Can the caller ask for a person?', answer: 'Yes. The business decides when to transfer, take a message or promise a human callback. The assistant should not trap someone in a loop.' }, { question: 'What if the caller hangs up?', answer: 'The system should preserve whatever valid information was captured and follow the business’s abandoned-call rule. It must not invent missing details.' }],
    sources: [{ label: 'TradieRelay full call flow', url: 'https://tradie-relay.verve-9089.chatgpt.site/call-flow' }, { label: 'Australian Government Voluntary AI Safety Standard', url: 'https://www.industry.gov.au/publications/voluntary-ai-safety-standard' }],
    related: ['what-is-an-ai-receptionist-for-tradies', 'busy-no-answer-after-hours-which-call-rule', 'what-happens-after-tradie-misses-call'],
  },
  {
    slug: 'can-ai-really-answer-calls-for-trade-business', number: 3, category: 'AI receptionist basics',
    title: 'Can AI Really Answer Calls for a Trade Business?',
    description: 'Where AI phone answering works well for tradies, where it can struggle and the controls that make it useful instead of risky.',
    directAnswer: 'Yes—AI can answer straightforward trade enquiries when the scope is narrow, the questions are approved and uncertain answers are confirmed. It works best for capturing and routing information. It is less suitable for diagnosis, negotiation, emotional complaints or any situation where a qualified human must judge the work.',
    readMinutes: 7, heroImage: '/blog/electrician-missed-call.webp', heroAlt: 'Australian electrician inspecting a switchboard while a phone call comes in nearby',
    secondaryImage: '/blog/trade-crew-routing.webp', secondaryAlt: 'Small Australian trade business reviewing its call system', secondaryCaption: 'The system is strongest when the trade business defines the questions, service area and hand-off before callers reach it.',
    keyPoints: ['AI is good at repeatable intake, not trade judgment.', 'A narrow first flow is more dependable than a system trying to answer everything.', 'Confirmation, fallback and human review protect against misheard details.'],
    sections: [
      { heading: 'The jobs AI is well placed to handle', bullets: ['Answering when the business is busy or closed', 'Collecting names, numbers, suburbs and job descriptions', 'Separating new enquiries from existing-customer calls', 'Applying clear service-area and job-type rules', 'Requesting photos and confirming the next step'] },
      { heading: 'The jobs that still need people', paragraphs: ['An AI receptionist has not inspected the site, checked compliance, seen the diary change or weighed the commercial relationship. It should hand back decisions about technical advice, final pricing, complaints, exceptions and any promise that creates risk.'] },
      { heading: 'The real issue is not “Can it talk?”', paragraphs: ['Modern voice systems can hold a conversation. The business question is whether the conversation creates a dependable record and stays inside the approved boundaries. A friendly voice with loose rules is less useful than a plain voice with reliable capture and escalation.'] },
      { heading: 'Build for mistakes, not perfection', paragraphs: ['Names, street details and accents can be misheard. The flow should repeat important details, allow correction, avoid guessing and send uncertain cases to a human. TradieRelay labels AI-captured information for review instead of presenting it as unquestionable fact.'], callout: { label: 'PRACTICAL STANDARD', text: 'If a wrong answer could cost money, safety or trust, make the system confirm it or hand it over.' } },
      { heading: 'A useful first deployment', paragraphs: ['Start with missed new-job calls in a defined service area. Review the transcripts and summaries. Only expand to more call types when the system is consistently capturing what the business needs.'] },
    ],
    example: { title: 'An electrical enquiry without remote diagnosis', text: 'A caller reports that part of the house has lost power. TradieRelay captures the address, visible issue, callback availability and approved urgency indicators. It does not tell the caller which component failed. The electrician reviews the summary and decides what response is appropriate.' },
    productVisual: 'lead', productCaption: 'TradieRelay marks the job as AI-captured and prompts the tradie to check anything uncertain.',
    checklist: ['Name five repeatable call types.', 'Name five calls that always need a person.', 'Write the exact hand-off for uncertainty.', 'Require confirmation of names, numbers and addresses.', 'Review summaries against recordings during testing.', 'Expand only after the first narrow flow is reliable.'],
    faqs: [{ question: 'Will it sound exactly like a person?', answer: 'The aim should be a clear, respectful conversation—not deception. The introduction should identify the automated assistant.' }, { question: 'Can it answer technical questions?', answer: 'It can repeat business-approved information, but it should not diagnose a fault or improvise trade advice.' }, { question: 'What happens if the service is unavailable?', answer: 'A production setup needs a fallback such as voicemail, message capture or another number. That fallback should be tested before launch.' }],
    sources: [{ label: 'OAIC guidance on privacy and commercially available AI', url: 'https://www.oaic.gov.au/privacy/privacy-guidance-for-organisations-and-government-agencies/guidance-on-privacy-and-the-use-of-commercially-available-ai-products' }],
    related: ['what-can-ai-receptionist-do-and-never-do', 'what-happens-when-ai-does-not-know-answer', 'can-ai-receptionist-handle-australian-accents'],
  },
  {
    slug: 'what-can-ai-receptionist-do-and-never-do', number: 4, category: 'AI receptionist basics',
    title: 'What Can an AI Receptionist Do—and What Should It Never Do?',
    description: 'A practical boundary list for Australian trade businesses: safe call capture on one side, human-only decisions on the other.',
    directAnswer: 'An AI receptionist can greet callers, capture job facts, apply simple routing rules, request evidence and send updates. It should never diagnose a trade problem, invent a price, conceal that it is automated, promise attendance without authority, or make a high-consequence decision that needs a qualified person.',
    readMinutes: 8, heroImage: '/trades/electricians.jpg', heroAlt: 'Australian electrician working safely at a residential property',
    secondaryImage: '/blog/tradierelay-call-rules.png', secondaryAlt: 'TradieRelay call rules screen in the working demo', secondaryCaption: 'The working product keeps visible rules for answer timing, AI disclosure, phone pricing, failed questions and urgent alerts.',
    keyPoints: ['Capture facts; do not diagnose.', 'Apply approved rules; do not invent policy.', 'Escalate uncertainty; do not bluff.'],
    sections: [
      { heading: 'Green zone: repeatable call handling', bullets: ['State the business name and automated-assistant disclosure', 'Collect contact, location and job information', 'Check the service area and preferred job types', 'Send a secure photo request', 'Notify the right person using an approved rule', 'Confirm that a callback or review will happen'] },
      { heading: 'Amber zone: allowed only with a clear rule', bullets: ['Offering appointment windows from a connected, current calendar', 'Giving a price that comes from an approved product or service list', 'Transferring an urgent call to a named person', 'Sending follow-up messages on an existing enquiry', 'Handling an existing booking or change request'] },
      { heading: 'Red zone: leave it to a qualified human', bullets: ['Diagnosing a fault or telling a caller how to repair it', 'Giving safety, legal or compliance advice beyond approved wording', 'Negotiating price or making up a discount', 'Guaranteeing attendance, availability or an outcome', 'Resolving a serious complaint or dispute', 'Guessing when the caller’s answer is unclear'] },
      { heading: 'Boundaries should be visible and testable', paragraphs: ['A boundary hidden in a long prompt is easy to miss. The operator and the trade business should be able to see the call rules, test the edge cases and change the rule without rebuilding everything. Every exception should end in a named next step.'] },
      { heading: 'Human control is part of the product', paragraphs: ['Review buttons, approval steps, alerts and audit records are not signs that the AI failed. They are how a small business keeps judgment where it belongs while automating the repetitive part.'], callout: { label: 'RULE OF THUMB', text: 'If the assistant cannot cite an approved rule or saved fact, it should not present the answer as certain.' } },
    ],
    example: { title: 'A price question with a safe boundary', text: 'A caller asks, “How much to replace it?” If the business has not approved a price for that exact service, TradieRelay records the question and says the tradie will review it. It does not estimate from the caller’s description. If a saved, approved call-out fee exists, that exact information may be used under the business’s rule.' },
    productVisual: 'rules', productCaption: 'Actual TradieRelay demo screen showing the business’s selected rules. Demo data only.',
    table: { headers: ['AI may do', 'Only with a rule', 'Human only'], rows: [['Capture a suburb', 'Offer a connected calendar window', 'Promise attendance'], ['Request photos', 'Quote an approved saved fee', 'Diagnose the fault'], ['Send a lead alert', 'Transfer to a named person', 'Negotiate a dispute'], ['Confirm a callback', 'Send enquiry follow-up', 'Guess missing facts']] },
    checklist: ['Write a green, amber and red list.', 'Give every amber action a source and owner.', 'Give every red action a human hand-off.', 'Test price, safety, complaint and unclear-answer calls.', 'Keep the AI disclosure on.', 'Review boundaries whenever services or staff change.'],
    faqs: [{ question: 'Can the AI use prices saved in the account?', answer: 'Yes, when the business deliberately enables that use and the price applies to the caller’s exact request. TradieRelay’s current default rule is never to give prices by phone.' }, { question: 'Can it tell a caller to contact emergency services?', answer: 'The business can approve clear emergency wording and escalation. The assistant should not assess clinical, fire or life-safety risk by itself.' }, { question: 'Who changes the rules?', answer: 'The trade business approves the rules. TradieRelay’s setup and operator tools make the configuration visible and testable.' }],
    sources: [{ label: 'Australian Government Voluntary AI Safety Standard', url: 'https://www.industry.gov.au/publications/voluntary-ai-safety-standard' }],
    related: ['can-ai-really-answer-calls-for-trade-business', 'can-ai-receptionist-use-business-name-and-rules', 'what-happens-when-ai-does-not-know-answer'],
  },
  {
    slug: 'who-is-ai-receptionist-best-suited-to', number: 5, category: 'AI receptionist basics',
    title: 'Who Is an AI Receptionist Best Suited To?',
    description: 'A fit guide for sole traders, small crews and growing trade businesses deciding whether AI call handling will actually help.',
    directAnswer: 'AI reception is best suited to trade businesses that receive useful calls while nobody can reliably answer, follow a reasonably repeatable intake process and are willing to define their rules. It is less useful when call volume is tiny, every enquiry needs expert judgment immediately, or nobody will act on the captured leads.',
    readMinutes: 7, heroImage: '/blog/trade-crew-routing.webp', heroAlt: 'Small Australian trade crew reviewing calls and jobs together',
    secondaryImage: '/tradie-van-hero.jpg', secondaryAlt: 'Australian tradie beside a work van on the Gold Coast', secondaryCaption: 'Sole traders gain time only when captured enquiries land somewhere they already check and can act on quickly.',
    keyPoints: ['Sole traders can recover calls without answering on the tools.', 'Small crews can route job types to the right person.', 'The strongest fit has both missed demand and a clear follow-up owner.'],
    sections: [
      { heading: 'Strong fit: the sole trader with regular interruptions', paragraphs: ['If one person sells, quotes, drives and does the work, every call competes with safety and productivity. Missed-call recovery can capture the enquiry until the tradie reaches a sensible stopping point.'] },
      { heading: 'Strong fit: the small crew with one shared number', paragraphs: ['A crew may need different rules for service work, projects, existing customers and urgent calls. Structured routing reduces the “Who spoke to them?” problem and gives each person the same facts.'] },
      { heading: 'Strong fit: the growing business before a full-time hire', paragraphs: ['AI reception can cover gaps and prove the real call workload before the business commits to another wage. It can also sit behind office staff for busy periods and after hours.'] },
      { heading: 'Weak fit: nobody owns the next step', paragraphs: ['Capturing more leads does not help if they sit untouched. One named person must review alerts, return qualified calls and keep statuses current. Automation without that human loop simply creates a tidier backlog.'] },
      { heading: 'Weak fit: the call cannot be safely standardised', paragraphs: ['If nearly every caller needs immediate expert advice or a sensitive relationship decision, a human-led service may be the right answer. The assistant can still take a basic message, but should not be stretched into work it cannot safely perform.'] },
    ],
    example: { title: 'A two-person plumbing business', text: 'One plumber is on the tools; the other moves between quoting and jobs. TradieRelay handles missed and after-hours new enquiries, captures service area and urgency, and alerts the on-call person for approved urgent cases. Existing-customer complaints still route to a human.' },
    productVisual: 'pipeline', productCaption: 'The pipeline separates jobs that need a person from jobs waiting on the customer or already booked.',
    checklist: ['Count genuine new-job calls for two weeks.', 'Record how many are missed or delayed.', 'Name the person who will own each captured lead.', 'List repeatable intake questions.', 'List calls that must stay human.', 'Decide whether the likely recovered work justifies the service cost.'],
    faqs: [{ question: 'Is it useful for a brand-new trade business?', answer: 'It can be, but first make sure there is enough call demand and a clear offer. AI reception does not create demand by itself.' }, { question: 'Is it only for sole traders?', answer: 'No. Small teams can use multi-person routing and different job-type rules, while larger teams may use it for overflow and after-hours coverage.' }, { question: 'What if most customers book online?', answer: 'Phone recovery may be a smaller priority. Measure the real call volume and value before adding a system.' }],
    related: ['does-ai-receptionist-replace-office-staff', 'how-small-trade-business-handle-several-calls', 'how-track-missed-calls-costing-jobs'],
  },
  {
    slug: 'does-ai-receptionist-replace-office-staff', number: 6, category: 'AI receptionist basics',
    title: 'Does an AI Receptionist Replace Your Office Staff?',
    description: 'How AI reception can support a trade office, where human staff add more value and when a hire still makes sense.',
    directAnswer: 'Usually, no. An AI receptionist is best used to cover repeatable intake, overflow, missed calls and after-hours gaps. Office staff still handle relationships, exceptions, scheduling conflicts, complaints, supplier coordination and commercial judgment. The practical question is which low-value interruptions can be removed from their day.',
    readMinutes: 7, heroImage: '/tradie-day-done.jpg', heroAlt: 'Australian trade business owner reviewing the day after work',
    secondaryImage: '/blog/trade-crew-routing.webp', secondaryAlt: 'Trade team working together on call routing and jobs', secondaryCaption: 'A useful setup gives routine capture to the system and keeps customer judgment with the people who know the business.',
    keyPoints: ['Use AI for repetitive capture and coverage gaps.', 'Use people for relationships, exceptions and judgment.', 'Measure work removed—not just calls answered.'],
    sections: [
      { heading: 'What AI can take off the office plate', bullets: ['Repeating the same intake questions', 'Covering simultaneous or after-hours calls', 'Collecting job photos and access details', 'Sorting obvious service-area and job-type mismatches', 'Sending the first operational update on an active enquiry'] },
      { heading: 'Where office staff remain stronger', bullets: ['Reassuring a frustrated long-term customer', 'Resolving a diary clash across several jobs', 'Chasing suppliers and coordinating materials', 'Handling payment or scope disputes', 'Recognising exceptions that deserve special treatment'] },
      { heading: 'Three workable staffing patterns', paragraphs: ['For a sole trader, AI can cover calls until there is enough volume for help. In a small office, it can act as overflow so staff answer the calls needing a person. In a growing business, it can handle first-line intake while an administrator manages confirmed work and exceptions.'] },
      { heading: 'Do not automate a broken hand-off', paragraphs: ['If nobody knows who returns a lead, adding AI will not fix ownership. Decide where each call type lands, when it becomes overdue and who steps in. The system should make human work clearer, not spray notifications at everyone.'], callout: { label: 'GOOD DISPLACEMENT', text: 'The win is not “we added AI”. The win is “our office stopped retyping details and chasing incomplete messages”.' } },
      { heading: 'When a person may still be the better investment', paragraphs: ['If the business needs full-day scheduling, customer care, supplier coordination and bookkeeping, that is a real role—not a phone-answering problem. AI may still support the hire, but it should not be used to avoid staffing work that clearly needs a person.'] },
    ],
    example: { title: 'Overflow for a busy office coordinator', text: 'Emma answers calls and schedules a three-person HVAC crew. When she is already on a call, TradieRelay captures the next enquiry and labels it for callback. Emma returns with the job facts in front of her instead of a voicemail. Complaints and existing commercial accounts still come to her directly.' },
    productVisual: 'pipeline', productCaption: 'The working product groups captured work by the human action it needs next.',
    table: { headers: ['Work', 'AI role', 'Human role'], rows: [['New enquiry', 'Capture and qualify', 'Approve next step'], ['Overflow', 'Answer and summarise', 'Return priority calls'], ['Scheduling', 'Offer only approved windows', 'Resolve conflicts'], ['Complaint', 'Recognise and hand over', 'Listen and decide']] },
    checklist: ['List the office tasks people repeat daily.', 'Separate capture work from judgment work.', 'Choose overflow and after-hours coverage first.', 'Name one owner for captured leads.', 'Track whether admin re-entry and interruptions fall.', 'Review the design with the person doing the office work.'],
    faqs: [{ question: 'Can office staff take over a live call?', answer: 'A configured transfer or callback rule can hand a call to a person. The business decides which call types deserve that option.' }, { question: 'Will staff have to use another inbox?', answer: 'The best setup uses the existing operating channel where possible and keeps the full job in TradieRelay for review. Avoid parallel queues nobody checks.' }, { question: 'Can AI cover staff leave?', answer: 'It can extend call coverage, but the business still needs a person accountable for decisions and follow-up during the leave period.' }],
    related: ['who-is-ai-receptionist-best-suited-to', 'what-is-overflow-call-answering', 'how-small-trade-business-handle-several-calls'],
  },
  {
    slug: 'can-ai-receptionist-use-business-name-and-rules', number: 7, category: 'AI receptionist basics',
    title: 'Can an AI Receptionist Use Your Business Name and Call Rules?',
    description: 'How to make an AI receptionist sound like it belongs to your trade business without letting it invent answers or pretend to be a person.',
    directAnswer: 'Yes. An AI receptionist can answer in your business name and follow your approved wording, service area, job preferences, routing, hours and escalation rules. It should also identify itself as automated. Personalisation should come from saved business facts—not from giving the AI permission to make things up.',
    readMinutes: 7, heroImage: '/tradie-van-hero.jpg', heroAlt: 'Australian tradie beside a branded work van',
    secondaryImage: '/blog/tradierelay-call-rules.png', secondaryAlt: 'TradieRelay call rules screen', secondaryCaption: 'TradieRelay keeps the operating rules visible so the business can review how a call will be handled.',
    keyPoints: ['Use the real business name and plain language.', 'Store rules as visible business settings.', 'Keep an AI disclosure and an uncertainty fallback.'],
    sections: [
      { heading: 'What can be personalised', bullets: ['Business name and trading hours', 'Trade, service area and excluded locations', 'Preferred and excluded job types', 'Urgent-job alert recipients', 'Callback, transfer and after-hours rules', 'Approved prices, availability and customer messages when enabled'] },
      { heading: 'The introduction should still be transparent', paragraphs: ['A useful opening can sound natural without pretending. For example: “Thanks for calling GC Plumbing. You’re speaking with our automated assistant. I can take a few details so the team can help.” That tells the caller who answered, what it is and why continuing is useful.'] },
      { heading: 'Rules should be facts, not vague instructions', paragraphs: ['“Be helpful” is not a call rule. “We service these suburbs, never quote by phone and alert Noah for these urgent job types” is. Specific rules are easier to test, easier to change and less likely to create a surprising promise.'] },
      { heading: 'Different call types can follow different paths', paragraphs: ['A new plumbing enquiry may ask for a suburb and photo. An existing booking may ask for the job reference and requested change. A supplier call may take a message. The business can keep those paths separate rather than forcing every caller through the same script.'] },
      { heading: 'The business remains accountable for the setup', paragraphs: ['Someone must approve the wording, test the routes and update the rules when hours, service areas, prices or staff change. The AI cannot know that a staff member is away or a product is unavailable unless the source is updated.'], callout: { label: 'OWNER', text: 'Give one named person responsibility for rule accuracy. Stale rules create confident, wrong answers.' } },
    ],
    example: { title: 'GC Plumbing’s first rule set', text: 'The greeting names GC Plumbing and discloses the automated assistant. New missed calls are captured; urgent approved job types alert the on-call plumber; prices are never given by phone; and unclear answers switch to message capture after two failed questions. These are the rules shown in the working demo.' },
    productVisual: 'rules', productCaption: 'The working TradieRelay rules view: answer mode, disclosure, pricing, fallback and urgent alerts are all visible.',
    checklist: ['Write the exact business name callers know.', 'Choose a clear AI disclosure.', 'List service areas and exclusions.', 'List approved and human-only actions.', 'Name every route recipient.', 'Set a monthly rule review and update rules immediately after operational changes.'],
    faqs: [{ question: 'Can the greeting sound Australian?', answer: 'Yes. The wording and voice can be chosen for the audience, but clarity matters more than slang or impersonation.' }, { question: 'Can it use different rules for different trades?', answer: 'Yes. A multi-service business can configure separate questions and routes by job type, provided the caller can be reliably placed in the right lane.' }, { question: 'Can I turn off automatic pricing?', answer: 'Yes. TradieRelay’s current demo rule is “never” for prices by phone, leaving price decisions with the tradie.' }],
    sources: [{ label: 'OAIC guidance on transparency and AI', url: 'https://www.oaic.gov.au/privacy/privacy-guidance-for-organisations-and-government-agencies/guidance-on-privacy-and-the-use-of-commercially-available-ai-products' }],
    related: ['what-can-ai-receptionist-do-and-never-do', 'ai-receptionist-setup-checklist-australian-tradies', 'busy-no-answer-after-hours-which-call-rule'],
  },
  {
    slug: 'what-happens-when-ai-does-not-know-answer', number: 8, category: 'AI receptionist basics',
    title: 'What Happens When the AI Does Not Know the Answer?',
    description: 'The fallback rules every trade business should have for unclear callers, unknown questions and information the AI cannot safely provide.',
    directAnswer: 'When the AI does not know, it should say so plainly, avoid guessing and move to an approved fallback: repeat the question, confirm the detail, take a message, request a photo, transfer the call or arrange a human callback. The fallback must be designed before the service goes live.',
    readMinutes: 7, heroImage: '/customer-call.jpg', heroAlt: 'Australian homeowner explaining a job by phone',
    secondaryImage: '/blog/tradierelay-call-rules.png', secondaryAlt: 'TradieRelay failed-question fallback rule', secondaryCaption: 'In the working demo, two failed questions switch the call into message mode instead of repeating forever.',
    keyPoints: ['Uncertainty should be visible, not hidden.', 'Important details need confirmation or human review.', 'Every unknown question needs a safe exit path.'],
    sections: [
      { heading: 'There are several kinds of “I don’t know”', bullets: ['The audio was unclear', 'The caller’s answer did not match the question', 'The caller asked for information that is not saved', 'The request falls outside the approved service', 'The decision needs technical or commercial judgment'] },
      { heading: 'First, try a simple clarification', paragraphs: ['The assistant can ask the caller to repeat one detail or confirm what it heard: “Was that Burleigh Waters?” For phone numbers and addresses, a repeat-back is especially useful. The clarification should not become an endless loop.'] },
      { heading: 'Then use the approved fallback', paragraphs: ['After the configured number of failed attempts, TradieRelay can switch to message mode, offer a callback, request supporting information or route to a person. The caller should hear what will happen next and when the business expects to review the message.'] },
      { heading: 'Unknown business questions should not trigger invention', paragraphs: ['If the caller asks for a price, product warranty, technician arrival time or advice that is not in an approved source, the assistant records the question for a human. A confident guess is more damaging than a short, useful hand-off.'], callout: { label: 'SAFE PHRASE', text: '“I don’t have an approved answer for that, but I can add it to the job for the team to review.”' } },
      { heading: 'The tradie should see what is uncertain', paragraphs: ['Captured information should be labelled as AI-collected and anything uncertain should be reviewable against the recording or caller’s message. That keeps the human decision-maker aware of the system’s limits.'] },
    ],
    example: { title: 'A street name the system cannot confirm', text: 'A caller gives a street name twice, but the audio remains unclear. TradieRelay confirms the suburb, marks the address detail as uncertain and asks the caller to reply to the follow-up text with the correct address. The tradie sees the gap instead of receiving a fabricated street.' },
    productVisual: 'lead', productCaption: 'The qualified-job view labels the information as AI-captured and tells the tradie to check anything uncertain.',
    checklist: ['Set the maximum clarification attempts.', 'Write a message-mode fallback.', 'Create separate hand-offs for price, safety, complaints and unknown job types.', 'Confirm phone numbers and service locations.', 'Show uncertainty in the human review screen.', 'Include unknown-answer tests in every launch check.'],
    faqs: [{ question: 'Can the AI transfer every difficult call?', answer: 'It can transfer only when a person is available and the route is approved. Otherwise it should set a clear callback expectation.' }, { question: 'What if the caller refuses to speak with AI?', answer: 'The flow should offer an approved human alternative such as a callback or message rather than forcing the conversation.' }, { question: 'Will it learn the right answer automatically?', answer: 'Business rules should not silently change from one caller’s statement. A person should review and approve new facts before they become reusable answers.' }],
    sources: [{ label: 'Australian Government Voluntary AI Safety Standard', url: 'https://www.industry.gov.au/publications/voluntary-ai-safety-standard' }],
    related: ['can-ai-really-answer-calls-for-trade-business', 'can-ai-receptionist-handle-australian-accents', 'what-can-ai-receptionist-do-and-never-do'],
  },
  {
    slug: 'can-ai-receptionist-handle-australian-accents', number: 9, category: 'AI receptionist basics',
    title: 'Can an AI Receptionist Handle Australian Accents?',
    description: 'What Australian tradies should expect from voice recognition, including names, suburbs, noisy calls and the checks that reduce errors.',
    directAnswer: 'AI voice systems can understand many Australian accents, but no system will hear every caller perfectly—especially with road noise, poor reception, uncommon names or local suburb pronunciations. A dependable setup confirms important details, allows correction and sends unclear information to a human instead of guessing.',
    readMinutes: 7, heroImage: '/blog/after-hours-customer-call.webp', heroAlt: 'Australian homeowner speaking on the phone from a Queensland veranda',
    secondaryImage: '/customer-call.jpg', secondaryAlt: 'Customer speaking clearly during a trade enquiry', secondaryCaption: 'Call quality, background noise and the words being captured affect recognition as much as accent.',
    keyPoints: ['Accent handling is not a yes-or-no feature.', 'Names, addresses and phone numbers deserve repeat-back.', 'Noisy or unclear calls need a fast fallback.'],
    sections: [
      { heading: 'What makes a call harder to understand', bullets: ['Traffic, wind, machinery or children in the background', 'Speakerphone echo or weak mobile reception', 'Fast speech and several details in one sentence', 'Uncommon names, business names and street names', 'Local abbreviations and suburb pronunciations'] },
      { heading: 'Design the question for the phone', paragraphs: ['Short prompts perform better than multi-part questions. Ask for the suburb, then the job, then the timing. Do not make the caller remember a long list of things to answer at once.'] },
      { heading: 'Confirm what matters', paragraphs: ['For contact numbers, suburbs and service addresses, the assistant can repeat the captured detail and ask the caller to correct it. A follow-up text gives the caller another way to fix spelling or send the full address.'] },
      { heading: 'Do not judge callers by the transcript alone', paragraphs: ['A strange transcript may reflect the phone connection, not the caller. During testing, compare the recording, summary and caller correction. Build a list of business names, suburbs and trade terms that the system needs to recognise.'] },
      { heading: 'Have a polite escape route', paragraphs: ['If the system fails to understand after the configured attempts, it should apologise once, switch to message capture or arrange a human callback. Repeating the same question five times damages trust.'], callout: { label: 'DESIGN FOR REALITY', text: 'The target is not perfect transcription. It is enough confirmed information for a person to take the right next step.' } },
    ],
    example: { title: 'Confirming a Gold Coast suburb', text: 'A caller says “Currumbin Waters” over road noise. TradieRelay repeats the suburb and asks for confirmation. When the caller corrects it to “Burleigh Waters”, the corrected value is attached to the job. If the confirmation still fails, the text follow-up asks for the service address in writing.' },
    productVisual: 'lead', productCaption: 'The job screen separates captured fields such as suburb and best time so the tradie can check them quickly.',
    checklist: ['Test at least ten local suburb names.', 'Test from a van, workshop and quiet room.', 'Include different ages and Australian accents.', 'Confirm names, numbers and addresses.', 'Set a two-attempt fallback.', 'Review errors without blaming the caller.'],
    faqs: [{ question: 'Can it understand broad Australian accents?', answer: 'Often, but performance varies by speaker, audio quality and vocabulary. Test the actual service with local callers before relying on it.' }, { question: 'Can we add local place names?', answer: 'The setup can include the business’s service suburbs and common trade vocabulary, which helps the system ask and confirm the right details.' }, { question: 'What about customers who speak English as a second language?', answer: 'Use simple questions, avoid idioms and provide a human or text fallback. Do not assume understanding from accent alone.' }],
    related: ['what-happens-when-ai-does-not-know-answer', 'how-does-an-ai-receptionist-handle-a-tradie-call', 'ai-receptionist-setup-checklist-australian-tradies'],
  },
  {
    slug: 'ai-receptionist-setup-checklist-australian-tradies', number: 10, category: 'AI receptionist basics',
    title: 'AI Receptionist Setup Checklist for Australian Tradies',
    description: 'A step-by-step launch checklist covering call forwarding, business rules, privacy, testing, alerts and the first two weeks.',
    directAnswer: 'A safe setup starts with one narrow call condition, an approved introduction, clear service and escalation rules, a named lead owner, tested fallback paths and visible privacy information. Test real call scenarios before launch, then review every captured lead during the first fortnight.',
    readMinutes: 10, heroImage: '/blog/trade-crew-routing.webp', heroAlt: 'Australian trade business owners configuring a call system together',
    secondaryImage: '/blog/tradierelay-call-rules.png', secondaryAlt: 'TradieRelay call rules configuration screen', secondaryCaption: 'The live operating rules should be easy for the business and operator to inspect—not buried in technical code.',
    keyPoints: ['Start with missed or after-hours calls.', 'Write down what the assistant may and may not do.', 'Test the ugly cases before a real customer finds them.'],
    sections: [
      { heading: '1. Decide the first job the system will do', paragraphs: ['Choose one clear outcome such as “capture missed new-job calls”. Do not start with every call type, automatic booking, quoting and follow-up at once. A narrow launch makes mistakes easier to spot and fix.'] },
      { heading: '2. Map the number and call condition', paragraphs: ['Decide whether the existing mobile or business number forwards on no answer, busy, unreachable, after hours or all calls. Confirm the ring time and make sure voicemail does not answer before the forwarding rule.'] },
      { heading: '3. Approve the caller experience', bullets: ['Business-name greeting', 'Automated-assistant disclosure', 'Essential qualification questions', 'Photo request wording', 'Callback or next-step promise', 'Human request, urgent case and failed-question fallbacks'] },
      { heading: '4. Configure the human hand-off', paragraphs: ['Name the person who gets normal leads, urgent leads and existing-customer issues. Set what happens when that person is unavailable. Decide how quickly each lead type should be reviewed.'] },
      { heading: '5. Test, launch narrowly and review', paragraphs: ['Run in-area, out-of-area, urgent, unclear, silent, price, complaint, photo and human-request calls. After launch, compare what the caller said with what the job shows. Tighten questions and rules before expanding coverage.'], callout: { label: 'FIRST FORTNIGHT', text: 'Review every real call, correction and missed hand-off. This is where a generic script becomes your operating system.' } },
    ],
    example: { title: 'A cautious first launch', text: 'GC Plumbing forwards no-answer and after-hours new enquiries to TradieRelay. AI disclosure is on, phone pricing is off, urgent jobs alert the on-call plumber and two failed questions switch to message mode. The team tests ten scenarios before sending real traffic.' },
    productVisual: 'rules', productCaption: 'TradieRelay’s working demo displays the chosen call and safety rules in one reviewable screen.',
    table: { headers: ['Before launch', 'Owner', 'Proof it works'], rows: [['Number forwarding', 'Business owner/operator', 'Test call reaches the assistant at the right time'], ['Call rules', 'Business owner', 'Expected route for every test scenario'], ['Lead alerts', 'Named responder', 'Alert arrives and opens the correct job'], ['Privacy and disclosure', 'Business owner', 'Caller hears disclosure and can find privacy information']] },
    checklist: ['Choose one starting call condition.', 'Confirm number ownership and forwarding access.', 'Approve greeting and AI disclosure.', 'Document services, suburbs and exclusions.', 'Set urgent, human and failed-question fallbacks.', 'Choose alert recipients and response targets.', 'Add a privacy notice and data-retention decision.', 'Run at least ten launch tests.', 'Review every call for the first two weeks.', 'Set a keep, change or stop review date.'],
    faqs: [{ question: 'Do I need a new phone number?', answer: 'Not necessarily. Many businesses keep their normal number and use conditional call forwarding to the service.' }, { question: 'How long does setup take?', answer: 'The technical connection can be quick, but the important work is approving rules and testing. The time depends on how many trades, staff and call paths are included.' }, { question: 'Should recording be turned on?', answer: 'Only with the right disclosure, purpose, access controls and retention decision. The business should understand its obligations before recording callers.' }],
    sources: [{ label: 'Telstra guide to mobile call forwarding', url: 'https://www.telstra.com.au/small-business/online-support/mobiles-devices/forward-calls-on-mobile' }, { label: 'OAIC guidance on privacy and AI', url: 'https://www.oaic.gov.au/privacy/privacy-guidance-for-organisations-and-government-agencies/guidance-on-privacy-and-the-use-of-commercially-available-ai-products' }, { label: 'Australian Government Voluntary AI Safety Standard', url: 'https://www.industry.gov.au/publications/voluntary-ai-safety-standard' }],
    related: ['can-ai-receptionist-use-business-name-and-rules', 'busy-no-answer-after-hours-which-call-rule', 'what-is-an-ai-receptionist-for-tradies'],
  },
  {
    slug: 'what-happens-after-tradie-misses-call', number: 11, category: 'Missed-call recovery',
    title: 'What Should Happen After a Tradie Misses a Call?',
    description: 'A simple missed-call recovery flow that gives the customer a fast response and gives the tradie enough information to act.',
    directAnswer: 'After a missed trade call, the customer should quickly hear from the business, know what information is needed and understand the next step. The best flow either answers under a no-answer rule or sends an operational text-back, captures the job details, requests evidence when useful and alerts the right person for review.',
    readMinutes: 8, heroImage: '/missed-call-plumber.jpg', heroAlt: 'Australian plumber unable to answer a phone while working',
    secondaryImage: '/blog/tradierelay-dashboard.png', secondaryAlt: 'TradieRelay working dashboard with recovered job and photo', secondaryCaption: 'A recovered call should become one job with the summary, caller details, urgency and photos together.',
    keyPoints: ['A missed call needs a response, not just a notification.', 'Capture enough context before the callback.', 'Keep the call, text, photos and decision on one job.'],
    sections: [
      { heading: 'Step 1: acknowledge the enquiry', paragraphs: ['The caller should not be left wondering whether the number works. Conditional forwarding can let the assistant answer when the tradie does not. A text-back can be used as a fallback for a missed inbound enquiry, using the business name and a clear purpose.'] },
      { heading: 'Step 2: find out what the job is', paragraphs: ['Collect the name, callback number, suburb, job type and plain-English problem. Ask only the urgency questions the business approved. A missed-call system that only sends “We missed you” still leaves the tradie calling blind.'] },
      { heading: 'Step 3: request useful evidence', paragraphs: ['For selected jobs, tell the caller that a secure photo link is coming by text. In TradieRelay, up to six photos can be uploaded and attached to the same job. Photos assist triage; they do not replace inspection or diagnosis.'] },
      { heading: 'Step 4: route by the business rule', bullets: ['Immediate alert for approved urgent cases', 'Normal callback queue for suitable new work', 'Existing-customer route for booking changes or issues', 'Polite response for excluded job types or areas', 'Human review when the answer is uncertain'] },
      { heading: 'Step 5: close the loop', paragraphs: ['Tell the customer whether the business will review, call back, offer a time or needs more information. Then keep replies and status changes attached to the original enquiry.'], callout: { label: 'CLOSED LOOP', text: 'A lead is not recovered when the text is sent. It is recovered when a person makes and records the next decision.' } },
    ],
    example: { title: 'The missed call that arrives as a useful job', text: 'Sarah calls at 2:14pm while the plumber is busy. TradieRelay answers after the no-answer rule, captures a burst flexi hose in Burleigh Waters, records that Sarah says the mains are off, requests a photo and sends an urgent alert. The tradie opens one complete job instead of returning an unknown number.' },
    productVisual: 'alert', productCaption: 'The native product preview shows the urgent lead alert with the job, suburb, isolation status and photo count.',
    checklist: ['Choose answer or text-back as the first recovery action.', 'Identify the business in every message.', 'Capture the five essential job facts.', 'Define urgent and excluded cases.', 'Request photos only where they help.', 'Assign the callback owner and track the outcome.'],
    faqs: [{ question: 'Should I call every missed number back?', answer: 'You can, but qualified context helps you return the right calls first and avoid blind callbacks to suppliers, spam or out-of-area enquiries.' }, { question: 'Can the customer reply by text?', answer: 'Yes. A well-designed flow keeps the reply on the same enquiry and makes clear what information the customer should send.' }, { question: 'What if the customer calls again?', answer: 'The system should match the call to the existing enquiry where possible rather than creating a duplicate job.' }],
    sources: [{ label: 'Telstra guide to mobile call forwarding', url: 'https://www.telstra.com.au/small-business/online-support/mobiles-devices/forward-calls-on-mobile' }, { label: 'ACMA guidance on avoiding spam', url: 'https://www.acma.gov.au/avoid-sending-spam' }],
    related: ['how-quickly-respond-missed-trade-enquiry', 'best-missed-call-text-back-message-tradies', 'how-track-missed-calls-costing-jobs'],
  },
  {
    slug: 'how-quickly-respond-missed-trade-enquiry', number: 12, category: 'Missed-call recovery',
    title: 'How Quickly Should You Respond to a Missed Trade Enquiry?',
    description: 'A practical response-time framework for urgent, normal, after-hours and quote calls—without making promises your crew cannot keep.',
    directAnswer: 'A missed enquiry should be acknowledged as soon as the system can do it reliably, but the human callback time should match the job and your real capacity. Urgent approved cases need immediate alerts; normal leads need a clear review window; after-hours callers need an honest expectation. Never promise attendance just to sound fast.',
    readMinutes: 7, heroImage: '/blog/plumber-missed-call.webp', heroAlt: 'Plumber working while a customer call rings nearby',
    secondaryImage: '/blog/tradierelay-dashboard.png', secondaryAlt: 'TradieRelay dashboard sorting urgent and normal leads', secondaryCaption: 'Priority is useful only when it is visible and tied to a named human response.',
    keyPoints: ['Acknowledge quickly; promise cautiously.', 'Different calls need different response targets.', 'Measure the time to a real decision, not only the automated reply.'],
    sections: [
      { heading: 'Separate acknowledgement from human response', paragraphs: ['An automated answer or text can confirm that the enquiry reached the business. That is not the same as a tradie accepting the job. Use wording such as “The team will review this” unless a real booking or attendance commitment exists.'] },
      { heading: 'Set response lanes', bullets: ['Urgent by approved rule: immediate alert to the on-call person', 'Suitable new job: review within the business’s stated working window', 'Quote follow-up: respond based on the agreed follow-up plan', 'Existing booking issue: route to the person managing the diary', 'After hours: acknowledge now and state when review resumes'] },
      { heading: 'Make the target achievable', paragraphs: ['A five-minute callback promise sounds good until the only plumber is under a house. Choose a target the business can meet on normal days, then create an escalation if the lead goes untouched.'] },
      { heading: 'Prioritise using facts, not emotion alone', paragraphs: ['A caller may describe every job as urgent. Use approved indicators, job type, service area and timing to mark the lead, while leaving technical assessment to the tradie.'] },
      { heading: 'Track the complete response', paragraphs: ['Measure time from first call to acknowledgement, qualified record and human decision. A two-second text is not a success if nobody opens the job for two days.'], callout: { label: 'BETTER METRIC', text: 'Track “time to first useful human action”, not only “time to automated reply”.' } },
    ],
    example: { title: 'Three calls, three sensible targets', text: 'A burst hose triggers an immediate urgent alert. A deck quote received at 3pm enters the normal callback queue for same-day review. An air-conditioning enquiry at 9:30pm is acknowledged immediately and told the team reviews normal jobs from 7am. Nobody is promised attendance before a person checks.' },
    productVisual: 'pipeline', productCaption: 'The action pipeline separates work needing a decision from enquiries waiting on the customer or already booked.',
    table: { headers: ['Call type', 'Automatic response', 'Human target'], rows: [['Approved urgent', 'Immediate acknowledgement and alert', 'On-call person reviews now'], ['Normal new job', 'Capture and confirm review', 'Within stated business window'], ['After hours', 'Capture and set expectation', 'Next staffed period'], ['Existing booking', 'Capture change or issue', 'Diary owner reviews']] },
    checklist: ['Set one realistic target per call lane.', 'Name the human owner.', 'Write acknowledgement separately from attendance.', 'Escalate untouched urgent leads.', 'Track time to human action.', 'Review targets against actual crew capacity.'],
    faqs: [{ question: 'Is an instant text enough?', answer: 'No. It reassures the caller, but the business still needs to review and act on the enquiry.' }, { question: 'Should urgent callers be transferred?', answer: 'Only when an approved on-call person is available. Otherwise send an immediate alert and use clear emergency wording where applicable.' }, { question: 'What should after-hours callers hear?', answer: 'Tell them their details are being captured and when the business normally reviews non-urgent enquiries. Avoid pretending someone is on the way.' }],
    related: ['what-happens-after-tradie-misses-call', 'how-tradies-handle-after-hours-calls', 'how-track-missed-calls-costing-jobs'],
  },
  {
    slug: 'how-much-could-missed-call-be-worth', number: 13, category: 'Missed-call recovery',
    title: 'How Much Could a Missed Call Be Worth to Your Business?',
    description: 'A no-hype calculator for estimating missed-call opportunity using your own call volume, job conversion, average job value and margin.',
    directAnswer: 'There is no honest fixed dollar value for a missed tradie call. Estimate it from your own numbers: missed genuine enquiries × likely qualification rate × win rate × average job revenue. For profit, multiply the result by gross margin. Use a low, middle and high case rather than treating every missed call as a lost job.',
    readMinutes: 9, heroImage: '/tradie-day-done.jpg', heroAlt: 'Trade business owner reviewing calls and jobs at the end of the day',
    secondaryImage: '/blog/tradierelay-dashboard.png', secondaryAlt: 'TradieRelay jobs dashboard for tracking lead outcomes', secondaryCaption: 'To improve the estimate, record whether each captured call became unsuitable, quoted, booked, won or lost.',
    keyPoints: ['Use your own enquiries and job values.', 'Count only genuine opportunities.', 'Compare recovered gross profit with the full service cost.'],
    sections: [
      { heading: 'The basic opportunity formula', paragraphs: ['Monthly opportunity revenue = genuine missed enquiries × qualification rate × win rate × average job revenue. Example inputs are useful for testing the maths, but they are not a promise about your business.'] },
      { heading: 'Start with genuine enquiries', paragraphs: ['Remove spam, suppliers, existing-customer administration, wrong numbers and work you never accept. A high missed-call count can look impressive while hiding very little saleable demand.'] },
      { heading: 'Use a qualification rate and a win rate', paragraphs: ['Not every genuine enquiry fits your area, job type, timing or capacity. Of the suitable leads, not every quote or callback becomes paid work. Keep those two stages separate so the estimate stays credible.'] },
      { heading: 'Revenue is not profit', paragraphs: ['A $2,000 job may include materials, subcontractors and labour. Multiply the estimated recovered revenue by your gross-margin percentage to compare it with the cost of call handling and follow-up.'] },
      { heading: 'Run three scenarios', paragraphs: ['Use conservative, expected and strong assumptions. If the service only makes sense in the strongest case, the decision is fragile. If it pays back in the conservative case, test it against real results for a defined period.'], callout: { label: 'NO HYPE', text: 'Do not count every missed call as a lost job. Count only the additional work the recovery process can reasonably influence.' } },
    ],
    example: { title: 'A worked example using assumptions', text: 'Suppose a business logs 30 genuine missed enquiries in a month. If 50% fit the business, 40% of those become jobs and average job revenue is $600, the opportunity estimate is 30 × 0.50 × 0.40 × $600 = $3,600 revenue. At a 45% gross margin, that is $1,620 gross profit. Replace every assumption with your actual data.' },
    productVisual: 'pipeline', productCaption: 'Outcome statuses in the working product create the raw data needed to replace assumptions with actual conversion.',
    table: { headers: ['Scenario', 'Genuine enquiries', 'Fit × win', 'Average revenue', 'Estimated revenue'], rows: [['Conservative', '20', '35% × 30%', '$500', '$1,050'], ['Expected example', '30', '50% × 40%', '$600', '$3,600'], ['Strong', '40', '60% × 50%', '$750', '$9,000']] },
    checklist: ['Log every missed inbound call for four weeks.', 'Mark genuine versus non-opportunity.', 'Record fit, quote, booking and win outcomes.', 'Calculate average revenue by job type.', 'Use gross margin, not only revenue.', 'Compare actual recovered profit with service and labour cost.'],
    faqs: [{ question: 'What average job value should I use?', answer: 'Use collected revenue from comparable jobs, not the biggest project on the books. Separate service calls from large projects if their values differ widely.' }, { question: 'Should repeat customers count?', answer: 'Include them when a missed call could affect paid work, but separate service and retention value from new-customer acquisition.' }, { question: 'How long should I measure?', answer: 'Four weeks gives a starting view, but seasonal trades should compare several periods before making a long-term assumption.' }],
    related: ['how-track-missed-calls-costing-jobs', 'what-happens-after-tradie-misses-call', 'how-quickly-respond-missed-trade-enquiry'],
  },
  {
    slug: 'best-missed-call-text-back-message-tradies', number: 14, category: 'Missed-call recovery',
    title: 'The Best Missed-Call Text-Back Message for Tradies',
    description: 'A practical SMS template for an inbound missed call, plus the wording, consent and follow-up mistakes to avoid in Australia.',
    directAnswer: 'A useful missed-call text-back identifies the business, says why the message was sent, asks for only the details needed and explains the next step. Example: “Hi, it’s GC Plumbing. Sorry we missed your call. Reply with your name, suburb and what you need help with, and we’ll review it as soon as we can.” Do not promise a time you cannot meet.',
    readMinutes: 8, heroImage: '/blog/after-hours-customer-call.webp', heroAlt: 'Australian customer receiving a trade business follow-up on a mobile phone',
    secondaryImage: '/blog/tradierelay-photo-request.png', secondaryAlt: 'Secure TradieRelay photo upload link after a missed call', secondaryCaption: 'When a photo is useful, send a clear secure upload request after the customer has described the job.',
    keyPoints: ['Name the business immediately.', 'Ask for three useful details, not an essay.', 'Keep operational recovery separate from marketing.'],
    sections: [
      { heading: 'A strong base message', paragraphs: ['“Hi, it’s [Business]. Sorry we missed your call. Reply with your name, suburb and what you need help with, and we’ll review it [realistic timeframe]. If it’s an immediate danger, contact the appropriate emergency service.” Adapt the final sentence to your trade and approved safety wording.'] },
      { heading: 'Why each line matters', bullets: ['Business name: the customer knows who sent it', 'Missed-call context: the reason for contact is clear', 'Three requested details: the reply is easy', 'Review expectation: no invented attendance promise', 'Emergency wording: the assistant does not act as emergency services'] },
      { heading: 'What not to write', bullets: ['“We’ll be there shortly” when nobody has accepted the job', '“Send photos and we’ll diagnose it”', 'A long list of eight questions', 'A sales promotion unrelated to the missed enquiry', 'A link with no explanation or business identity'] },
      { heading: 'Operational reply versus later marketing', paragraphs: ['A reply to a person who just called the business has a clear service context. If the business later sends promotional electronic messages, Australia’s spam rules can require consent, sender identification and a working unsubscribe facility. Keep the recovery flow focused on the enquiry and obtain proper advice for broader marketing programs.'] },
      { heading: 'Move the reply into one job', paragraphs: ['When the customer replies, attach the message and any photos to the same enquiry. The tradie should not have to reconcile an unknown call, a loose SMS and a separate photo link.'], callout: { label: 'BEST NEXT QUESTION', text: 'Ask only for information that changes what the tradie does next.' } },
    ],
    example: { title: 'A photo request after the first reply', text: 'Sarah replies with her name, Burleigh Waters and “burst hose under the sink”. TradieRelay recognises an approved photo-use case and sends: “Thanks Sarah. A clear photo of the hose and surrounding area may help the plumber review the job. Upload securely here: [link]. Please don’t touch anything unsafe.” The photo attaches to Sarah’s job.' },
    productVisual: 'photo-request', productCaption: 'The actual customer upload screen explains the job, accepts up to six photos and warns the customer not to enter an unsafe area.',
    checklist: ['Identify the business.', 'State that the message follows a missed call.', 'Ask for name, suburb and job.', 'Set an achievable review expectation.', 'Use approved emergency wording.', 'Keep marketing out of operational recovery.', 'Attach replies to the original enquiry.'],
    faqs: [{ question: 'Should I include a booking link?', answer: 'Only if the business wants self-booking for that job type and the calendar is accurate. Otherwise capture the enquiry first.' }, { question: 'Can I send another text if they do not reply?', answer: 'Use a documented, proportionate follow-up rule tied to the active enquiry. Repeated or promotional messages can create spam and trust issues.' }, { question: 'Do I need an unsubscribe line?', answer: 'For commercial electronic marketing, Australian rules generally require a functional unsubscribe. An operational response to a current enquiry is different, but keep it relevant and get advice for your exact use.' }],
    sources: [{ label: 'ACMA: Avoid sending spam', url: 'https://www.acma.gov.au/avoid-sending-spam' }, { label: 'ACMA consent expectations for direct marketing', url: 'https://www.acma.gov.au/articles/2024-06/consent-expectations-businesses-using-direct-marketing' }],
    related: ['what-happens-after-tradie-misses-call', 'how-quickly-respond-missed-trade-enquiry', 'how-tradies-handle-after-hours-calls'],
  },
  {
    slug: 'how-do-you-answer-calls-when-on-tools', number: 15, category: 'Missed-call recovery',
    title: 'How Do You Answer Calls When You Are on the Tools?',
    description: 'Safer, less disruptive ways for Australian tradies to handle business calls while working, driving or speaking with a customer.',
    directAnswer: 'Do not try to answer every call while working. Keep safety and the customer in front of you as the priority. Use conditional call forwarding or overflow answering to capture the enquiry, then return qualified calls at a planned break. Urgent approved cases can alert the right person without making every ring an interruption.',
    readMinutes: 7, heroImage: '/blog/electrician-missed-call.webp', heroAlt: 'Electrician staying focused on safe work while a phone rings nearby',
    secondaryImage: '/missed-call-plumber.jpg', secondaryAlt: 'Plumber working while unable to answer the phone', secondaryCaption: 'The phone should work around the job—not force unsafe or unprofessional interruptions.',
    keyPoints: ['Safety and the current customer come first.', 'Let the system capture context while you work.', 'Return calls from a prioritised list at planned times.'],
    sections: [
      { heading: 'Stop treating every ring as equally urgent', paragraphs: ['An unknown number may be a good lead, a supplier, spam or an existing customer. Answering immediately sacrifices focus before you know which. Structured capture lets the call earn its priority.'] },
      { heading: 'Use no-answer or busy forwarding', paragraphs: ['Let your number ring for a sensible period. If you cannot answer, forward the call to the assistant. When you are already on another call, a busy rule can prevent the second caller from reaching voicemail.'] },
      { heading: 'Choose callback windows in the day', paragraphs: ['Review captured leads at lunch, between jobs and before finishing. Truly urgent approved calls can trigger an immediate alert; normal work waits for the next planned window.'] },
      { heading: 'Give the caller a clear expectation', paragraphs: ['The assistant should not say “someone will call straight back” unless that is true. Tell the caller the business will review the details and state the actual operating window.'] },
      { heading: 'Protect the customer already paying for your time', paragraphs: ['Constant call interruptions make the current customer feel secondary and increase mistakes. A captured lead with context allows a professional response without abandoning the job in front of you.'], callout: { label: 'SIMPLE OPERATING RULE', text: 'Work safely now. Review qualified leads at a named time. Interrupt only for cases you deliberately classify as urgent.' } },
    ],
    example: { title: 'A call during switchboard work', text: 'An electrician is inspecting a switchboard and does not reach for the phone. After the no-answer interval, TradieRelay captures the caller’s suburb, visible problem and callback details. The electrician reviews the qualified job after making the site safe. No diagnosis or attendance promise is made.' },
    productVisual: 'alert', productCaption: 'The hot-lead alert puts the key facts in one short view so a tradie can decide whether the job needs immediate attention.',
    checklist: ['Set a safe no-answer interval.', 'Turn on busy-call handling if calls overlap.', 'Define urgent alert criteria.', 'Schedule two or three lead-review windows.', 'Use hands-free only where safe and lawful; do not qualify jobs while driving.', 'Tell current customers how your call coverage works if needed.'],
    faqs: [{ question: 'Should I use voicemail instead?', answer: 'Voicemail is simple, but it often produces incomplete details. Structured answering can give you more context before the callback.' }, { question: 'Can urgent calls still get through?', answer: 'Yes, under an approved transfer or alert rule. The system should not label every emotional caller as technically urgent.' }, { question: 'What if I prefer to call everyone myself?', answer: 'You still can. The assistant can capture and prioritise without booking or quoting on your behalf.' }],
    related: ['what-is-overflow-call-answering', 'busy-no-answer-after-hours-which-call-rule', 'what-happens-after-tradie-misses-call'],
  },
  {
    slug: 'what-is-overflow-call-answering', number: 16, category: 'Missed-call recovery',
    title: 'What Is Overflow Call Answering?',
    description: 'How overflow answering covers calls your tradie or office team cannot reach, without taking over every call or changing the customer-facing number.',
    directAnswer: 'Overflow call answering is backup coverage. Your normal person or team gets the first chance to answer; if the call is busy, unanswered or exceeds the available lines, the backup service answers and captures the enquiry. It suits businesses that want human answering first but do not want the next caller to reach a dead end.',
    readMinutes: 7, heroImage: '/blog/trade-crew-routing.webp', heroAlt: 'Small Australian trade team managing several calls and jobs',
    secondaryImage: '/blog/tradierelay-call-rules.png', secondaryAlt: 'TradieRelay rule showing missed-call and after-hours answer mode', secondaryCaption: 'Overflow is a routing choice. It should be visible alongside no-answer, busy and after-hours rules.',
    keyPoints: ['Your normal answer path stays first.', 'Backup coverage starts only under chosen conditions.', 'Captured calls need an owner and response target.'],
    sections: [
      { heading: 'Overflow is not the same as answering every call', paragraphs: ['With full answering, the service may receive calls from the first ring. With overflow, your team retains the first opportunity. The backup catches demand when people or lines are occupied.'] },
      { heading: 'Common overflow triggers', bullets: ['The main line is busy', 'Nobody answers within the chosen ring time', 'Several callers arrive at once', 'The office is closed or temporarily unstaffed', 'A named person rejects or cannot take the call'] },
      { heading: 'What the backup should do', paragraphs: ['Identify the business, disclose the automated assistant, find out why the person called and route the result. It should not make the caller repeat the whole story to several systems.'] },
      { heading: 'Where overflow helps most', paragraphs: ['It is useful for small offices during lunch, crews sharing one number, businesses running local advertising and seasonal peaks. It also supports staff without making them race every second ring.'] },
      { heading: 'The hidden risk is an unowned queue', paragraphs: ['If overflow calls land in a separate inbox nobody checks, coverage has only moved the missed call. Put the result in the normal job pipeline, name the owner and track whether the lead receives a decision.'], callout: { label: 'OVERFLOW TEST', text: 'Make two test calls at once. Confirm the second call is answered and that both jobs reach the right person.' } },
    ],
    example: { title: 'The second caller during a booking change', text: 'Emma is speaking with an existing customer when a new plumbing enquiry rings. The busy-call rule sends the second call to TradieRelay. It captures the new job and adds it to Emma’s review queue. The caller receives a useful response without interrupting the first customer.' },
    productVisual: 'pipeline', productCaption: 'Overflow leads land in the same action pipeline as other enquiries rather than creating a separate hidden inbox.',
    checklist: ['Choose who answers first.', 'Set the busy and no-answer triggers.', 'Decide which call types overflow may handle.', 'Route results into the existing job queue.', 'Name the reviewer and response target.', 'Test simultaneous, rejected and unanswered calls.'],
    faqs: [{ question: 'Do customers call a different number?', answer: 'Usually no. Call forwarding or provider routing can send eligible calls to overflow while the customer uses the normal number.' }, { question: 'Can office staff still answer first?', answer: 'Yes. That is the core purpose of overflow: staff answer when available, backup catches the rest.' }, { question: 'Does overflow work after hours?', answer: 'It can, but after-hours rules may use a different greeting, escalation and response expectation.' }],
    sources: [{ label: 'Telstra guide to mobile call forwarding', url: 'https://www.telstra.com.au/small-business/online-support/mobiles-devices/forward-calls-on-mobile' }],
    related: ['busy-no-answer-after-hours-which-call-rule', 'how-small-trade-business-handle-several-calls', 'does-ai-receptionist-replace-office-staff'],
  },
  {
    slug: 'how-tradies-handle-after-hours-calls', number: 17, category: 'Missed-call recovery',
    title: 'How Should Tradies Handle After-Hours Calls?',
    description: 'A practical after-hours design for urgent and normal trade enquiries, including caller expectations, escalation and next-morning follow-up.',
    directAnswer: 'After-hours calls should be split into clear lanes: approved urgent cases alert an on-call person, normal enquiries are captured for the next staffed period, and emergencies are directed using approved wording. The caller should know they are speaking with an automated assistant and should never be told a tradie is coming unless a person has accepted the job.',
    readMinutes: 8, heroImage: '/blog/after-hours-customer-call.webp', heroAlt: 'Queensland homeowner making an after-hours trade call',
    secondaryImage: '/blog/plumber-missed-call.webp', secondaryAlt: 'Plumber unavailable to answer while completing a job', secondaryCaption: 'After-hours coverage should protect the crew’s time while still creating a clear path for genuinely urgent work.',
    keyPoints: ['Define urgent in operational terms.', 'Set a real on-call route or do not promise one.', 'Normal calls get a next-business-period expectation.'],
    sections: [
      { heading: 'Decide whether you offer an after-hours service', paragraphs: ['The system cannot create an on-call capability the business does not have. If nobody attends after hours, say so clearly while still capturing normal enquiries for review.'] },
      { heading: 'Write the urgent lane', paragraphs: ['List the job types and caller statements that trigger an immediate alert. Keep the assistant to approved questions and do not let it diagnose the fault. Name the on-call person and what happens if they do not respond.'] },
      { heading: 'Write the normal lane', paragraphs: ['Capture the job, suburb, contact details and preferred time. Tell the caller when normal review begins. If photos will help, send the secure link without asking the customer to enter an unsafe area.'] },
      { heading: 'Protect the emergency boundary', paragraphs: ['The assistant is not an emergency service. Use clear, approved wording for immediate danger and do not make the caller wait in a long qualification flow. The exact wording should suit the trade and legal context.'] },
      { heading: 'Start the morning with a clean hand-off', paragraphs: ['After-hours jobs should be grouped for review, with urgent alerts separated from normal work. Confirm that every caller has a status and that nothing sits between SMS, voicemail and the dashboard.'], callout: { label: 'PROMISE ONLY WHAT EXISTS', text: '“The team will review this from 7am” is better than “someone will be there soon” when no attendance is confirmed.' } },
    ],
    example: { title: 'Two calls at 9:30pm', text: 'One caller reports a routine air-conditioner service request. TradieRelay captures it for the 7am review. Another caller describes an approved urgent plumbing situation; the system sends an immediate alert to the on-call plumber. In both cases, attendance remains a human decision.' },
    productVisual: 'alert', productCaption: 'Urgent approved cases can generate a concise hot-lead alert, while normal after-hours calls stay in the review queue.',
    table: { headers: ['Lane', 'Caller hears', 'Business action'], rows: [['Immediate danger', 'Approved emergency direction', 'No AI diagnosis'], ['Approved urgent', 'Details captured; review under on-call rule', 'Immediate named alert'], ['Normal enquiry', 'Review resumes at stated time', 'Next-period queue'], ['Existing booking', 'Issue or change captured', 'Diary owner reviews']] },
    checklist: ['State whether after-hours attendance exists.', 'Define urgent indicators and exclusions.', 'Name the on-call person and backup.', 'Write emergency wording.', 'Set the next staffed review time.', 'Test unanswered on-call alerts and next-morning queues.'],
    faqs: [{ question: 'Should every after-hours call alert me?', answer: 'No. That recreates the interruption problem. Alert only the approved urgent lane; queue normal work.' }, { question: 'Can I charge an after-hours fee?', answer: 'If the business has an approved fee and rule, the assistant may communicate it exactly. Do not invent or estimate charges.' }, { question: 'What if I do not offer emergency work?', answer: 'Say so clearly, capture suitable normal work and use approved emergency direction where needed.' }],
    related: ['busy-no-answer-after-hours-which-call-rule', 'how-quickly-respond-missed-trade-enquiry', 'best-missed-call-text-back-message-tradies'],
  },
  {
    slug: 'busy-no-answer-after-hours-which-call-rule', number: 18, category: 'Missed-call recovery',
    title: 'Busy, No Answer or After Hours: Which Call Rule Should You Use?',
    description: 'Compare the main conditional call-forwarding rules and choose a simple starting setup for a sole trader, small crew or staffed office.',
    directAnswer: 'Use no-answer when you want the normal phone to ring first, busy when a second call should not hit voicemail, and after-hours when the business is closed. Many small trade businesses start with no-answer plus after-hours. Add busy or overflow when simultaneous calls are a proven problem. Test carrier and voicemail timing before launch.',
    readMinutes: 8, heroImage: '/tradie-van-hero.jpg', heroAlt: 'Australian tradie managing calls from a work van',
    secondaryImage: '/blog/tradierelay-call-rules.png', secondaryAlt: 'TradieRelay screen displaying selected call rules', secondaryCaption: 'TradieRelay’s demo starts with missed calls plus after hours. The exact carrier forwarding is configured and tested during setup.',
    keyPoints: ['No-answer gives you first chance to pick up.', 'Busy protects callers when you are already on the phone.', 'After-hours uses a separate expectation and escalation design.'],
    sections: [
      { heading: 'No-answer forwarding', paragraphs: ['Your phone rings for the chosen period. If nobody answers, the call forwards to the assistant. This is the easiest starting point for a sole trader who still wants to answer when practical. Watch the interaction with carrier voicemail.'] },
      { heading: 'Busy forwarding', paragraphs: ['When the line is engaged or the provider marks it busy, the next call routes to backup. This is useful for one-number businesses and small offices that receive overlapping calls.'] },
      { heading: 'After-hours forwarding', paragraphs: ['Calls outside the business schedule route to a separate flow. Use different wording for normal review, on-call urgent work and emergencies. Keep public holidays and temporary closures current.'] },
      { heading: 'Unreachable forwarding', paragraphs: ['Some carriers can forward when the device is off or outside coverage. It can protect the business during site blackspots, but test how quickly the carrier decides the phone is unreachable.'] },
      { heading: 'Choose the smallest combination that solves the problem', paragraphs: ['Start with the condition you can explain and measure. Each extra rule creates another edge case: voicemail race, personal calls, duplicate alerts or an unexpected greeting.'], callout: { label: 'COMMON START', text: 'No-answer during business hours + a separate after-hours flow. Add busy once overlapping calls are visible in your data.' } },
    ],
    example: { title: 'A sole trader’s starting setup', text: 'Noah configures GC Plumbing so the normal mobile rings first. After the chosen no-answer interval, TradieRelay answers. From 5pm to 7am, the after-hours flow answers immediately and only approved urgent cases send an on-call alert. Busy forwarding is tested and added later when call data shows overlap.' },
    productVisual: 'rules', productCaption: 'The working product displays the selected answer mode and related safeguards for review.',
    table: { headers: ['Rule', 'Use it when', 'Watch for'], rows: [['No answer', 'You want first chance to pick up', 'Voicemail may answer first'], ['Busy', 'Calls overlap', 'Carrier busy behaviour'], ['After hours', 'The business is closed', 'Holiday and on-call changes'], ['Unreachable', 'Coverage or device availability varies', 'Carrier detection delay']] },
    checklist: ['Check which rules your carrier supports.', 'Choose business hours and holidays.', 'Set the no-answer ring interval.', 'Disable or coordinate voicemail.', 'Test busy and unreachable behaviour.', 'Call from another phone and confirm every route.', 'Re-test after carrier or number changes.'],
    faqs: [{ question: 'Will I need to change carriers?', answer: 'Not necessarily. Many mobile and business services support conditional forwarding, but features and codes vary. Confirm with the current provider.' }, { question: 'How many rings before forwarding?', answer: 'Choose enough time to answer safely without making the caller wait too long. Carrier settings may use seconds rather than ring counts.' }, { question: 'Can I turn the rule off?', answer: 'Yes. Keep the provider instructions and a tested fallback so the business can narrow or stop coverage.' }],
    sources: [{ label: 'Telstra guide to mobile call forwarding', url: 'https://www.telstra.com.au/small-business/online-support/mobiles-devices/forward-calls-on-mobile' }],
    related: ['what-is-overflow-call-answering', 'how-tradies-handle-after-hours-calls', 'ai-receptionist-setup-checklist-australian-tradies'],
  },
  {
    slug: 'how-small-trade-business-handle-several-calls', number: 19, category: 'Missed-call recovery',
    title: 'How Can a Small Trade Business Handle Several Calls at Once?',
    description: 'A simple routing design for overlapping enquiries, including priority, multiple people, overflow and one shared job record.',
    directAnswer: 'A small trade business can handle several calls by separating call answering from human decision-making. Let available staff answer normally, route overlapping calls to overflow, capture each enquiry into one shared job pipeline and alert only the person responsible for that job type or urgency. Do not forward every call to every phone.',
    readMinutes: 8, heroImage: '/blog/trade-crew-routing.webp', heroAlt: 'Small trade team reviewing several incoming jobs',
    secondaryImage: '/blog/tradierelay-dashboard.png', secondaryAlt: 'TradieRelay dashboard showing several jobs with different priorities', secondaryCaption: 'A shared pipeline shows what needs action, what is waiting and what is already booked—without asking everyone to read every message.',
    keyPoints: ['Overflow catches the second call.', 'Routing sends the job to one accountable person.', 'A shared pipeline prevents duplicate callbacks.'],
    sections: [
      { heading: 'Keep the customer-facing entry point simple', paragraphs: ['One main number can still serve the business. Behind it, call conditions and job rules decide whether staff, overflow or after-hours handling takes the call.'] },
      { heading: 'Route by responsibility, not by panic', bullets: ['Service calls to the service coordinator', 'Project enquiries to the estimator', 'Approved urgent calls to the on-call person', 'Existing bookings to the diary owner', 'Unclear calls to a general review queue with one owner'] },
      { heading: 'Use one job record', paragraphs: ['The call summary, contact details, customer photos, quote and status should stay on one enquiry. If two team members can see the same record, they are less likely to both call the customer or ask for the same details again.'] },
      { heading: 'Give alerts a hierarchy', paragraphs: ['Immediate notifications are for exceptional cases. Normal leads belong in a review queue. A weekly or daily summary can show volume and outcomes without making every staff member live in notification mode.'] },
      { heading: 'Test the system under load', paragraphs: ['Place two or three calls at once, include one urgent case and leave one answer unclear. Confirm that each call is captured, no lead overwrites another and each route reaches the right owner.'], callout: { label: 'ANTI-CHAOS RULE', text: 'One lead, one owner, one current status. Everyone else can see it without owning it.' } },
    ],
    example: { title: 'Three calls in ten minutes', text: 'A new service job goes to Emma’s queue, a project quote routes to James and an approved urgent plumbing call alerts Noah. All three jobs are visible in the shared pipeline. The team does not forward three recordings in a group chat or guess who is calling whom.' },
    productVisual: 'pipeline', productCaption: 'The native job pipeline groups each enquiry by the action it needs while keeping all jobs visible to the team.',
    checklist: ['List call types and owners.', 'Set a default owner for unclear cases.', 'Enable overflow for simultaneous calls.', 'Create one shared job pipeline.', 'Reserve immediate alerts for urgent cases.', 'Test at least three concurrent calls.', 'Review duplicates and unowned jobs weekly.'],
    faqs: [{ question: 'Can one call alert several people?', answer: 'It can, but broad alerts often reduce accountability. Prefer one primary owner with a backup or timed escalation.' }, { question: 'What if the owner is away?', answer: 'Update routing or use an availability schedule. The system cannot know a person is unavailable unless that information is current.' }, { question: 'Can different job types ask different questions?', answer: 'Yes. Job-type rules can collect the facts relevant to that work while keeping shared basics such as contact and location.' }],
    related: ['what-is-overflow-call-answering', 'does-ai-receptionist-replace-office-staff', 'busy-no-answer-after-hours-which-call-rule'],
  },
  {
    slug: 'how-track-missed-calls-costing-jobs', number: 20, category: 'Missed-call recovery',
    title: 'How to Track Whether Missed Calls Are Costing You Jobs',
    description: 'A practical measurement plan for tradies: what to log, which conversion stages matter and how to decide whether missed-call recovery pays.',
    directAnswer: 'Track every inbound call through a small set of outcomes: answered or missed, genuine enquiry or not, suitable or unsuitable, contacted, quoted, booked, won and revenue collected. Compare the conversion and gross profit of recovered calls with answered calls. Without outcomes, call counts cannot tell you whether missed calls cost jobs.',
    readMinutes: 9, heroImage: '/tradie-day-done.jpg', heroAlt: 'Tradie reviewing business calls and job outcomes after the workday',
    secondaryImage: '/blog/tradierelay-dashboard.png', secondaryAlt: 'TradieRelay working dashboard showing jobs and statuses', secondaryCaption: 'The software provides the job record; the business must still mark the real outcome so the data becomes useful.',
    keyPoints: ['Count outcomes, not only rings.', 'Separate unsuitable enquiries from lost suitable work.', 'Use revenue and gross profit to make the keep-or-kill decision.'],
    sections: [
      { heading: 'Create a simple call-to-job funnel', bullets: ['Inbound call', 'Answered or missed', 'Genuine enquiry', 'Suitable for the business', 'Contacted', 'Quoted or offered a booking', 'Won, lost or no decision', 'Revenue and gross profit collected'] },
      { heading: 'Use consistent reason codes', paragraphs: ['When a job does not proceed, mark why: out of area, wrong trade, no capacity, price, no response, competitor, existing customer administration or unknown. A generic “lost” status will not show what call recovery could have changed.'] },
      { heading: 'Compare like with like', paragraphs: ['A recovered after-hours emergency call is not comparable with a weekday project enquiry. Review results by trade, job type, source and time period. Small samples need caution.'] },
      { heading: 'Measure both speed and quality', paragraphs: ['Track acknowledgement time, time to human action, percentage with complete details, qualification rate, booking or quote rate, win rate and recovered gross profit. A faster response is not valuable if it produces poor-fit jobs.'] },
      { heading: 'Run a defined trial and decide', paragraphs: ['Choose a baseline period, then a recovery period with the same definitions. At the review date, keep, change or stop based on the work recovered, the admin removed and the customer experience.'], callout: { label: 'DECISION DATE', text: 'Set the review before launch. A tool without a keep-or-kill date can become another monthly cost nobody evaluates.' } },
    ],
    example: { title: 'A four-week tracking test', text: 'Before TradieRelay, a plumbing business logs missed calls and outcomes for four weeks. Then it runs missed-call recovery for four weeks. It compares genuine enquiries, fit, time to human action, won jobs and gross profit. Spam and out-of-area calls are excluded from the opportunity calculation.' },
    productVisual: 'dashboard', productCaption: 'The working TradieRelay job view captures the details and current status. Accurate outcome marking turns it into useful business evidence.',
    table: { headers: ['Metric', 'Why it matters', 'Do not confuse it with'], rows: [['Missed genuine enquiries', 'Size of recoverable demand', 'All missed calls'], ['Time to human action', 'Real response speed', 'Instant automated acknowledgement'], ['Qualification rate', 'Fit with your business', 'Lead volume'], ['Won gross profit', 'Economic return', 'Quoted revenue']] },
    checklist: ['Choose funnel stages and reason codes.', 'Log a four-week baseline.', 'Keep spam and suppliers separate.', 'Record time to first human action.', 'Mark won revenue and gross margin.', 'Compare by job type and source.', 'Review with a keep, change or stop decision.'],
    faqs: [{ question: 'What if I do not use a CRM?', answer: 'A simple spreadsheet or the TradieRelay job pipeline is enough to start, provided every enquiry gets a consistent outcome.' }, { question: 'How many calls do I need?', answer: 'There is no universal minimum. Small samples can be directionally useful, but avoid treating a few jobs as a stable conversion rate.' }, { question: 'Should I count customer lifetime value?', answer: 'You may track repeat work separately, but start with collected revenue and gross profit. Lifetime estimates can make a weak result look stronger than it is.' }],
    related: ['how-much-could-missed-call-be-worth', 'what-happens-after-tradie-misses-call', 'how-quickly-respond-missed-trade-enquiry'],
  },
];

export function getBlogArticle(slug: string) {
  return blogArticles.find((article) => article.slug === slug);
}
